### ISSUE TITLE
"Load Cargo Changes" false positives

### ISSUE THREAD

**Issue by blueglyph** [intellij-rust/intellij-rust#10158]
## Environment

* **IntelliJ Rust plugin version:** 0.4.188.5205-223
* **Rust toolchain version:** 1.67.0 (fc594f156 2023-01-24) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2022.3.2 Ultimate Edition (IU-223.8617.56)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled

## Problem description

When I add lines of Rust source code, I get the icon "Load Cargo Changes", even though there is no change in the `Cargo.toml` file.
If I remove the line, the icon disappears.

If I click to reload Cargo, it comes back a short while later when the source code is modified again.

It's happening all the time in that project, very annoying, is it because it's a declarative macro? It's just a silly exploratory program, nothing big.

I don't have this problem in other projects. I just did a few tests in another project that is open at the same time, and it doesn't ask me to reload Cargo.

## Steps to reproduce

- Load the project in attachment
- Comment / uncomment line 20, or add a new `println!("");` line

=> "Load Cargo Changes"

## Other information

Here is the project:
[typegen.zip](https://github.com/intellij-rust/intellij-rust/files/10794000/typegen.zip)

I also have the logs but I'm not sure you can use them; I can provide them if there's a safe way to transfer the file.

**Comment by vlad20012** [comment]
Hi!
It happens because your library is a procedural macro.
Every time you change a code of a procedural macro in your project you have to Load Cargo Changes in order to compile the new version of the procedural macro to make it possible to invoke it somewhere (in your case, for example, from tests). Without the reloading, the IDE will not see the changes in your procedural macro, just like it won't see the changed dependencies in `Cargo.toml`. This is why you see this "Load Cargo Changes". When you continuously write your procedural macro, you obviously don't need to invoke  "Load Cargo Changes" action, so you can ignore this notification. This is where similar to continuous writing writing of `Cargo.toml` itself (for example, describing a bunch of `[feature]`s) - you don't need to click "Load Cargo Changes" button at that time, but you will see it anyway. But later, when you will bring your macro to a working state an will want to try to use to, for example, in tests, you will have to invoke "Load Cargo Changes" to let the IDE see the changes in your macro (just like with `Cargo.toml`).
By the way, you can adjust settings to force the IDE reload the project automatically (after any change in `Cargo.toml` or a `build.rs` or a procedural macro crate, etc), but this will likely hurt the performance since project reloading is heavy, and in the case of procedural macro it requires compilation of that procedural macro (hence `cargo build` invocation).

Overall, this is not a false-positive because a change in a procedural macro requires a project reload just like a change in `Cargo.toml`

**Comment by blueglyph** [comment]
Ah, so there's no rlib or other artefact for the procedural macros? I didn't know that. I understand the reason for it, then.

Sorry and thanks for taking the time to explain!
