### ISSUE TITLE
CLion profiler: jump to Rust source error "Declaration not found".

### ISSUE THREAD

**Issue by SebastianJL** [intellij-rust/intellij-rust#10165]
## Environment

* **IntelliJ Rust plugin version:** 0.4.188.5205-223
* **Rust toolchain version:** 1.67.1 (d5a82bbd2 2023-02-07) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.3.2 (CL-223.8617.54)
* **Operating system:** Linux 6.1.0-3-amd64
* **Macro expansion:** enabled

## Problem description
When I do `jump to source` in the clion profiler I simply get a banner telling me "Declaration not found" even for functions that are defined in my project.

## Steps to reproduce
- Create a new binary project with the rust plugin in CLion.
- Profile the following code. I ran the code unoptimized and just stopped the process after some time so it would show up in the flamegraph.
  ```rust
  fn main() {
      println!("Hello, world!");
      foo();
  }
  
  #[inline(never)]
  fn foo() {
      for i in 0..u32::MAX {
          let a = i;
      }
  }
  ```
- Select `Jump to Source` for the `foo()` function in the flamegraph.
![image](https://user-images.githubusercontent.com/11479035/220600457-ac38aebb-b921-4521-94dc-41e756da41a5.png)
- See `Declaration not Found`
![image](https://user-images.githubusercontent.com/11479035/220600804-9ccd4ae9-3089-4d9e-bc1c-8798261cf2f8.png)

**Comment by jman168** [comment]
I have the exact same issue! It's such a shame too because apart from this, CLion is by far the easiest Rust profiling tool I've used so far.

# Environment
* **IntelliJ Rust plugin version:** 0.4.199.5415-232
* **Rust toolchain version:** rustc 1.71.0 (8ede3aae2 2023-07-12)
* **IDE name and version:** CLion 2023.2 (CL-232.8660.186)
* **Operating system:** Ubuntu Linux 5.19.0-50-generic x86_64
* **Macro expansion:** enabled

# Steps to reproduce
Exactly the same as SebastianJL describes.

# Extra Note
I looked at the file that gets generated by CLion (and in turn perf) to confirm that the file and line locations are in fact getting encoded correctly and they are. I can use perf annotate to get file and line numbers as expected.

**Comment by SebastianJL** [comment]
I closed because by now there is RustRover.
