### ISSUE TITLE
Show recursive macro expansion does not reflect proc macro changes

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#10357]
## Environment

* **IntelliJ Rust plugin version:** 0.4.191.5293-231
* **Rust toolchain version:** 1.70.0-nightly (84dd17b56 2023-04-14) aarch64-apple-darwin
* **IDE name and version:** CLion 2023.1.1 (CL-231.8109.222)
* **Operating system:** macOS 13.2.1
* **Macro expansion:** enabled

## Problem description

I'm editing a proc macro, thus need macro expansion to see the generated code.
However, newly added changes are not reflected in macro expansion. I have to clean all the cache and restart the IDE.

## Steps to reproduce

1. Show macro expansion.
2. Modify proc macro implementation
3. Show macro expansion

**Comment by Undin** [comment]
It's expected behaviour. To expand proc macros, the plugin needs the corresponding dynamic libraries created by proc macro lib compilation. It happens during project model loading.

> I have to clean all the cache and restart the IDE.

You don't need to do it.
What you actually need is just to reload the project model. You can do it [manually](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-cargo-tool-window.html#manual-reloading) or enable [auto reloading](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-cargo-tool-window.html#automatic-reloading) of project model.
Note, the last option has some disadvantages if we are talking about proc macros: currently, the plugin detects changes only in `lib.rs` file of the proc macro library, so if you change another file, the plugin won't detect this change and won't recompile the library. Also, most likely you don't expect recompilation (which is quite heavy from a performance point of view) of proc macro lib after each change in it that may happen during development inside proc macro crate.
