### ISSUE TITLE
Configurations got hosed

### ISSUE THREAD

**Issue by nathanaeljones** [intellij-rust/intellij-rust#1044]
One of the recent nighties resulted in a loss of env vars and arguments. The arg string reverted to the default for its class.

**Comment by matklad** [comment]
Yep, that's true! It was kind of intentional: I've changed the internal serialization format and have not provided a migration path. So you have to recreate your defaults (Out of curiosity, is this something specific to your project, or can we improve defaults in the plugin?).

Currently we don't have a strict settings migration policy: things change rather often, so providing a clean migration path is a lot of work (especially because such migrations are rather difficult to test).

This surely should have been mentioned in the changelog though! 

Or do you think we should adopt a stricter policy regarding settings migrations?

**Comment by nathanaeljones** [comment]
The number of configurations I have is difficult to manage - I have 6 crates, each of which has a 'test', 'build', and 'check' (some also have 'run'). 

Most of these need CARGO_INCREMENTAL=1 and -- --no-capture. 

I wish there was a way to update env vars for all Rust configurations...

**Comment by nathanaeljones** [comment]
I wouldn't expect a migration path, just wanted to make sure this was intentional.

Any timeline on when we should try versioning configurations in git?

**Comment by matklad** [comment]
>I wish there was a way to update env vars for all Rust configurations...

Shared configurations are stored as XML in `.idea/runConfigurations`, so it should be possible to use some search/replace to update then en masse. 

> RUST_TEST_THREADS=1, and -- --no-capture.

https://github.com/intellij-rust/intellij-rust/pull/1029 might fix it in a more principal way

>Any timeline on when we should try versioning configurations in git?

No timeline at the moment. I think we will be ready to stabilize run configurations once debugger is ready. 


I'm closing this then, thanks for the report!
