### ISSUE TITLE
When debugging, container types are not displayed properly in the debugging window. Windows w/ Jetbrains only

### ISSUE THREAD

**Issue by Mersid** [intellij-rust/intellij-rust#10549]
## Environment

* **IntelliJ Rust plugin version:** 0.4.195.5408-231
* **Rust toolchain version:** stable-x86_64-pc-windows-msvc
* **IDE name and version:** Jetbrains IntelliJ Ultimate, CLion
* **Operating system:** Windows 10

## Problem description
When debugging, container types are not displayed properly in the debugging window. Observe:

![image](https://github.com/intellij-rust/intellij-rust/assets/30786211/5d37db8e-ad8d-4701-b64e-aed0396df1c4)

Notice that the elements are not displayed; instead, other variables that are not exactly relevant to a developer is. This issue does not exist in Visual Studio Code, running on the same machine:

![image](https://github.com/intellij-rust/intellij-rust/assets/30786211/d90e0da1-018a-42f9-9682-398bb105715b)

In this case, the variables in the collections are rendered correctly.

Additionally, this issue does not appear to exist on Linux. The variables render correctly.

![image](https://github.com/intellij-rust/intellij-rust/assets/30786211/83938961-6ff0-434f-a19b-b43ad6158df6)

## Steps to reproduce

Run Rust with a debugger on Windows, using a JetBrains tool.

```rust

use std::collections::HashMap;

fn main() {
    let a = 16;
    let mut b = HashMap::<i32, i32>::new();
    let mut c = Vec::<i32>::new();

    b.insert(1, 2);
    b.insert(2, 3);
    b.insert(3, 4);

    c.push(1);
    c.push(2);
    c.push(3);
    

    println!("Hello, world!");
}

```

**Comment by Maksim20023** [comment]
Hi! For me, the issue is reproducible on CLion 2022.3, but not in CLion 2023.1.3 - could you please try updating to [CLion 2023.1.3](https://www.jetbrains.com/clion/download/) and see if it persists?

**Comment by Mersid** [comment]
Hello, Maksim

I am already running on 2023.1.3.

**Comment by Maksim20023** [comment]
If you have the latest version of the IDE installed but the issue still persists, it could be related to the current toolchain.
Could you provide me with a screenshot of your toolchain settings?
This setting is located here:
Settings | Build, Execution, Deployment | Toolchains
This will help me to investigate the problem

**Comment by Mersid** [comment]
Thanks, Maksim

Here is the relevant screenshot. Hope this helps.

![image](https://github.com/intellij-rust/intellij-rust/assets/30786211/7ca111ae-da79-41cf-8ae5-21e8a65fdd52)

**Comment by Maksim20023** [comment]
Thank you for providing the screenshot. In same environment, this issue can be reproduced by using renderer options "Rust compiler's renderers" or "No renderers", and can be fixed by using "Bundled renderers".
To check which renderer you are using, go to
Settings | Build, Executions, Deployment | Debugger | Data view | Rust,
and take a look at the "LLDB renderers" option.
If the option is set to "Rust compiler's renderers" or "No renderers", choose "Bundled renderers" from the dropdown menu instead.
Press "Apply" and "OK".
Does that help?

**Comment by Mersid** [comment]
Hello, Maksim

Thank you! The problem appears to be resolved using the instructions you provided. Do you happen to know why this issue is the way it is? Regardless, I appreciate your assistance! :)

**Comment by Maksim20023** [comment]
Hi!
Since you are using the latest versions of the IDE and toolchain, in this case it is more of a feature of the renderer you are using. You can read more about renderers [here](https://plugins.jetbrains.com/plugin/8182-rust/docs/switching-debuggers-and-renderers.html#renderers)
Feel free to close the issue if you don’t have further questions.

**Comment by Mersid** [comment]
Thank you!
