### ISSUE TITLE
The Intellij complains "Cannot start compiler: the SDK is not specified ..."

### ISSUE THREAD

**Issue by NanXiao** [intellij-rust/intellij-rust#1062]
If I use `cargo new hello_cargo --bin` command to create _Rust_ project first, then use _Intellij_->_Open_ to create this _Intellij_ project:  
![1](https://cloud.githubusercontent.com/assets/2338189/23778429/0e448696-0575-11e7-9c35-ce5189766ad9.JPG)
I find the _Build_ and _Run_ commands work OK:  
![2](https://cloud.githubusercontent.com/assets/2338189/23778483/6dc2a620-0575-11e7-8736-eba92817b57d.JPG)

But if I use _Intellij_->_Create New Project_ to create a new project:  
![3](https://cloud.githubusercontent.com/assets/2338189/23778543/c61d9352-0575-11e7-8601-35c5fe9ec7aa.JPG)
Build project will generate following error: "`Cannot start compiler: the SDK is not specified ...`", like this:  
![4](https://cloud.githubusercontent.com/assets/2338189/23778573/f3ea5fe0-0575-11e7-9412-4595c1d30bab.JPG)

What's the differences between these two methods?

**Comment by matklad** [comment]
The Build action currently does nothing, project building is handled by cargo in run configurations. 

But we should try to avoid these SDK errors, fixed in https://github.com/intellij-rust/intellij-rust/commit/203e5049d11b615569e8edc60ef1bf1da6c3aed9

See also https://intellij-rust.github.io/docs/faq.html#make
