### ISSUE TITLE
After implementing Copy Trait, there is still a "Cannot move" error message

### ISSUE THREAD

**Issue by agraellee** [intellij-rust/intellij-rust#10652]
## Environment

* **IntelliJ Rust plugin version:** 0.4.197.5401-231
* **Rust toolchain version:** 1.71.0-nightly (e9e1bbc7a 2023-05-17) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2023.1.1 (CL-231.8109.222)
* **Operating system:** Windows 10.0
* **Macro expansion:** enabled

## Problem description
![Copy bug](https://github.com/intellij-rust/intellij-rust/assets/12542983/692a8e7a-11e4-4676-9bdc-2b264af741a6)

**Comment by Maksim20023** [comment]
Hi! Thank you for reaching us.
I reproduced it in Rust 1.71.0-nightly ( 2023-05-17) which you specify, but it seams that in Rust stable 1.70.0 and the latest nightly releases this issue isn't observed.
Could you please try to change your Rust to the latest stable or nightly and check if the issue is still occurring?
In general, we recommend using the latest stable release of Rust and nightly should be used only if necessary. Because nightly is constantly updated with bug fixes and changes, which might lead to unusual behavior of the Rust plugin

**Comment by agraellee** [comment]
> 

Hi~
This issue only occurs in the Nightly version, and strangely, if we switch from the Stable version to the Nightly version, we have to restart the IDE for this issue to occur.

I have tried the latest 1.72Nightly and haven't found this issue yet, I will observe more.
Thanks
