### ISSUE TITLE
300 line file - intellisense and external linter stop working

### ISSUE THREAD

**Issue by bes** [intellij-rust/intellij-rust#10707]
## Environment

* **IntelliJ Rust plugin version:** 0.4.198.5409-231
* **Rust toolchain version:** 1.71.0
* **IDE name and version:** CLion 2023.1.4 Build #CL-231.9161.40, built on June 20, 2023
* **Operating system:** macOS Ventura

## Problem description
I have a file with a an impl block with 16 functions that each have a `#[wasm_bindgen(js_name = xxxSomething)]` attribute.

Inside some of the functions, intellisense, go to declaration, autocompletion, etc is completely broken, does not work.

Furthermore, "external linter" using Cargo check is completely broken for that file, doesn't even work for the functions that have working intellisense.

## Steps to reproduce

I can't make a small proof-of-concept (i tried but failed). This file is part of a large workspace, but most (all?) other files in the workspace have working intellisense and external linter.

Please let me know how I can help log / debug this issue so that it can be fixed. It is quite annoying.

**Comment by Maksim20023** [comment]
Hi! Thank you for the report!
Could you please send me logs ( [Help | Collect Logs and Diagnostic Data](https://www.jetbrains.com/help/clion/security-model.html#collect_logs)). Please remember that `idea.log` might contain sensitive information (e.g local paths). You can upload your logs to our https://uploads.jetbrains.com/. Uploaded files will only be accessible to JetBrains employees, and we guarantee the privacy of the data.

**Comment by bes** [comment]
Hi, I have uploaded the file -

Upload id: 2023_07_21_RvMUTHYLjuHtDnioGJ4Q1F (file: clion-logs-20230721-0957391047453779638931783.zip)

On the fly linter works _sometimes_ and I can't figure out how / why it decides to work, but most of the time it does not work.

Here is the same session as above, but the linter isn't running on save anymore:

Upload id: 2023_07_21_zogGUeZGfBAWSUfbmkns44 (file: clion-logs-20230721-1000523211655485328588251.zip)

**Comment by witter-deland** [comment]
Please try to remove #[wasm_bindgen(js_name = xxxSomething)], if it works normally after removal, then we have encountered a similar problem

**Comment by bes** [comment]
@witter-deland If I remove those attributes, external linter & intellisense start working. Albeit external linter being much slower than usual.

**Comment by Maksim20023** [comment]
Hi @bes !
Unfortunately, it is unclear what happens without a project with reproducible issue. As a general troubleshooting step, please try to perform [Invalidate caches](https://www.jetbrains.com/help/clion/invalidate-caches.html) with the checked "Clear file system cache and Local History" option. After that, if the issue continues, we kindly ask you to send your project.
Hi @witter-deland ! Could you please share your project with this issue with us? It would be helpful for the investigation process.

**Comment by bes** [comment]
Hi @Maksim20023 unfortunately I can't send a 25k line proprietary project to you. I have done invalidate caches several times and deleted the .idea folder etc before I posted the issue.

**Comment by bes** [comment]
I've really tried to create a small reproducible case to make intellisense work, but as I peel the onion, at some point it just starts working again and I have no way to bring it back except adding back a lot of code that I can't send to you.

For example, I have this code, inside which intellisense doesn't work:

Example 1: Intellisense not working inside this function
```rust
    #[wasm_bindgen(js_name = fetchXxxx)]
    pub fn fetch_xxxx(&self) -> Promise {
        let fut = self.game_handle.fetch_xxxx();
        future_to_promise(async move {
            fut.await
                .map(|_| JsValue::undefined())
                .map_err(|e| JsValue::from(format!("Error {e:?}")))
        })
    }
```

If I add a comment on top of it like this:

Example 2: Intellisense starts working when I add a comment above it
```rust
    // Any old comment
    #[wasm_bindgen(js_name = fetchXxxx)]
    pub fn fetch_xxxx(&self) -> Promise {
        ...
```

Intellisense starts working inside the function again.

And it also starts working if I add a comment inside the function like this:

Example 3: Intellisense starts working when I add a comment inside it
```rust
    #[wasm_bindgen(js_name = fetchXxxx)]
    pub fn fetch_xxxx(&self) -> Promise {
        // Any old comment
        ...
```

Which makes me suspect that there is some part of intellij-rust where parsing the function just breaks down, but starts working again if I add some stuff that breaks out of some critical section.

**Comment by bes** [comment]
@Maksim20023  Is there any other way I can help you than "send logs" or "send code"?

**Comment by vlad20012** [comment]
@bes, The fact that the problem disappears when a comment is added suggests a corrupted cache to be honest. Did you clear the cache properly? I mean, did you check the first checkbox in the cache invalidation window?

![image](https://github.com/intellij-rust/intellij-rust/assets/3221931/079c853d-bbca-4944-8f5d-f7522bfc8462)

**Comment by witter-deland** [comment]
@Maksim20023 
I tried clearing the cache, I tried uninstalling rust, I tried uninstalling clion, but none of them got the highlighting working again. After trial and error, I finally determined that in some cases, the code marked with macro will have this problem, and I can't determine the reason. The project is currently closed source, but if you want to use it to reproduce the problem, I'd like to create a new project and get your folks involved in order to reproduce the problem.
> Hi @bes ! Unfortunately, it is unclear what happens without a project with reproducible issue. As a general troubleshooting step, please try to perform [Invalidate caches](https://www.jetbrains.com/help/clion/invalidate-caches.html) with the checked "Clear file system cache and Local History" option. After that, if the issue continues, we kindly ask you to send your project. Hi @witter-deland ! Could you please share your project with this issue with us? It would be helpful for the investigation process.

**Comment by bes** [comment]
@vlad20012 @Maksim20023 Here's a video I made for you: Upload id: 2023_07_22_25wpZfSEAgxNZP4HLmbBZS (file: invalidate_cache_doesnt_work.mov)

I won't share it publicly, but I will write a synopsis for you & everyone else:

At 00:13 I show that some functions can be "highlighted" (indicating intellisense navigation is working) but others can't.

At 00:15 I use Cmd+B to navigate (as shown by navigation assistant) - doesn't work

At 00:22 There is a fun bug where I can't use the `File` menu without tabbing out to another app first.

At 00:26 I do `Invalidate Caches` with `Clear file system cache...` checked.

At 00:30 CLion is restarted but indexing takes a while, so waiting for that

At 00:58 Indexing is complete and as you said everything is working again 👍 

At 01:00 I restart CLion

At 01:10 I click around, and the function that didn't work with intellisense before now works.

At 01:14 I scoll down to another function (that worked before), that is now not working anymore.

At 01:16 I use Cmd+B to navigate (as shown by navigation assistant) - doesn't work

**Comment by ivan-aksamentov** [comment]
I am experiencing the same problem on a large project. It is not reproducible on smaller projects and it not does not always happen on the larger project either.

The file itself is small, but it imports a giant amount of code and especially struct types from other modules, recursively.

Sometimes, as I edit this file, something bugs and syntax highlighting, completion and lints stop working. Additionally to that, random errors appear in the editor, like a "missing semicolon", while it obviously not the case and the code compiles fine outside of the editor. Once errors appear, they never disappear.

I managed to narrow it down to this `#[wasm_bindgen]` attribute on the `impl` block (not on `struct` itself):

https://github.com/nextstrain/nextclade/blob/9ccea3975b18e66d5f7401dd8e4bb3b8f84811cb/packages_rs/nextclade-web/src/wasm/main.rs#L36-L37

```rust
#[wasm_bindgen]
impl NextcladeWasm {
  ...
}
```

If comment it out the attribute, all features in the editor start working again:

```rust
// #[wasm_bindgen]
impl NextcladeWasm {
  ...
}
```

However, obviously, the code won't compile without the attribute, so I cannot remove it permanently.

My workaround thus, is when I touch the file, I comment away this line temporarily. And when I am done I bring it back. Not amazing, but works for me.

I also noticed that once the bug is triggered, the only way to reset it back into normal state is to comment, wait and then uncomment the attribute. Restarting CLion also helps sometimes, but not always.

Also, there is this small popup when you hover the checkmark in the top right corner of the editor space, and when the bug is active, the popup keeps blinking and the progress bars keeps restarting. This looks like an infinite loop, as it retries something. Here is the video:

<details>
  <summary> [CLICK TO EXPAND] Seizure/epilepsy warning - this video blinks a lot!</summary>
 
https://github.com/intellij-rust/intellij-rust/assets/9403403/89075aa2-8e0b-4103-a880-ff5f2d3cac0d
  
</details>

I believe (but might be wrong) that `#[wasm_bindgen]` has a huge procedural macro underneath, and generates lots of tricky code. 

Perhaps IntelliJ or CLippy at some point stops understanding the code produced by the macro?

Or maybe we are hitting some timing limit in macro expansion or in how external linter is implemented? Is there an option to raise the limits? I found `org.rust.macros.proc.timeout`, but increasing it does not help. Is there a timeout option for Clippy?

Might also be a bug in `wasm_bindgen`  or in clippy.

It's been happening for ages (at least a year, maybe two), so I don't believe IDE, plugin or package versions are relevant, but here they are:


Crates:

https://github.com/nextstrain/nextclade/blob/9ccea3975b18e66d5f7401dd8e4bb3b8f84811cb/packages_rs/nextclade-web/Cargo.toml#L24

Clion:

```
CLion 2023.1.4
Build #CL-231.9161.40, built on June 20, 2023
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-45-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 20000M
Cores: 20
Registry:
    ide.scroll.background.auto=false
    run.processes.with.pty=TRUE
    documentation.show.toolbar=true
    contrast.scrollbars.alpha.level=0
    editor.full.width.scrollbar=true
    debugger.attach.dialog.enabled=true
    ide.balloon.shadow.size=0
    eslint.additional.file.extensions=ts,tsx
    org.rust.external.linter.max.duration=30000
    credentialStore.linux.prefer.kwallet=true
    org.rust.cargo.lock.update.delay.threshold=15000
    org.rust.macros.proc.timeout=20000

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (231.9161.47)
    org.editorconfig.editorconfigjetbrains (231.8770.3)
    me.laria.code.idea_caseconv (0.7.1)
    String Manipulation (9.9.0)
    com.jakecoffman.theme (1.4)
    org.jetbrains.plugins.rest (231.8770.3)
    org.rust.lang (0.4.198.5409-231)
    com.intellij.grpc (231.9011.3)
    idea.plugin.protoeditor (231.8109.91)
    com.github.b3er.idea.plugins.arc.browser (0.32)
    com.mallowigi (90.0.0)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-231)
    com.chylex.intellij.inspectionlens (1.3.0)
    com.laravel_idea.tailwind (1.4.1)
    ru.adelf.idea.dotenv (2023.1)

Current Desktop: Unity:Unity7:ubuntu
```

P.S. If I manage to strip the code and narrow down the problem, I'll post a minimal repro. But I am quite busy at this time, so it might never happen.

**Comment by ivan-aksamentov** [comment]
I also noticed that the opposite is true: if there ARE errors in code, they won't be detected while the bug is active.

Also you can see that the CPU consumption is much higher when the attribute is uncommented. It really tries to do something heavy in the background.

<details>
  <summary>[CLICK TO EXPAND] Seizure/epilepsy warning - this video blinks a lot!
</summary>

https://github.com/intellij-rust/intellij-rust/assets/9403403/df553817-dc51-416b-ae33-8baad2027239
  
</details>


I uploaded logs to https://uploads.jetbrains.com/
```
Upload id: 2023_07_24_A1FdtfxF1CVtLAeKnnEocZ (files: clion-logs-20230724-04314515149821478616438870.zip and 3 more)
```
But if it's really an infinite loop, logs might have limited

**Comment by bes** [comment]
I have 400% CPU usage from clion when my project is open, but normal CPU usage with other Rust projects. I don't know if it's related to this bug, but maybe?

Please, please, please, I don't like vscode/fleet/rust-analyzer. I really don't want to switch. But this bug is killing intellij-rust for me.

Is it possible to setup some sort of live debugging session where someone from JetBrains can use my project to find out what is wrong? Or are there other ways to debug this? @Maksim20023 @vlad20012

**Comment by Maksim20023** [comment]
Hello @bes 
Unfortunately, we don’t have an estimated time to resolve the issue entirely. Rest assured that I have forwarded all the information, including the Nextclade project from @ivan-aksamentov, to our development team, and I hope they can fix this in future updates.
However, I noticed this problem is not reproduced in the 0.4.197 Rust plugin. And In the Rust plugin 0.4.198 version, experimental feature `org.rust.macros.proc.attr` was enabled by default #10607. So try to [disable](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)  `org.rust.macros.proc.attr` feature, and please write a response on whether it helped.

**Comment by Maksim20023** [comment]
Hi!
Due to the launch of the [RustRover](https://www.jetbrains.com/rust/) and [Rust support portal](https://intellij-support.jetbrains.com/hc/en-us/?rustrover), we will no longer be using the GitHub issue tracker for support requests related to RustRover or the new [Rust plugin](https://plugins.jetbrains.com/plugin/22407-rust). So, we moved this issue to our Rust issue tracker: [link](https://youtrack.jetbrains.com/issue/RUST-11484/IntelliSense-and-external-linter-stop-working-when-using-wasmbindgen-attribute)

We are also glad to say this issue has been fixed in RustRover and the new Rust plugin.
