### ISSUE TITLE
Cannot Move for types implementing Copy trait

### ISSUE THREAD

**Issue by Datoclement** [intellij-rust/intellij-rust#10800]
## Environment

* **IntelliJ Rust plugin version:0.4.194.5382-223**
* **Rust toolchain version:cargo 1.71.0 (cfd3bbd8f 2023-06-08)**
* **IDE name and version:PyCharm 2022.3 #PY-223.7571.203 Runtime version: 17.0.5+1-b653.14 aarch64**
* **Operating system:MacOS Ventura 13.3.1(a)(22E772610a)**

## Problem description
Warn of `cannot move` error for types that implement `Copy` trait.

## Steps to reproduce
![The reproducing code and the symptom](https://github.com/intellij-rust/intellij-rust/assets/14246001/1e9d7b93-ddb4-4be3-b39d-01e58ae42168)

```rust
#[allow(unused)]
fn f(_:usize){}
#[allow(unused)]
fn g(x:&usize){
    f(*x)
}
```

**Comment by Maksim20023** [comment]
Hi! Thank you for reaching us.
This issue has been fixed (please, see [PR 10528](https://github.com/intellij-rust/intellij-rust/pull/10528)), and the current Rust plugin version is [0.4.200.5421](https://plugins.jetbrains.com/plugin/8182-rust/versions/stable/373256). 
Due to using Pycharm 2022 version, you cannot install a Rast plugin version higher than 0.4.194. So, please, update your [PyCharm](https://www.jetbrains.com/help/pycharm/update.html) first, and after that, [plugin](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#update), and try to reproduce the issue.
