### ISSUE TITLE
external linter(cargo check) on the fly not working on #[path= "../somethings.rs"] module

### ISSUE THREAD

**Issue by oicu0619** [intellij-rust/intellij-rust#10848]
## Environment

* **IntelliJ Rust plugin version:**
0.4.200.5421-232
* **Rust toolchain version:**
rustc 1.71.1 (eb26296b5 2023-08-03)
* **IDE name and version:**
CLion 2023.2.1 Build #CL-232.9559.58
* **Operating system:**
Ubuntu 22.04.3 LTS

## Problem description
external linter(cargo check) on the fly not working on #[path= "../somethings.rs"] module. If fails to detect errors

## Steps to reproduce
demo of the issue is on https://github.com/oicu0619/intellij_rust_plugin_bug_demo
As you can see in the figure, cargo check fail to see the bug, due to the module is introduced by #[path= "../somethings.rs"]
![image](https://github.com/intellij-rust/intellij-rust/assets/42464901/4cbc33f5-03bf-4028-b961-e54fe5b8cf67)
if it is introduced by normal "mod something", it can be found by on the fly cargo check.
![image](https://github.com/intellij-rust/intellij-rust/assets/42464901/c51302e7-b7c0-4c0c-816a-70be56f0e3f5)
command line cargo check will always found the error.
![image](https://github.com/intellij-rust/intellij-rust/assets/42464901/f699d34a-7d55-4fc2-aca0-33758fe65179)

**Comment by Maksim20023** [comment]
Hi!
Due to the launch of the [RustRover](https://www.jetbrains.com/rust/)  and [Rust support portal](https://intellij-support.jetbrains.com/hc/en-us/?rustrover),  we will no longer be using the GitHub issue tracker for support requests related to RustRover or the new [Rust plugin](https://plugins.jetbrains.com/plugin/22407-rust). So, we moved this issue to our Rust issue tracker: [link](https://youtrack.jetbrains.com/issue/RUST-11852/False-negative-E0382-borrow-of-moved-value-in-path-..-somethings.rs-module)
