### ISSUE TITLE
Support IntelliJ Path variables for the Cargo toolchain location

### ISSUE THREAD

**Issue by profiluefter** [intellij-rust/intellij-rust#10851]
## Environment

* **IntelliJ Rust plugin version:** 0.4.200.5421-232
* **Rust toolchain version:** 1.72.0 (5680fa18f 2023-08-23) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2023.2 Ultimate Edition (IU-232.8660.185)
* **Operating system:** Linux 6.1.47 (NixOS)
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr

## Problem description

It would be nice if I could specify [Path variables](https://www.jetbrains.com/help/idea/absolute-path-variables.html) in the Toolchain Location settings field.

## Steps to reproduce

1. Create a new path variable in the settings
![image](https://github.com/intellij-rust/intellij-rust/assets/18028031/03f49cea-16e6-4a77-b704-5994ad1dc018)
2. Set toolchain location to the name of the new variable (enclosed in dollar)
![image](https://github.com/intellij-rust/intellij-rust/assets/18028031/223ada26-216b-4c47-b281-1eeced41152d)
3. Try to save and see the error message that the path litterally

## Additional notes / workaround

I noticed that the `workspace.xml` file which contains the data of the setting uses path variables by default. It had a value along the lines of `$USER_HOME$/.cargo/...`. I replaced it with `$RUST_TOOLCHAIN$` (the name of my variable) and it displayed the correct path in the settings and the cargo sync then recognized the toolchain! So it seems like this only needs to be changed in the validator.

**Comment by Maksim20023** [comment]
Hi! Thank you for the report.
I moved your issue to our [Rust issue tracker](https://youtrack.jetbrains.com/issue/RUST-11771/Feature-request-Support-IntelliJ-Path-variables-for-the-Cargo-toolchain-location). Due to the launch of the [RustRover](https://www.jetbrains.com/rust/)  and [Rust support portal](https://intellij-support.jetbrains.com/hc/en-us/?rustrover), we will no longer be using the GitHub issue tracker for support requests related to RustRover or the new [Rust plugin](https://plugins.jetbrains.com/plugin/22407-rust)
