### ISSUE TITLE
[Feature Request] Code analysis based on remote environment

### ISSUE THREAD

**Issue by XOR-op** [intellij-rust/intellij-rust#10852]
## Environment

* **IntelliJ Rust plugin version:** 0.4.200.5421-232
* **Rust toolchain version:** 1.72.0 (5680fa18f 2023-08-23) aarch64-apple-darwin
* **IDE name and version:** CLion 2023.2.1 (CL-232.9559.58)
* **Operating system:** macOS 13.5
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.macros.proc

## Problem description
During remote development, libraries' behaviors are usually different. (Functions or structs controlled by 'target_os', or bindings generated on the remote platform etc.) However, intellij-rust seems to only analyze code on the local environment, since I don't find any option to do that. Without this functionality, it's difficult to develop cross-platform softwares with platform-specific libraries and get correct highlight and completion from generated bindings.

## Possible solutions
1. Add an option to perform code analysis entirely on a remote machine, like what remote run/debug have been done.
2. Override some flags (e.g. target_os) and copy generated bindings.rs from the remote machine, then perform code analysis locally.

**Comment by Maksim20023** [comment]
Hi!
Due to the launch of the [RustRover](https://www.jetbrains.com/rust/)  and [Rust support portal](https://intellij-support.jetbrains.com/hc/en-us/?rustrover),  we will no longer be using the GitHub issue tracker for support requests related to RustRover or the new Rust plugin. So, we moved this issue to our Rust issue tracker: [link](https://youtrack.jetbrains.com/issue/RUST-11762/Feature-Request-Code-analysis-based-on-remote-environment)
