### ISSUE TITLE
PyCharm 2023.2.1 line breakpoints not working

### ISSUE THREAD

**Issue by s-l-young** [intellij-rust/intellij-rust#10864]
## Environment

* **IntelliJ Rust plugin version:** 0.4.200.5421-232
* **Rust toolchain version:** 1.72.0 (5680fa18f 2023-08-23) stable-x86_64-unknown-linux-gnu (
  default)
* **IDE name and version:** PyCharm 2023.2.1 (Professional Edition) (Build #PY-232.9559.58)
* **Operating system:** Linux 5.15.0-83-generic

## Problem description

Line breakpoints do not work as expected. When running in debug mode, line breakpoints are marked
with a gray icon signifying that they do not work, with the following hint when hovering over them:
> The breakpoint will not currently be hit. No executable code is associated with this line.

Panic breakpoints on the other hand appear to work.

Consulting the following issues did not yield working solutions:
- #10486
- #10316
- #10263
- #10006
- #9701
- #8621
- #8526
- #8419
- #7698
- #7958
- #7802

## Steps to reproduce

1. In PyCharm, create a new Rust project with toolchain version 1.72.0 with the project template
   “Binary (application)”.
2. Replace the contents of `main.rs` with the following:
   ```rust
   fn main() {
       println!("Hello, world!");
       panic!();
   }
   ```
3. Set a line breakpoint in `main.rs` line 2 (the `println`-line).
4. Debug 'Run' (Run main.rs in debug mode).

### Expected behavior

The program execution pauses at the specified breakpoint before line 2 in `main.rs`.

### Observed behavior

The program execution pauses in reaction to panicking.

**Comment by Maksim20023** [comment]
Hi! Thank you for the report.
I moved your issue to our [Rust issue tracker](https://youtrack.jetbrains.com/issue/RUST-11848/PyCharm-2023.2.1-line-breakpoints-not-working). Due to the launch of the [RustRover](https://www.jetbrains.com/rust/)  and [Rust support portal](https://intellij-support.jetbrains.com/hc/en-us/?rustrover),  we will no longer be using the GitHub issue tracker for support requests related to RustRover or the new [Rust plugin](https://plugins.jetbrains.com/plugin/22407-rust)
