### ISSUE TITLE
missing type inference for this simple expression

### ISSUE THREAD

**Issue by LastExceed** [intellij-rust/intellij-rust#10865]
```rust
fn foo<T>(f: impl Fn() -> T) -> T {
    f()
}

fn bar() -> bool {
    true
}

fn main() {
    let x = foo(bar);
}
```

quick documentation on `x` shows type `<unknown>` and no auto-complete suggestions are available when typing `x.`

adding `let y: i32 = x` shows the expected type mismatch error (`expected i32, found bool`) so it's definitely a problem with intellij-rust

workarounds:
* use `fn()` instead of `impl Fn()` - `fn foo<T>(f: fn() -> T) -> T { f() }`
* wrap `bar` in a closure - `let x = foo(|| bar());`
* specify the type explicitly (via type annotation) - `let x: bool = foo(bar);`
* specify the type explicitly (via turbofish) - `let x = foo::<bool>(bar);`

## Environment

* **IntelliJ Rust plugin version:** 0.4.200.5421-232
* **Rust toolchain version:** 1.74.0-nightly (e3abbd499 2023-09-06) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2023.2.1 (CL-232.9559.58)
* **Operating system:** Windows 11.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.cargo.features.settings.gutter, org.rust.ide.intentions.macros.function-like, org.rust.macros.proc, org.rust.coverage.source, org.rust.ssr

**Comment by Maksim20023** [comment]
Hi! Thank you for the report.
I moved your issue to our [Rust issue tracker](https://youtrack.jetbrains.com/issue/RUST-11844/missing-type-inference-for-this-simple-expression). Due to the launch of the RustRover https://www.jetbrains.com/rust/ and Rust support portal, https://intellij-support.jetbrains.com/hc/en-us/?rustrover we will no longer be using the GitHub issue tracker for support requests related to RustRover or the new [Rust plugin](https://plugins.jetbrains.com/plugin/22407-rust)

**Comment by LastExceed** [comment]
now thats an interesting way to learn about the release of a new jb product. crazy timing
