### ISSUE TITLE
Using rustfmt should be more embraced

### ISSUE THREAD

**Issue by fulara** [intellij-rust/intellij-rust#1087]
I think the RustFmt should be preferred way of formatting the code over building the formatter inside the plugin. This has a lot of advantages. Biggest one is probably that you would no longer have to maintain the formatter engine.  
The most drastic measure could be just to by default block the plugin's formatter and by default scream message to install the rustfmt. :). The block could be configurable in the options - novice users would probably prefer to use rustfmt than the Plugin's fmt, and seasoned users if they like the built in formatter could switch that in the options.  
Also, right now its unintuitive to switch to rustfmt over builtin plugin

Since more attention would be paid to integrating of rustfmt then some handling of its stdout would be welcome.  for example:
a) When rustfmt stdouts nothing - that means it formatter correctly a pop-up should be shown that formatting went ok
b) When rustfmt does not know how to split the lines, it outputs file and line number where the problem occured, this should be clickable

**Comment by matklad** [comment]
I would say that we'll need to do both :) Let me explain this a little bit!

IntelliJ and rustfmt use different approaches to formatting. rustfmt will completely rewrite your code to fit the Rust style. IntelliJ will just try to enforce certain rules (like, "there should be a space after comma"), but it will leave the general structure of the code intact. That is, we don't try to maintain a line length limit and let the user control breaking complex expressions into several lines.

This means that IntelliJ formater can be just "less strict" then `rustfmt`: code formatter by `rustfmt` won't be changed by IntelliJ, but not necessary vice verse. And this should be relatively easy to achieve as soon as official style guide is finished, [our implementation](https://github.com/intellij-rust/intellij-rust/blob/b467a49b08ae011863c7e264be5f69d58a3b5df2/src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt#L32-L138) is much shorter than the one in rustfmt. 

And we do need our own formatter because it is used for more than just formatting. For example, when you press `Enter` formatting model is used to determine if the caret should be indented or not. Formatter is also crucial for quick fixes, intentions and refactoring: it's next to impossible to generate good looking code manually, and formatter saves the day.

Improving `rustfmt` UI in the plugin is definitely something we should do though!

**Comment by fulara** [comment]
I am just stating my opinion here - apologies If I am too aggressive with these. :)  

Okay, it seems unfortunatelly that two engines is the requirement, however I do still think that the `rustfmt` should be a default choice of the plugin, mainly because as of right now the plugin' formatter outputs different code than `rustfmt`. Use of plugin' formatter should be only applied for actions. plugin' formatter also inserts some useful blank lines sometimes - so probably a 'code cleanup'  action could invoke this?

As to aggressivenes of formatter - When someone runs the formatter on whole file - he probably would rather have the aggressive approach used by `rustfmt`. If that person wants to only format a chunk of code then integration with rustfmt should be able to pass the selected lines as an argument to `rustfmt`.  

I think that the rustfmt way of formatting should be standard. By standard I mean that plugin' formatter should never conflict with the rustfmt.  
By conflict I mean that running `rustfmt` -> `plugin` and then running `rustfmt` again should not introduce any changes.   
This is probably quite hard to do. With the build i am using which is pretty recent.  I can see multiple conflicts between the formatters - especially when handling the `assert_eq!` macro.  
If that goal is achievable then excellent test suite could be prepared for testing the plugin' formatter - just download bunch of rust code, run rustfmt then intellij' formatter and check for differences.

**Comment by matklad** [comment]
> With the build i am using which is pretty recent. I can see multiple conflicts between the formatters 

Yeah, the situation is definitely not perfect at the moment! rustfmt is a moving target because the formatting rules are not yet finished. As soon as https://github.com/rust-lang-nursery/fmt-rfcs is done, we'll make sure that IntelliJ and `rustfmt` agree :) 

>I can see multiple conflicts between the formatters

It would be useful to find particular examples as bugs!

**Comment by CAD97** [comment]
Here's a quick idea that could potentially make using rustfmt easier:

If `rustfmt.toml`/`.rustfmt.toml` exists, when running the action `Reformat File` across the whole file, call into `rustfmt`. In any case, once `rustfmt`'s rules and configuration stabilize, we should definitely make sure to use the configuration in that file. Or at the very least offer an automated way to sync that file and the style settings in the plugin.

**Comment by perryprog** [comment]
Maybe a mix would be nice? i.e. have a setting to use `rustfmt` instead of the format engine for a full file reformat, and then use the format engine to know where to put the caret on a newline.

This probably won't work too well though, until the format engine and `rustfmt` match and all of that gets working.

**Comment by Avi-D** [comment]
Perhaps the necessities(intentions and what not) could be provided by intellij-rust's formatter, while everything else could be farmed out to `rustfmt`. Everything else meaning the aforementioned full file formats and formatting of subsections. Even things as small as trailing commas could be handled by `rustfmt`. This would make intellij-rust respect `rustfmt.toml` thereby supporting custom `rustfmt` configurations.

This could be done in a similar manner to how `rls` going to support Formatting ranges: [issue](https://github.com/rust-lang-nursery/rls/issues/333), [pull request](https://github.com/rust-lang-nursery/rls/pull/346), [progress](https://github.com/rust-lang-nursery/rls/issues/3).

**Comment by Juici** [comment]
I'm gonna bump this with a suggestion.

Have to option to select the formatter in settings. Like an option to use rustfmt or another custom formatter, so that users have the option of using rustfmt instead of the IntelliJ formatter.

I personally use rustfmt and have to use a separate keybind for it; it sucks that I can't just have rustfmt be used when I hit the default formatter keybind, without overriding the formatter which prevents it from working on other file types.

*If there is a way to do this and I'm being an idiot please tell me.*

**Comment by fulara** [comment]
Cant you just disabled the defualt formatting key and replace it with external-tools rust-fmt? I think I did that. Its not ideal but its something.

Is it even possible to use rust-fmt constantly? I think the rust-fmt requiers your code to be syntactically correct? Maybe I am wrong.

**Comment by Juici** [comment]
@fulara

Disabling the default keybind prevents you from using it for other file types.

**Comment by brokenthorn** [comment]
Regarding the issue of embracing, I suggest this: https://github.com/intellij-rust/intellij-rust/issues/2588#issuecomment-447016324

**Comment by tobia** [comment]
Just putting in my 2¢ as a novice Rust developer.

I really, really like the (original?) idea behind `gofmt`, which then cascaded into `rustfmt`, `prettier`, and many other such tools. Performing an automatic full-file re-formatting "on save," especially including a fixed line-length limit, frees my mind from having to deal with *any* whitespace whatsoever, because I know it will be overwritten by the formatter anyways as soon as I press Ctrl-S, and lets me focus on the actual code.

"On save" is in quotes because IntelliJ IDEA seems to do an automatic, continuous save of sources (correct me if I'm wrong.) But I still like to press Ctrl-S after every minor batch of work, so that should count as a save action, triggering the reformatting.

Right now I'm finding it hard to get this behaviour in IntelliJ IDEA. I got it working for Kotlin by installing the Save Actions plugin, which has "Optimize imports" and "Reformat file" as options to be performed automatically on Ctrl-S. But in Rust it seems to be invoking the internal formatter, which produces a different result than `rustfmt`, and thus completely misses the point of `rustfmt`, which is *having everybody use the same formatter.*

How can I get the behaviour of running `rustfmt` on all changed files whenever I press Ctrl-S? The internal formatter might be useful for computing indentation after newlines, or things like that, but I don't really care for it and wouldn't mind turning it off for Rust, it that was required to get IntelliJ IDEA to use `rustfmt` exclusively.

**Comment by Juici** [comment]
> How can I get the behaviour of running `rustfmt` on all changed files whenever I press Ctrl-S? The internal formatter might be useful for computing indentation after newlines, or things like that, but I don't really care for it and wouldn't mind turning it off for Rust, it that was required to get IntelliJ IDEA to use `rustfmt` exclusively.

@tobia Personally I use CLion whenever writing in Rust, I have Ctrl-Shift-S bound to invoke `rustfmt` on the current file in order to format it. I try to keep consistency by also binding Ctrl-Shift-S as a secondary format binding in my other IntelliJ IDEs. Of course that is a workaround, but it works for me right now.

To answer your question about the on-save formatting, you might want to look into [File Watchers](https://www.jetbrains.com/help/idea/using-file-watchers.html), which I know from experience (having used them myself for this purpose before) can run `rustfmt` when you make changes to your code.

I personally stopped using File Watchers for this purpose, because I found that when tabbing out to look at a reference document, such as API documentation, the IDE would invoke the File Watcher and try to format the code. Often times, this would be when the code was not in a syntactically correct state; this would result in a lot of errors, so I decided to settle on the manual Ctrl-Shift-S approach.

> Have to option to select the formatter in settings. Like an option to use rustfmt or another custom formatter, so that users have the option of using rustfmt instead of the IntelliJ formatter.

My previous suggestion, seen quoted above, was from the view of someone who has already been using my workaround for a number of months at the time. I am of the opinion that using `rustfmt` is the way forward and that variance in code styles are often a cause for problems, especially in the open source community.

I don't mind people using different styles per se, but using a configuration file like `rustfmt.toml` in order to standardise the formatting styles for a project is definitely the best approach in my view.

Since one issue that can be raised is that `rustfmt` requires syntactically correct code in order to format, I am of the opinion that the intellij-rust formatter could work around this by validating the code for syntax and attempting to run `rustfmt` on syntactically correct code snippets (maybe as temporary files). This would obviously have performance problems, but could be a good approach.

**Comment by vlad20012** [comment]
@tobia You can also get the desired behavior with this workaround:
1. Open the settings (ctrl+alt+S)
2. Unmap the "save" action 
![image](https://user-images.githubusercontent.com/3221931/52977135-2b5fd300-33dd-11e9-9237-0b8c12ee3b52.png)
3. Assign the "ctrl+S" kotkey to "Reformat File with Rustfmt" action
![image](https://user-images.githubusercontent.com/3221931/52977186-619d5280-33dd-11e9-8aaa-79bde4a280fb.png)
![image](https://user-images.githubusercontent.com/3221931/52977222-872a5c00-33dd-11e9-9d95-2c5307f7b5f9.png)

Then ctrl+S will work literally as you described. Additionally, ctrl+S will continue to work as "save all" just because "Reformat File with Rustfmt" saves all files before launch =D. The one possible problem is that now ctrl+S will not save anything if invoked not in rust file 😥. BUT in IntelliJ IDEs you usually don't really need to to manually save anything. Sooo this approach should works

**Comment by tobia** [comment]
@vlad20012 Remapping Ctrl-S will not save anything if invoked on a file other than rust, as you mentioned. Also it won't re-format any other changed file other than the foremost one. It's a nice hack, but I might as well use a different hotkey.

IMHO the proper solution is for the Rust plugin to use `rustfmt` whenever it's going to re-format an entire file (whether a `rustfmt.toml` is present or not) and only use its internal engine for incremental changes. Are the plugin developers against this idea, for any reasons? Should I go ahead and make a pull request?

**Comment by vlad20012** [comment]
> IMHO the proper solution is for the Rust plugin to use `rustfmt` whenever it's going to re-format an entire file (whether a `rustfmt.toml` is present or not) and only use its internal engine for incremental changes. Are the plugin developers against this idea, for any reason?

1. A plugin can't just override the behavior of the platform "Reformat Code" action (ctrl+alt+L). Most likely, we have to change something in the platform to do this (we try to avoid touching the platform as much as possible).
2. Run rustfmt is likely slow
3. Rustfmt can't process an invalid code
4. The formatter is something very fundamental in the platform and we can't control when it is called. And it scares.

We'll try to discuss it and come up with something. Right now I don't see a solution except having a separate action for running rustfmt. But maybe we can make it more convenient. At least we can add a button on cargo panel and assign a default shortcut.

**Comment by vlad20012** [comment]
We'll add an option to reformat changed files on save with #3490

**Comment by kluen** [comment]
@vlad20012 Perhaps it is possible to look at how other plugins handle this issue?
For example using the Scala plugin, when a `.scalafmt.conf` is detected in the project, IntelliJ will prompt the user to use either Scalafmt or the internal formatter. It can also be set in the preferences.
There is only one shortcut for formatting.
Not sure if this helps, but maybe one can get some ideas there.

**Comment by vlad20012** [comment]
Since #5704 there is an option to use `Rustfmt` instead of built-in formatter in the case of **whole file** formatting by:
1. `Code | Reformat Code` (`Ctrl + Alt + L`) action **without text selection**
2. `Code | Reformat File ...` (`Ctrl + Alt + Shift + L`) action with `Whole file` option

You can try it now on the nightly plugin (see [instructions](https://intellij-rust.github.io/install.html)) or try it later in the [next release](https://github.com/intellij-rust/intellij-rust/milestone/40).

The option can be enabled in `Settings | Languages & Frameworks | Rust | Rustfmt | Use rustfmt instead of built-in formatter`.

![image](https://user-images.githubusercontent.com/3221931/93435939-c7f89880-f8d2-11ea-89de-88c104c052f5.png)

Let's move the further discussion to #6145
