### ISSUE TITLE
Inline variable refactoring

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1095]
We have support for "Introduce a variable" already. It would be nice to be able to do the opposite and inline variables as well. 

The initial version should just inline the expression, without checking any borrowing related things.

**Comment by mcarlin** [comment]
Cool if I grab this one?

**Comment by matklad** [comment]
@mcarlin sure!

**Comment by vlad20012** [comment]
The issue seems still up for grab =)
As sample, "Introduce a variable" refactoring located [here](https://github.com/intellij-rust/intellij-rust/blob/fd96ed4524a6365ea89bfad3e761954a1361edbc/src/main/kotlin/org/rust/lang/refactoring/RsLocalVariableHandler.kt) and tests for it - [here](https://github.com/intellij-rust/intellij-rust/blob/fd96ed4524a6365ea89bfad3e761954a1361edbc/src/test/kotlin/org/rust/lang/refactoring/RsLocalVariableHandlerTest.kt)

**Comment by matklad** [comment]
As an example, a similar feature for Kotlin is implemented [here](https://github.com/JetBrains/kotlin/blob/941e5ae1b2c7a3e16d1c9cdf57d647bd2d3f0a35/idea/src/org/jetbrains/kotlin/idea/refactoring/inline/KotlinInlineValHandler.kt).

**Comment by snpefk** [comment]
I'd like to grab this

**Comment by snpefk** [comment]
Hello @matklad! 

Looks like all methods in `RsRefactoringSupportProvider` overrides methods from `RefactoringSupportProvider` which lies in intellij source code. Should I add changes to Intellij codebase or it's not a big deal and I just add new method to `RsRefactoringSupportProvider`?
