### ISSUE TITLE
Sometimes weird highlighting in doc code

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#1237]
From time time to time, my example code in doc comments gets highlighted like usual markdown. Editing something fixes it.

**Comment by CAD97** [comment]
In a markdown (`.md`) file (handled by the JetBrains plugin "Markdown support"), using a `` ```rust`` code block leads to highlighting the code properly:
![Rust in Markdown](https://cloud.githubusercontent.com/assets/5992217/26232605/577104de-3c25-11e7-9ce0-1fc0bb0e4527.png)

However, within doc comments (`///`) in a Rust file (`.rs`) (handled by this plugin), I have never gotten rust syntax highlighting for code blocks (`` ``` ``):
![Rust in doc comment in Rust](https://cloud.githubusercontent.com/assets/5992217/26232760/7ff5c9ca-3c26-11e7-9790-275f7191678d.png)

I am using version 0.1.0.1991 of the plugin.
![Version 0.1.0.1991](https://cloud.githubusercontent.com/assets/5992217/26232877/4ec6dcbc-3c27-11e7-9024-431936804202.png)

If the plugin is supposed to be treating code blocks in markdown doc comments as Rust, then it's hasn't ever done so for me. (I have tried using `` ```rust`` as in Markdown, but that doesn't change anything. Neither do any other languages which successfully embed in Markdown.)

<hr />

Implementation speculation below.

IIRC, the IDEA platform provides a concept of "embedded languages", and that's how the Markdown plugin works, when it sees `` ```lang``` it sets the language to display as `lang` until the closing of the code block, and IDEA then delegates to the correct plugin to colorize the code. This plugin could _theoretically_ use embedded Markdown to handle the documentation comments, except for a couple problems:

- Every line starts with `///` which is not a part of the Markdown syntax. This might be workaround-able, but I don't know enough of the IDEA plugin system to know for sure.
- Rustdoc code blocks `` ``` `` default to treatment as rust code (`` ```rust``) when unspecified, unlike pure Markdown which defaults to plain text (`` ```text``).
- Rust code in documentation comments has extra syntax elements -- specifically, `# code` to hide the code from generated documentation -- so needs to be treated specially.

In an ideal world, doc comments would be highlighted as proper markdown, with code blocks defaulting to rust highlighting (with `#` support), and code blocks labeled otherwise (like `` ```c`` or `` ```text``) passing through to the correct plugin for colorization. In a perfect world, this could be handled by delegating to the Markdown plugin while specifying the default code block highlighting, so that this plugin doesn't have to know anything about Markdown. I don't know how realistic either of those are, however.

**Comment by alygin** [comment]
More discussion on the related topic can be found in #618
