### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1252]
![1](https://cloud.githubusercontent.com/assets/873919/26278302/c3f29732-3d9f-11e7-9156-d3329d29a94f.gif)

Chances are I'm just not aware how to configure a project to make it working. Please, help.

**Comment by alygin** [comment]
It looks like you have the "Test t1" run configuration that you created by running the `t1()` test via the gutter icon, then clicking "Save 'Test t1' Configuration" from the "Select Run/Debug Configuration" dropdown list and then manually changing its parameters to actually run the program instead of the test. If so, the problem will gone if you delete the "Test t1" run configuration.

There's a kind of [prioritisation of run configurations](https://github.com/intellij-rust/intellij-rust/blob/7ed670ae0ae2f3e2eeb2521d06444eafb343aa0a/src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunLineMarkerContributor.kt#L25) that doesn't seem to work properly, we need to fix it.

**Comment by matklad** [comment]
>There's a kind of prioritisation of run configurations that doesn't seem to work properly, we need to fix it.

I've actually looked into this, and I am not sure how to fix this properly. The problem is that if idea finds an existing configuration which fits the given context, it won't try to create any other configurations. That is, we correctly prioritize test and executable configurations in this case, but the problem is that we don't even try to compare these two configurations in this case.
