### ISSUE TITLE
"Add derive clause" quick action is shown even though there is `derive` attribute already

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1276]
![image](https://cloud.githubusercontent.com/assets/873919/26522239/a4ec2a0a-4304-11e7-8a48-a696704b63ba.png)

**Comment by matklad** [comment]
It is intentional: you can invoke it anywhere inside the struct, an it'll place the caret at the end of the `derive` attribute, so that you can start typing immediately. 

It's somewhat useful, but not super useful, but, because there are only a couple of intentions available there, I think we should maintain the status quo.

**Comment by vasily-kirichenko** [comment]
I see. Thanks for explanation.
