### ISSUE TITLE
Provide option to create a library project

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1277]
Currently there's no way to create a library project, not an executable one:

![image](https://cloud.githubusercontent.com/assets/873919/26522467/3005605c-430a-11e7-9e13-2e0c0e0937ef.png)

**Comment by Gedweb** [comment]
just 2 line block in `Cargo.toml
````
[lib]
name = "libname"
```

**Comment by vasily-kirichenko** [comment]
and rename main.rs to lib.rs

**Comment by owmywrists** [comment]
I've tried the above and yet I still have an unexecutable project.

**Comment by Gedweb** [comment]
@owmywrists for running library you need create example binary internally in library.
By the `[[bin]]` section, you can find example in any popular crate.

**Comment by Undin** [comment]
I think there are two main options:
* Add checkbox into new project panel to create binary application or not. But in this case settings panel would contain this checkbox too (because it's same panel).
* Create two different items for binary and library projects. As I understand two different `RsModuleTypeBase` should be created instead of `RsModuleType` to do it.

@matklad What option do you like?
