### ISSUE TITLE
Massive Memory Leak for rustc process on 64-bit linux

### ISSUE THREAD

**Issue by kasrasadeghi** [intellij-rust/intellij-rust#1365]
I have no idea why, but I open the project and there's a rustc process in the background that makes my entire computer grind to a halt. I think it's a memory leak or something, but rustc runs about 14 GB of memory and my computer only has 16. This is on rust nightly (1.20). I'm going to try and switch to stable.

**Comment by matklad** [comment]
Hm, that's definitely not how things are supposed to work!

It is only a single `rustc` process, right? If it is the case, then most likely the root of the issue lies somewhere in `rustc`, and not in IntelliJ Rust per se. Could you share a full command with arguments for this process (`ps -aux | grep rustc` should probably show it)? 

There's only one place where we are invoking `rustc` automatically in the background, [when we call cargo check](https://github.com/intellij-rust/intellij-rust/pull/1310). You can disable automatic Cargo checking in `Settings > Languages & Frameworks > Rust`.

**Comment by kasrasadeghi** [comment]
It seems to be fine on rust 1.18. I'll go reinstall 1.20 and give the command output.

**Comment by kasrasadeghi** [comment]
The issue does not appear to be reoccuring. I'll open this up if it happens again.
