### ISSUE TITLE
Spurious: Workspace member is outside of IDE project, please open the root of the workspace.

### ISSUE THREAD

**Issue by nathanaeljones** [intellij-rust/intellij-rust#1506]
This occurs when the root of the workspace is opened, and modules (for each crate) have been loaded in to the workspace root project. 

Example: https://github.com/imazen/imageflow/commit/0114fa8319779434736911b31da6f453eb3a9142

**Comment by matklad** [comment]
Question: why do you need to create a separate IDEA module for each of the crates? My understanding is that they are a member of a single workspace, so it should be sufficient to import only the root of the workspace in the IDE. 

Modules were required a while back, when Cargo didn't support workspaces, but now they should be unnecessary, and we are trying to get rid of them slowly, because they are IDEA specific thing, and are not really available in CLion.

**Comment by matklad** [comment]
The single layout will look like this: https://github.com/matklad/imageflow/commit/c6d38969f9104fe590f12897ec057a723495176. If it'll work for you, I'll send a PR after the next plugin release.

Thanks for sharing the link to the repo! It's nice to see IntelliJ being used for cool projects, and it helped to track down one nasty bug which would have slipped into production otherwise!

**Comment by nathanaeljones** [comment]
I usually run tests on one crate at a time when developing - and run configurations seem to require a crate module. Maybe not? I'd also assumed that refactoring needed them.

**Comment by matklad** [comment]
@nathanaeljones yeah, there's `--package` argument on Cargo's side to select which workspace member to use. I've send the PR!

So I am closing this issue because the warning is not actually spurious: in the current implementation, IDEA modules should correspond to Cargo workspaces. We probably will support several workspaces in a single module some time in the future, but I don't think it's important to perfectly support opening a single workspace member, without opening the whole workspace.

**Comment by matklad** [comment]
@nathanaeljones looks like you use run configurations a lot, so if you have any feedback about them, please add them to this issue: https://github.com/intellij-rust/intellij-rust/issues/1632.
