### ISSUE TITLE
Custom environment variables for running cargo

### ISSUE THREAD

**Issue by overminder** [intellij-rust/intellij-rust#1569]
First I'd like to thank you for creating this! It really improves my productivity when developing large Rust projects.

There's one feature that I'd like to have: allow users to set per-project custom environmental variables. Our use case is that some FFI bindings ([pkg-config](https://github.com/alexcrichton/pkg-config-rs/blob/bd1d464/src/lib.rs#L85) / [openssl](https://github.com/sfackler/rust-openssl/blob/43cacf0/openssl-sys/build.rs#L41)) tend to use user-supplied environment variables to configure the build process. We couldn't simply set those environment variables globally as we might have multiple projects with different build configurations.

I can think of two ways to implement this:

1. We could use a project-local property file to define the environment variables (like [gradle.properties](https://docs.gradle.org/3.3/userguide/build_environment.html) etc). intellij-rust would read from it and call cargo with the updated environment. The downside is that cargo itself knows nothing about this file so it doesn't work when cargo is called directly without using intellij-rust.

2. We could add a way to override the cargo executable path in intellij-rust. Then the user can override cargo with a wrapper script that calls cargo with the desired environment variables. The downside is that the wrapper script might not be cross-platform..

I personally like the second way as it works both with and without intellij-rust.

Currently as a workaround I just change the `toolchainHomeDirectory` property in `.idea/misc.xml` to point to directory with a custom cargo wrapper. For now it works fine but it would be better if this feature could be supported officially.

**Comment by matklad** [comment]
Glad that the plugin helps you to be more productive! 

Regarding the issue itself, I think it should be solved lower in the stack then in IDE. As you've correctly said, the IDE solution will work only in the IDE.

>Currently as a workaround I just change the toolchainHomeDirectory property in .idea/misc.xml to point to directory with a custom cargo wrapper. For now it works fine but it would be better if this feature could be supported officially.

It is 100% supported :) You can change path to the toolchain per project at `Settings > Languages & Frameworks > Rust`. Or does this not work for your use case for some reason? 

I have a similar problem when developing Rust projects, because on nixos, *nothing* works without proper tweaks to the environemt. The way I solve it is that I have a bash script that sets up necessary project env. When working on the project, I execute the script to make cargo from command line work, and then I launch IDEA from that same shell. That way, IDEA inherits env vars and passes them through to Cargo.

**Comment by overminder** [comment]
Ah, there it is. From the plugin source there seems to be a UI for setting the toolchain path but previously I couldn't find it... Yes, this solution is sufficient for my need. Thanks!

On the other hand, [cargo might be planning to support passing environment variables from downstream to upstream](https://github.com/rust-lang/cargo/issues/4121).
