### ISSUE TITLE
Always add .idea folder and .iml file to .gitignore

### ISSUE THREAD

**Issue by sgift** [intellij-rust/intellij-rust#1570]
Currently, the IntelliJ project folder and file are not added to .gitignore. I think it would be a good idea to add them by default, as it's rather untypical to store IDE data in a repository.

**Comment by matklad** [comment]
It's a rather complicated question... Editor specific .gitignores usually go to user's [global .gitignore]( https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) or to .git/info/exclude, because different people use different editors. That said, some parts of `.idea` are *indented* to be committed to the repository: stuff that people usually share are code style, run configurations and dictionaries. 

Finally, we don't control `.gitignore` files, because they are created by Cargo, and it was decided that Cargo should not add editor-specific stuff to gitignore either: https://github.com/rust-lang/cargo/pull/4097

**Comment by grossws** [comment]
I usually add `.idea/` and `*.iml` to global gitignore to avoid project's `.gitignore` pollution. Also, `.ignore` plugin for IDEA is often used and it manages gitignore for project. 

IMHO, gitignore management is out of scope for this plugin and implementation of such functionality may conflict with dedicated `.ignore` plugin.

**Comment by sgift** [comment]
Using the global .gitignore instead sounds like a good idea. Would probably be too much work for too little gain to make it an option. Thanks for the quick responses.

**Comment by alihesari** [comment]
git rm --cached -r .idea

**Comment by Gaurav6982** [comment]
Should .idea be deleted or not?

**Comment by Undin** [comment]
@Gaurav6982 if you want to share project settings then you should add .idea directory to your vcs except some files with user data. See https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems for more details
