### ISSUE TITLE
Tooling only partially works with the Rust compiler

### ISSUE THREAD

**Issue by MaikKlein** [intellij-rust/intellij-rust#1660]
I opened the Rust compiler and I was surprised that it even partially worked at all.
![](https://i.imgur.com/oL7uIEC.png)

You can see on the left side that pub `use self::..` seems to work fine, but it fails to resolve `use util::node_map::NodeMap`. But I am able to find `NodeMap` with "Find class". 

![](https://i.imgur.com/FCfHHHQ.png)

**Comment by matklad** [comment]
Please note that Cargo.toml must be in the root of the project. So, to work with compiler, one should open the src subdirectory in IDEA, and not the root of the repository.

**Comment by MaikKlein** [comment]
@matklad That was actually the first thing that I tried

![](https://i.imgur.com/H8xJ8nY.png)

Does it work for you?

**Comment by MaikKlein** [comment]
Sorry it works now, I had to run  `x.py` first, I thought I already did because it worked fine with the emacs plugin.

**Comment by matklad** [comment]
It does work for me. Looks like you have zero external libraries, which means that we were unable to get the necessary information from Cargo. In similar cases, you can run **Refresh Cargo Project** action to request an update explicitly. 

Gosh, I really need to write a Cargo toolbar because it would be a nice place to say if everything is working properly, or if something is wrong. A lot people stumble on this, and this is totally undestandable.
