### ISSUE TITLE
Plugin doesn't seem to do anything at all on IDEA 2017.2.1

### ISSUE THREAD

**Issue by sp-1234** [intellij-rust/intellij-rust#1673]
I've installed the plugin and restarted IDEA.
Then I've imported a hello-world rust project. There was no mention of Rust anywhere in the process.

Then I opened the .rs file. This is all I got:
<img width="1184" alt="1" src="https://user-images.githubusercontent.com/19407943/29876047-6322cb52-8da4-11e7-90b9-42f1adc68740.png">

Also, there's no mention of rust anywhere in settings.

Plugins window:
<img width="1078" alt="2" src="https://user-images.githubusercontent.com/19407943/29876082-78da18a6-8da4-11e7-940f-496bafc01932.png">

Is IDEA 2017.2.1 officially supported?

**Comment by matklad** [comment]
>Is IDEA 2017.2.1 officially supported?

It is, yes. I haven't tested 2017.2.1 specifically, but it does work with plain 2017.2 and with 2017.2.2.

It seems like the plugin is disabled for some reason, although it clearly is enabled in the settings. Is there anything strange in the logs perhaps (`~/IdeaIC2017.2/system/log/`).

I am really puzzled with what might be the issue here, so the only advice I can give is to try do reinstall plugin again :(

**Comment by sp-1234** [comment]
There's no such directory `~/IdeaIC2017.2` and even none similar.
I'll try updating IDEA to ….2.2 and try again.

**Comment by mkaput** [comment]
it should be `~/.IdeaIC2017.2` (it's hidden folder), or it's located elsewhere on macOS

**Comment by matklad** [comment]
Hm, yeah, looks like it's not in `~` on macs. Here are proper documentation for getting logs: https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files.

**Comment by sp-1234** [comment]
Thank you for replies. It seems to work fine now after updating IDEA.

I also checked the log for the time period of the problem, and I think there's nothing related to the problem but I can send it to you privately if you want.
