### ISSUE TITLE
Cargo lacks 'metadata' subcommand necessary to properly import project.

### ISSUE THREAD

**Issue by vrcod** [intellij-rust/intellij-rust#169]
I'm trying to use this plugin with IDEA 15 and this is an error popup I'm getting when trying to import an existing project:

Cargo lacks 'metadata' subcommand necessary to properly import project.
Please, install it with 'cargo install metadata' to proceed!

However, ```cargo install metadata``` produces an error ```could not find `metadata` in `registry https://github.com/rust-lang/crates.io-index```

Any clues?

In any case - this is a welcome plugin for Intellij IDEA. Thanks.

**Comment by matklad** [comment]
Yes, cargo-metadata is uber unstable now, we hope to include it with cargo by default. It is not on crates-io because it depends on the yet unreleased version of cargo.

If you want just to use the plugin, you should just open the project folder, without importing `Cargo.toml`. We don't use metadata much at the moment :)

If you want to hack the plugin, you can install cargo-metadata from https://github.com/intellij-rust/cargo-metadata

**Comment by vrcod** [comment]
Thanks, will try that.
