### ISSUE TITLE
Labels meaning

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#1757]
I've noticed that some issues have a new label **E-mentor**.
So now we have at least 6 labels: **up for grab**, **E-easy**, **E-medium**, **E-hard**, **E-unknown** and **E-mentor**.
Although **up for grab** label is obvious other labels are not so easy to understand.
Personally, I know that **E**-prefixed labels mean level of **experience** necessary to fix the issue, but I've read corresponding part of rust's CONTRIBUTING.md (But I haven't still understood why **mentor** tag has **E** prefix:)) )

So it would be great to have some paragraph(s) in [CONTRIBUTING.md](https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md) with explanation of labels meaning.

**Comment by vlad20012** [comment]
Yes, I'm going to write a few lines about it =)

E-mentor is something [widely known](https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AE-mentor) in rust community. It means that someone know exactly how to fix the issue and most likely wrote some instructions. It is **E** label because it shows that contributor shouldn't have a large experience in this matter (and shouldn't perform a lot of research) because just there are instructions provided.

It would be nice if all **up for grab** issues had a mentoring instructions, but practically it is not so (and often, if you know how to fix the issue, it's simpler to just fix it than write an instructions, as for me)

**Comment by sanmai-NL** [comment]
For me the labels are clear, but I support the idea that anything arbitrary within a project such as labels should be documented somewhere within the project (even by means of referring to a label standard).
