### ISSUE TITLE
Extract variable mangles code for tuple arguments

### ISSUE THREAD

**Issue by FauxFaux** [intellij-rust/intellij-rust#1785]
Given code like:
```rust
fn foo((a, b): (u32, u32)) {
    println!("{} {}", a, b);
}
fn bar() -> (u32, u32) {
    (1, 2)
}
fn main() {
    foo(bar());
}
```

...attempting to run the "extract local variable" action on the call to `bar()` in `main()` gives:

```rust
fn main() {
    let b
    foo(b);
}
```

It's deleted the call to `bar()`, and resulted in invalid syntax. Other options in the dropdown are for naming `b` are `b)` and `a, b)`. I expect the problem is to do with parsing an unpacking expression in a method signature. The "type hinting" shows the parameter name correctly, so I believe it's being parsed okay.

![image](https://user-images.githubusercontent.com/328180/30857072-5757e5f0-a2b2-11e7-81b6-cdef7b81457e.png)

I was expecting the extraction to result in:

```rust
let (a, b) = bar();
foo((a, b));
```

..but would also be okay with:

```rust
let bar = bar();
foo(bar);
```

...which are equivalent, as far as I'm aware.

**Comment by vlad20012** [comment]
The actual code is located [here](https://github.com/intellij-rust/intellij-rust/blob/fcb26cbdbd7ae7a654597413b52862f3e115f58b/src/main/kotlin/org/rust/lang/refactoring/RsLocalVariableHandler.kt#L80) (and the tests [here](https://github.com/intellij-rust/intellij-rust/blob/fcb26cbdbd7ae7a654597413b52862f3e115f58b/src/test/kotlin/org/rust/lang/refactoring/RsLocalVariableHandlerTest.kt))

There is needed to write a test and then investigate where is something went wrong.

**Comment by GuillaumeEveillard** [comment]
Hello,

I made a first commit which corrects the issue described in the first message. I also added a unit test.

However, I found another issue when doing more tests:

```
fn foo((a, b): (u32, u32)) {
    println!("{} {}", a, b);
}
fn bar() -> (u32, u32) {
    (1, 2)
}
fn main() {
   let bar = 10;
   foo(bar());
}
```

In this case, my fix does not work. The problem is that the type of the extracted expression is unknown (I don't know why it does not find the type) instead of tuple, so I'm not able to detect that we are in the "tuple special case".

I will try to dig a little more, but if I don't find the root cause I will maybe propose my actual fix and insert a new issue.

Does someone have an advise?

Guillaume

**Comment by matklad** [comment]
>I made a first commit which corrects the issue described in the first message. I also added a unit test.

> However, I found another issue when doing more tests:

I think it makes sense to send a PR with this fix and tests right now, and handle additional issues separately.
