### ISSUE TITLE
TY: Introduce array of unknown size

### ISSUE THREAD

**Issue by chabapok** [intellij-rust/intellij-rust#1790]
This code is ok, but syntax checker marks array as wrong

```rust
const COUNT: usize = 2;

struct Foo {
    v: [usize; COUNT]
}

fn bar(f: Foo) {}

fn main() {
    bar(Foo{
        v:[10, 20] // E308, expected [usize], found [usize; 2]
    });
}
```

[Mentoring instructions can be found in this comment](https://github.com/intellij-rust/intellij-rust/issues/1790#issuecomment-333066164)

**Comment by kumbayo** [comment]
RsArrayType.calculateArraySize() is currently only dealing with literal expressions resulting in an unknown size.
Since we currently have no concept of unknown/unresolved array sizes
TypeInference.inferArrayType() falls back to TySlice instead which is more wrong :-(

**Comment by vlad20012** [comment]
As we can write `let a: [u8; 5+5];` it is a very hard task. We really should think about unknown array size, I guess.

**Comment by alexander-irbis** [comment]
Perhaps here you need to temporarily enter a new entity - an ignored size.

**Comment by vlad20012** [comment]
Mm, really it's even not temporary. I.e. some path (to constant) may be not resolved, so our array size is unknown too.

**Comment by vlad20012** [comment]
Ok, we can just turn `size` into `Int?` and allow null-sized array to be unified with array of any size. And it become a simple task.

**Comment by vlad20012** [comment]
How to achieve it:
1. make turn type of [TyArray](https://github.com/intellij-rust/intellij-rust/blob/d4a54c17c1dfffe7c7d2cbb8424b0eb126306a20/src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt#L13).size into `Int?`.
2. Fix [this line](https://github.com/intellij-rust/intellij-rust/blob/d4a54c17c1dfffe7c7d2cbb8424b0eb126306a20/src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt#L878) to make `size` `null` instead of returning an array
3. make [this condition](https://github.com/intellij-rust/intellij-rust/blob/d4a54c17c1dfffe7c7d2cbb8424b0eb126306a20/src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt#L161) more complex to allow unification of 2 arrays if at least one of them have `null` size
4. Improve display format: print something like `[u8; <unknown>]` for unknown size. (The code is located [here](https://github.com/intellij-rust/intellij-rust/blob/d4a54c17c1dfffe7c7d2cbb8424b0eb126306a20/src/main/kotlin/org/rust/ide/presentation/Ty.kt#L45))
5. Write some tests [here](https://github.com/intellij-rust/intellij-rust/blob/d4a54c17c1dfffe7c7d2cbb8424b0eb126306a20/src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt).

**Comment by Undin** [comment]
If @kumbayo doesn't mind I'll grab it

**Comment by vlad20012** [comment]
@Undin Looking at your skills, you could work on auto-import or a something like it =D

**Comment by Undin** [comment]
:blush:
Unfortunately, now I don't have a lot of time to grab large task, but I want to help too.
Btw, I implemented previous version of array size determination, so I can extend my own code:)

**Comment by mkaput** [comment]
> Unfortunately, now I don't have a lot of time to grab large task, but I want to help too.

I know that feel bro

**Comment by kumbayo** [comment]
@Undin yeah you can grab it.

**Comment by vlad20012** [comment]
Btw, we should probably use `Long` instead of `Int` for array size. Just because if `usize` is even 32-bit it's still more than java's `int` and our type inference will fail on 3Gb arrays =D
