### ISSUE TITLE
Feature request: explore macro expansion

### ISSUE THREAD

**Issue by HighCommander4** [intellij-rust/intellij-rust#1851]
It would be great to have a feature where the IDE let you "preview" the expansion of a macro invocation by e.g. showing it in a hover window in response to a command / keyboard shortcut.

Eclipse CDT has a similar features for C/C++ macros.

**Comment by prasannavl** [comment]
There's quite a lot of auto-completion missing due to this. Ranges from crates like winapi and the whole set like kernel32-sys, user32-sys all the way to even simpler standard libraries that use macros for ops like `wrapping_add`, `wrapping_sub`, `saturating_xxx`, `checked_xxx`. 

All of these depend on macro, and I'd expect more and more like these to be used, which will have no auto-completion unless macro-expansion works. :(

**Comment by prasannavl** [comment]
@matklad - I wonder how much mileage using `cargo expand` (internally using `cargo rustc -- --pretty=expanded`) get you. It does expand macros. Could this be used to add info to the intellij ast parser?

**Comment by Undin** [comment]
It works for declarative macros since #2720
See `Show expanded macro` and `Show recursively expanded macro` actions and the corresponding intensions

**Comment by HighCommander4** [comment]
I updated to the latest version of intellij-rust, and while I see the new actions, all they show is the original macro invocation.

For example, in:

```
fn main() {
    println!("Hello, world!");
}
```
"Show expanded macro" and "Show recursively expanded macro" on the `println!` both just show `println!("Hello, world!");`.

**Comment by HighCommander4** [comment]
Thanks, I can confirm that it works for `error_chain!`.

A couple of questions:

1. Is there a way to step through the expansion? The actions allow me to see the first level expansion and the final result, but what about e.g. the second level of expansion?
2. Why does it not work for builtin macros like `println!`? "Go to Declaration" works for `println`, and the definition uses `macro_rules!` just like the definition of `error_chain!`.
