### ISSUE TITLE
Completion of function in "use" declaration could insert semicolon

### ISSUE THREAD

**Issue by HighCommander4** [intellij-rust/intellij-rust#1856]
When performing completion of a function in a "use" declaration, we know we'll want a semicolon afterwards, so the completion might as well insert it.

**Comment by matklad** [comment]
The relevant code is here: https://github.com/intellij-rust/intellij-rust/blob/4e3e2baae57330f47c7bda1aa41c378caa4dea12/src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt#L46

**Comment by mhaessig** [comment]
I'd like to give this a try.

**Comment by mhaessig** [comment]
I have trouble detecting if there is already a semicolon.
When calling `val parent = element.parent!!` within the if at  https://github.com/intellij-rust/intellij-rust/blob/4e3e2baae57330f47c7bda1aa41c378caa4dea12/src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt#L51 I get a PSIElement of type `PSIElement(mod)` and I don't understand why, because from my (limited) understanding `parent` should really be of type `PSIElement(use)`, so that `ìf (element.nextSibling!! == null || element.nextSibling.elementType != RsElementTypes.SEMICOLON){context.addSuffix(")}` should only append a semicolon if there is none before.

Am I missing something?

**Comment by matklad** [comment]
In this function, `element` is the element you are trying to complete (for example, a struct from another file), and not the element at caret. 

See this snippet for an example of how to get context at the completion point:

https://github.com/intellij-rust/intellij-rust/blob/4e3e2baae57330f47c7bda1aa41c378caa4dea12/src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt#L32-L37

**Comment by mhaessig** [comment]
Oh, I see. Thanks for your help.
