### ISSUE TITLE
Don't render `<unknown>` types in hints

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1874]
![image](https://user-images.githubusercontent.com/1711539/31637076-b9ae1430-b2d5-11e7-8031-98b9ece9879a.png)

These `<unknowns>` do not add much value...

cc @farodin91

**Comment by alexander-irbis** [comment]
Maybe `?` or `<?>` as compact replacement for `<unknown>`?
Sometimes it would be useful to distinguish whether IDE failed to determine a type or work is still in progress.

**Comment by mkaput** [comment]
`_`

**Comment by farodin91** [comment]
I do not like `_` much because there can be a difference between rust is unable to infer, and IntelliJ-rust is unable to infer. Besides, we can start with this.

**Comment by farodin91** [comment]
Also, we currently add `_`, when don't want to show the complete type, for example, to large.

**Comment by vlad20012** [comment]
Let's resume discussion about <?> instead of <unknown>

**Comment by alexander-irbis** [comment]
My opinion: "unknown" is not the worst part of the problem now.
![screenshot_20181014_132845](https://user-images.githubusercontent.com/1448323/46915513-56f92980-cfb5-11e8-8434-07360ff07a4f.png)
:smile: 

Since we are not limited to the rust syntax to display an error, alternative characters can be used that will never be confused with ordinary code.
… − — ⋅ ◊ • ¡ ¿ etc

**Comment by vlad20012** [comment]
@alexander-irbis The worst part of the problem is a bug that leads to full rendering of closure return types. It should be fixed with #2940

**Comment by vlad20012** [comment]
I think a simple `?` is ok
