### ISSUE TITLE
Add underline to &mut self?

### ISSUE THREAD

**Issue by gilescope** [intellij-rust/intellij-rust#1950]
Add underline under &mut self to be consistent with display of other mut variables?

**Comment by matklad** [comment]
The relevant code is here: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt#L101

**Comment by guanqun** [comment]
Should we create a new color `SELF_MUT_PARAMETER`?

**Comment by matklad** [comment]
Hm, no, I think `self` should always use keyword. I think it should be possible to add decoration to existing keyword color?

**Comment by mfarrugi** [comment]
Right now `self` is configurable separately from keyword anyway.

Glancing through the TextAttributeKey api it doesn't look like it's easy to have orthogonal styling (eg. mut + self = underline + keyword), so I don't see any problem with adding a new color for this special case.

(Would also propose renaming `RsColor` to `RsStyle` or something more like TextAttributeKey, since that kind of obviates the issue)

**Comment by mfarrugi** [comment]
Would also like to clarify the issue title should be something more like 'make &mut self highlighting configurable' since not everyone wants underlines :)
