### ISSUE TITLE
Cargo project update failed:download failed: Failed to find stdlib in sysroot

### ISSUE THREAD

**Issue by limira** [intellij-rust/intellij-rust#2107]
My system info:
- Fedora 27
- IntelliJ IDEA Community 2017.3
- Rust plugin Version: 0.2.0.2081
- Default Rust channel: beta

After logging into Fedora. I open IDEA, it complains:

    `Cargo project update failed:download failed: Failed to find stdlib in sysroot`.

**But if I close IDEA and open it again, there is no error any more!!!**

More info: 
I found this [issue](https://github.com/intellij-rust/intellij-rust/issues/1102), but my folder do not contains any non-ascii characters.
I also run `rustc --print sysroot` confirm that 

    FileUtil.join(sysroot, "lib/rustlib/src/rust/src"))

is correct (the folder exists)

**Comment by mati865** [comment]
The same on Ubuntu 17.10, `$(rustc --print sysroot)/lib/rustlib/src/rust/src` exists and is readable/writable.
Looks like timeout issue: 
* cold start `rustc --print sysroot`: `0,08s user 0,04s system 2% cpu 4,190 total`
* warm start `rustc --print sysroot`: `0,07s user 0,01s system 97% cpu 0,084 total`
Use [this](https://wiki.openoffice.org/wiki/Cold-start-simulator#Flushing_Linux_Caches) to reproduce cold start without rebooting.

**Comment by nonsensecreativity** [comment]
I also got this issue on:
* Windows 10 Pro x64
* Intellij 2017.3.1
* Intellij-Rust v0.2.0.2083

This issue only happening to me when meet one of these two conditions:
- When opening Intellij project the last file is not part of **src** eq: other file from library
OR
- When opening Intellij project the last file is part of **src** but not a **.rs** file eq: the last opened file is .sql, .js, etc

Workaround:
Point to main.rs, then close Intellij and reopen it

**Comment by Cryptor1** [comment]
The issue is still present for me.

- _OS_: Ubuntu 16.04 LTS
- _IntelliJ_: IntelliJ IDEA 2018.1.2 (Community Edition)
Build #IC-181.4668.68, built on April 24, 2018
JRE: 1.8.0_152-release-1136-b29 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-122-generic
- _Rust plugin_: Version: 0.2.0.2094-181
- _Rustup_: rustup 1.11.0 (e751ff9f8 2018-02-13)

**Comment by IvSergei65** [comment]
https://github.com/intellij-rust/intellij-rust/issues/2068

We pass through environment variables to processes spawned from IDE, like Cargo and rustup. So this probably means that RUSTUP_HOME is not set for the IDE process, because it is launched by DE and not from the shell.

To verify my hypothesis, could you launch IDE from bash shell as well and check if it works?

If it does work, it probably means that RUSTUP_HOME should be set earlier then in .basrc, which is sadly per-DM and per-distribution specifig. Something like .xprofile might work.

**Comment by MCOfficer** [comment]
For testing, you can also leverage `rustup run` to force the correct environment:
```bash
$ rustup run stable idea # you can use any toolchain instead of "stable"
```

**Comment by BCarlaYap** [comment]
It fixed mine when I updated the plugin.

- Ubuntu 20.04.1 LTS
- IntelliJ IDEA 2020.2.3 (Community Edition)
Build #IC-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-48-generic
- Rust plugin: 0.3.132.3395-202
- Rustup: 1.22.1 (b01adbbc3 2020-07-08)
- Rustc: 1.47.0-nightly (f44c6e4e2 2020-08-24)

**Comment by zingi** [comment]
Like for @BCarlaYap an update of the plugin also fixed it for me.

However to get the latest version of the plugin I had to upgrade my IntelliJ Version from 2019 => 2020.

**Comment by samirm** [comment]
Running rustup again fixed it for me. (https://rustup.rs)
