### ISSUE TITLE
Auto import doesn't work

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#2157]
I just updated this plugin to version `0.2.0.2083` and saw in the changelog

> Initial support of auto import :tada: Now it is implemented as intention so you can try it via Alt+Enter at unresolved reference

and that sounded super awesome! But after updating and restarting IntelliJ IDEA (see below for meta stuff), I could not see any intention for the following code (simple, single-crate project) even though the "Import" intention is enabled:

```rust
fn simple() {
    let mut map = HashMap::new();
}
```

My Rust version is

```
rustc 1.24.0-nightly (7eb64b86c 2017-12-20)
```

and IDEA -> Help -> About gives me

```
IntelliJ IDEA 2017.3.1 (Community Edition)
Build #IC-173.3942.27, built on December 11, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-104-generic
```

**Comment by Undin** [comment]
@torkleyy the main restriction of current implementation - it doest's support reexports yet.
It leads to two different unpleasant cases:
* If item is in private module and available only via some reexport, auto import doesn't work for this item at all
* If item is in public module but it is supposed to be used via some reexport, you can import it but from some weird place

Your case belongs to the first group: `HashMap` is in private `std::collection::hash` module and it's available via reexport in `std::collection`.

We know about these problems and it is one of the main reason why auto import is intention instead of inspection with quick fix - we don't want to force users to use it while work on this feature is in progress.

**Comment by torkleyy** [comment]
Ah okay thanks for the explanation! Feel free to close it either now or when this gets fixed.

**Comment by dobkeratops** [comment]
Understanding that accurate autocompletion is difficult (macros, crates, implied traits..).. it is very hit and miss in my experience:
#2171

I would like a stopgap option to *over-estimate* the dot-autocomplete menu: imagine doing ```grep fn.*(.*self``` and populating the "." autocomplete menu with *everything* this finds (i.e. *all* methods): it will still jog your memory, and in generic code might be useful in find the right traits (i.e. find the function first) ; 


This might have to be an opt-in since I can see not everyone would like it, but you could always give the best of both worlds by sorting the menu and prioritizing/highlighting the completions that the IDE currently knows are relevant to the situation. How about if there was a permanent '<all methods>'option in the menu (where at present the 'empty menu' shows some ability to paste various syntactic forms.. I dont find typing assist useful; my reason for wanting auto-complete is the in-place navigation assist, which is worth it's weight in gold..)

in my own libraries I have taken to simplistic name prefixing ('vector maths methods prefixed with v') and stuck with raw glFoo style bindings to C libraries, precisely to give me an easier time when working with WIP-tools.

**Comment by torkleyy** [comment]
Actually, this issue should be called "auto import doesn't work".
