### ISSUE TITLE
"Invalid standard library" when setting standard library path

### ISSUE THREAD

**Issue by LinAGKar** [intellij-rust/intellij-rust#2211]
I'm trying to set the standard library path, but no matter what I set it to, it says "Invalid standard library". I'm on OpenSUSE, and I have rust-std installed from the main repo. I've tried setting the path to `/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib`, and the paths above that up to `/usr/lib`. I've also tried downloading the rust tarball and setting the path to `rust-1.23.0-x86_64-unknown-linux-gnu/rust-std-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib` all the way up to  `rust-1.23.0-x86_64-unknown-linux-gnu` in the extracted contents, but no matter what I set it to I get the same error.

**Comment by xftroxgpx** [comment]
You're lucky you get an error message :)
For me, no matter what dir I select, not even the Apply button gets re-enabled.
There's a "Download via rustup" link which doesn't download it even if I click it (it just spends 30 sec pretending to, then it closes the download window)
Toolchain location is: /home/xftroxgpx/.cargo/bin  which is why that link appears.

I'm starting to wonder if using jdk8 is the culprit, maybe I should be using jdk7...
(just like jdk9 didn't work)

Plugin Version: 0.2.0.3091

**Comment by xftroxgpx** [comment]
hey I fixed mine,
all I had to do is select a non `.cargo/bin` toolchain, and it let me select the `Standard library` dir. I think the `...` button should also be disabled when `Download via rustup` is shown! (my guess is the path field is already, since it's not white - see screenshot in my prev. comment)

For OP, the `Standard library` path must be to the rustc sources(ie. the `src` dir of rustc repo), not the build library; now that `invalid standard library:` error is gone.
![2untitled](https://user-images.githubusercontent.com/26243389/35180786-14d75d2c-fdb7-11e7-9362-0053b3da222a.png)

**Comment by LinAGKar** [comment]
Thanks, installing the rust-src package and pointing it to the contents of that works.

**Comment by sbutler2901** [comment]
On Arch Linux, I had to run `rustup component add rust-src` to install the stdlib and set the toolchain and stdlib as seen below. Note: the Toolchain Version should display the version when the Toolchain Location is set correctly (not in image because of `<USER_HOME>`

![webstorm-rust-config](https://user-images.githubusercontent.com/7417858/52181556-2dad1500-27c1-11e9-8e87-91660be7e8ba.png)

**Comment by AbrarNitk** [comment]
Toolchain location /Users/<USER_HOME>/.rustup/toolchains/1.31.0-x86_64-apple-darwin/bin

**Comment by rdesgroppes** [comment]
> For MAC PyCharm
> Toolchain location /Users//.rustup/toolchains/1.31.0-x86_64-apple-darwin/bin
> When will you toolchain location it will auto detect the Toolchain version (1.31.0 in my case)
> For standard library run `rustup add component rust-src` and give path of rust src
> /Users//.rustup/toolchains/1.31.0-x86_64-apple-darwin/lib/rustlib/src/rust/src
> 
> Yay! It's works for me.
> <img alt="screenshot 2019-02-07 at 10 18 12 am" width="771" src="https://user-images.githubusercontent.com/17473503/52391128-c42f4e00-2ac1-11e9-8713-ad9c92eb1e18.png">

Worked for me with `rustup component add rust-src`
