### ISSUE TITLE
containingFile.virtualFile must not be null

### ISSUE THREAD

**Issue by DerGroncki** [intellij-rust/intellij-rust#237]
Hi,

I am getting the following error if I enter new code in the edtor:
>"containingFile.virtualFile must not be null"

Maybe the configuration of the editor is not correct.

I am using IntelliJ IDEA 15.0.3 on windows 10 pro.

Thanks for helping.

Michael

**Comment by matklad** [comment]
Thanks for the report! I've reproduced the issue. It is caused by https://github.com/intellij-rust/intellij-rust/commit/5656ed00a1079821f84550acffef1d5e4bb57338. 

FYI: you can get a stack trace from the exception in IDEA, if you click that red exclamation mark in the lower right corner and select Details tab

**Comment by matklad** [comment]
The immediate work around should be to mark a directory with rust files as source root
