### ISSUE TITLE
RustStructureViewTest fails

### ISSUE THREAD

**Issue by jajakobyly** [intellij-rust/intellij-rust#240]
Hi!

As title says, all tests in org.rust.ide.structure.RustStructureViewTest fail on my machine. It's not critical (all tests pass on travis), but it's cumbersome.

Part of the log (for the rest of the errors the problem is the same: last `]` isn't preceded by a new line):
```
expected:<-enums.rs[
 -enums
  -CompileMode
   Test
   Build
   Bench
   Doc
  -CompileFilter
   Everything
   Only
]
> but was:<-enums.rs[
 -enums
  -CompileMode
   Test
   Build
   Bench
   Doc
  -CompileFilter
   Everything
   Only]
> <Click to see difference>
```

My spec: Windows 10 x64, JDK8

**Comment by matklad** [comment]
Weird, we have CI set up on windows: https://teamcity.jetbrains.com/viewType.html?buildTypeId=IntellijIdeaPlugins_Rust_Tests&guest=1 and there are no problems there...

I have two hypothesis:
* editorconfig somehow messed up `src/test/resources/org/rust/ide/structure/fixtures/enums.txt`. Are you sure that this file is not modified?
* line separators are different due to different git settings. Could you try

```Kotlin
        val text = FileUtil.loadFile(File(testDataPath + "/" + fileName.replace(".rs", ".txt")), "UTF-8",
            /* convertLineSeparators = */ true)
```

in `RustStructureViewTest`?

**Comment by jajakobyly** [comment]
Yeah, this line of code has fixed it. Git may be the cause. I have `core.autocrlf=true`.
