### ISSUE TITLE
Intellij-rust does not show some methods in completion list 

### ISSUE THREAD

**Issue by ajjaic** [intellij-rust/intellij-rust#2425]
intellij-rust - Version: 0.2.0.2090-173
intellij IDEA community - IC-173.4674.33
OS - ubuntu 17.10
rust stable - 1.25.0

Here is the sample program I'm testing it with,

```rust
fn main() {
    let s: String = "33".to_owned();
    let num: Result<usize, <usize as FromStr>::Err> = s.parse().un // notice this line
```

In the 2nd line, when I do `s.parse().un`, intellij-rust opens a completion list with all the methods for a `Result` enum. `s.parse()` returns a `Result` by the way.

In the completion list that opens up at that point, a few methods are missing. Specifically the following methods are missing in that completion list,

- unwrap
- expect
- unwrap_err
- expect_err
- unwrap_or_default

Is this a bug in intellij-rust or am I doing something incorrectly? Please advise.

**Note**: I have not filed an issue on intellij-rust before. If this is not relevant enough to be posted as an issue here, please let me know. I shall remove it. Thanks.

**Comment by vlad20012** [comment]
1. Error type is not inferred:
![image](https://user-images.githubusercontent.com/3221931/38175916-691d3ff0-35ed-11e8-80d6-b4a0bbbe7f09.png)
2. We can't infer the error type in this place because `FromStr` trait is implemented for primitive type via macros (we still don't support macros)
3. `unwrap` is defined in impl with the following bounds:
    `impl<T, E: fmt::Debug> Result<T, E> {`
4. As we don't know the error type, we can't be sure that it implements `fmt::Debug` so we ignoring this impl. 

2nd item will be fixed with macros support. But I think this issue is in 4th item. Why we igrnoring impls in completion for non-inferred types? This should be fixed, I think
