### ISSUE TITLE
Support for conditional breakpoints

### ISSUE THREAD

**Issue by vandenheuvel** [intellij-rust/intellij-rust#2566]
I understand that in order to create a conditional breakpoint, one should right-click an existing breakpoint. This is however not happening for me on #CL-181.5087.36 with 0.2.0.2095-181.

**Comment by ortem** [comment]
Now conditional breakpoints for Rust works in CLion.

However, they don't support complex expressions due to the lack of such support in debuggers itself. The progress of improving Rust support in LLDB is described in #4548. Rust support in GDB is described [here](https://sourceware.org/gdb/current/onlinedocs/gdb/Rust.html).
