### ISSUE TITLE
Using CLion with this plugin on NixOS with the Mozilla overlay

### ISSUE THREAD

**Issue by sondr3** [intellij-rust/intellij-rust#2575]
I'm not sure if this is the right place to ask, but I'm trying to use CLion with this plugin for developing Rust on NixOS. I'm currently installing and running Rust via the Mozilla overlay and using it with `nix-shell`, however it seems like CLion doesn't properly pick up the paths required for Rust:

```
/nix/store/r27y5rcbijpvac6zbbx63jb1grkqxld6-rust-1.26.1-2018-05-25-827013a31/bin/cargo run --color=always --package hello --bin hello
error: could not execute process `rustc -vV` (never executed)

Caused by:
  No such file or directory (os error 2)

Process finished with exit code 101
```

However if I run `nix-shell` and then launch CLion from the command line it picks up on this just fine, but it's a bit annoying and not really what I want. Is there a good way to fix this?

**Comment by pschuprikov** [comment]
Do you still have that issue? Does the issue persist if you do not use the overlay? When you say that you are *installing* Rust, do you mean installing with `nix-env` (I assume that you want to use CLion without `nix-shell`)? Are you installing both *cargo* and *rustc*? I currently use rust from `nixos-18.09` and everything seems to be working fine with a nightly plugin on IntelliJ IDEA.

**Comment by snaar** [comment]
Could it be related to paths to toolchain being stored in .idea/misc.xml? On non-nix you have something like `<option name="toolchainHomeDirectory" value="$USER_HOME$/.cargo/bin" />` show up automatically and it just works across versions.

With nix, the plugin does detect toolchainHomeDirectory correctly, but not the path to stdlib, so I always have to set manually, so I end up with this in my misc.xml:
```
<option name="explicitPathToStdlib" value="/nix/store/ri7glrk1mmybmycqcl3ixgdiyspp3l80-rust-1.28.0-2018-07-30-9634041f0/lib/rustlib/src/rust" />
<option name="toolchainHomeDirectory" value="/nix/store/ri7glrk1mmybmycqcl3ixgdiyspp3l80-rust-1.28.0-2018-07-30-9634041f0/bin" />
```
So when new version of rust is pulled in, CLion fails to find it. It's also pain to share the project between nix and non-nix installations since misc.xml seems to be "global" and not per-machine.

**Comment by snaar** [comment]
Actually I guess these are two independent issues, also potentially unrelated to the original issue:
- on nix+mozilla overlay the toolchainHomeDirectory is detected correctly, however stdlib is not and has to be set manually - filed https://github.com/intellij-rust/intellij-rust/issues/2906
- storing paths to toolchain in misc.xml is questionable, since this makes it annoying to share projects across different machines - filed https://github.com/intellij-rust/intellij-rust/issues/2907
