### ISSUE TITLE
--all-targets not always desirable

### ISSUE THREAD

**Issue by djmcgill** [intellij-rust/intellij-rust#2604]
When building a project for a specific no-std target (in my case for `thumbv6m-none-eabi`), the argument `--all-targets` casues `cargo check` to fail because there is no crate `test`. The same thing happens when I build from the command line.

Please make it configurable or even just a tickbox or something! I've had to go back to an older version of the plugin before the `--all-targets` change was introduced and am stuck there.

An example log is shown:
```
C:/Users/David/.cargo/bin/cargo.exe build --all --all-targets
   Compiling coffee-compass v0.1.0 (file:///C:/Users/David/Documents/code/coffee-compass)
error[E0463]: can't find crate for `test`
 --> src\main.rs:1:1
  |
1 | #![no_std]
  | ^ can't find crate

error: aborting due to previous error
```

**Comment by YaLTeR** [comment]
Another case where `--all-targets` is undesired: I have a stable Rust project, with a benchmark utilizing `#![feature(test)]`. `cargo check --all-targets` fails building the benchmark (because it requires nightly) and reports an error, even though I don't want to build the benchmark normally (when I do I can issue `cargo +nightly bench` manually).
