### ISSUE TITLE
Types get ellided when auto-generating trait implementations

### ISSUE THREAD

**Issue by Dylan-DPC** [intellij-rust/intellij-rust#2678]
## Environment

* **Intellij-Rust plugin version:**: 0.2.0.2099-181
* **IDE name and version:** : Phpstorm 2018.1.6
* **Operating system:** : Ubuntu 14.04

## Problem description
When implementations for a trait are autogenerated, the types of the parameters are ellided (replaced with _). 

## Steps to reproduce
```rust
trait Foo {
   fn bar(bar: Vec<String>);`
}

struct Bar;

impl Foo for Bar {
```
the IDE will throw an error on the last line, asking the user to implement the methods of the trait.

When the methods are generated (alt+click on the error), we get: 

```rust
impl Foo for Bar {
   fn bar(bar: _) {
     unimplemented()
   }
}
```
instead of: 
```rust
impl Foo for Bar {
    fn bar(bar: Vec<String>) {
      unimplemented()
   }
}
```

**Comment by Undin** [comment]
@Dylan-DPC 
Looks like that plugin doesn't know about stdlib and can't infer type of `Vec<String>`
Reasons:
* Plugin doesn't know where rust stdlib source code is located. You can check it in `Settings > Language & Frameworks > Rust`. If you don't have it, download it via rustup
<img width="851" alt="screen shot 2018-07-17 at 00 30 30" src="https://user-images.githubusercontent.com/2539310/42784824-0a924920-8959-11e8-918a-2c3f9dff8aee.png">

* Your cargo project is not attached. You can check it in cargo toolwindow.
If your project is not attached, do it via `Attach Cargo project` action in cargo toolwindow. Otherwise, try to refersh or even reattached cargo project
<img width="248" alt="screen shot 2018-07-17 at 00 47 24" src="https://user-images.githubusercontent.com/2539310/42785424-19375b08-895b-11e8-853e-8ef01ba0cca7.png">

**Comment by Kobzol** [comment]
@Undin I suppose that this was answered and can be closed? Or is there something that can be done, e.g. warn about missing `stdlib`?

**Comment by Undin** [comment]
Yep, let's close it
