### ISSUE TITLE
Automatically add closing parenthesis on meta tags

### ISSUE THREAD

**Issue by nicholastmosher** [intellij-rust/intellij-rust#2715]
Hello :)

Currently when typing a meta tag (e.g. `#[derive(Debug)]`), upon typing `#[` IntelliJ will automatically add a closing bracket to make the text into `#[^]`(where I'm using `^` to denote the cursor position. However, if you continue on to type `#[derive(^]` then IntelliJ does _not_ add a closing parenthesis, where the expected behavior (to me) would be to automatically add the closing parenthesis (as in, `#[derive(^)]`.

I'd be willing to take a stab at fixing this if somebody could point me to where bracket completions happen. Or if it's more work than it's worth to walk me through it that's fine too.

I left the environment section in just in case I'm accidentally running on old version or something and this is actually fixed already :)

## Environment

* **Intellij-Rust plugin version:** 0.2.0.2100-181
* **Rust toolchain version:** stable-x86_64-apple-darwin
* **IDE name and version:**
IntelliJ IDEA 2018.1.6 (Ultimate Edition)
Build #IU-181.5540.7, built on July 11, 2018
* **Operating system:** macOS 10.13.5

**Comment by Undin** [comment]
@nicholastmosher Hi!
As a temporary workaround, you can invoke completion while you're typing `derive` word and plugin will complete not only the word but also add parenthesis
But of course, it would be great to have parenthesis completion an in this case too.

> I'd be willing to take a stab at fixing this if somebody could point me to where bracket completions happen.

Now, we don't have code about parenthesis completion at all because in almost all cases platform completes them itself. But we have code for [angle brackes completion](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/typing/RsAngleBraceHandlers.kt). Looks like it should be a good example.

> Or if it's more work than it's worth to walk me through it that's fine too.

I don't think that it's a hard task. But some suggestions:
* We need parenthesis completion for all attributes not only for `derive`
* Don't forget to register new type handler in [plugin.xml](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/resources/META-INF/plugin.xml#L204)
* Don't forget about case when user types both `(` and `)` to avoid the following situation: you type `(`, platform adds `)` and then you type yet another `)` manually and get `())` sequence.

**Comment by nicholastmosher** [comment]
Thanks for the reply @Undin! I'll try to look at this in the next few days and see if I can work anything out :)

**Comment by Undin** [comment]
Implemented in #2768
