### ISSUE TITLE
Switch to local processing when suggestion completions for dependencies in Cargo.toml

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#2757]
I am not entirely sure about this, but looks like today, when completing dependence names and versions in Cargo.toml, IntelliJ issues requrests to the crates.io server. This unfortunately makes UX clunky: completion is slow, often freezes the UI thread, and often fails with a loud message "unable to reach crates.io".

I think it should be possible to avoid network and use local processing for completion. For example, here's how you can find available crates:

```
~/.cargo/registry/index/github.com-1ecc6299db9ec823 master*
λ git ls-tree --full-tree  -r remotes/origin/master | sed 's:.*/::' | rg ripgrep -A 10 -B 10
```

With some more legwork, it should be possible to extract version information as well.

**Comment by Jezza** [comment]
I've poked the cargo team, so we'll see if they'll give us access to the index directly.
Otherwise, we're probably going to forgo the index, and just rely on git.

## What I've discovered so far:

#### The index is stored at: "$CARGO_HOME/registry/index/github.com-1ecc6299db9ec823"

The "registry/index" is [hardcoded](https://github.com/rust-lang/cargo/blob/a6a395c6909d8417a1b48d4fd3a23e073108da62/src/cargo/util/config/mod.rs#L276).

The last part is from the [SourceId](https://github.com/rust-lang/cargo/blob/0b653a43ba49ebd67d04dc23cb4071d569a8671e/src/cargo/sources/registry/mod.rs#L387-L391).
It's siphashed, and then appended to the host url.

I doubt it's going to change anytime soon, so we can probably hardcode them ourselves.

### Querying the git repo

Querying the repo should be straight forward enough.
Annoyingly, [git ls-tree doesn't support pathspec](http://git.661346.n2.nabble.com/ls-tree-and-wildcards-td7553581.html), which means we need to dump and then parse the entire output.
It shouldn't be _too_ much of a problem, as we can cache it, but we have to be careful about that.

Once the user starts typing, we need to act based on how many characters there are, because as the [cargo index documentation states](https://github.com/rust-lang/cargo/blob/0b653a43ba49ebd67d04dc23cb4071d569a8671e/src/cargo/sources/registry/mod.rs#L90-L93): They're split based on their length.

* Only 1 character.
* Only 2 characters.
* Only 3 characters.
* The rest.

We then need to find the hashes, and then query git for all of the objects using `git show $hash`, parse all of that into json objects, then display the appropriate information to the user.

We could probably also cache the json objects themselves.

Ideally, the cargo team will give us access to the index, because otherwise we're going to have to do all of that. ;)

**Comment by matklad** [comment]
>Once the user starts typing, we need to act based on how many characters there are

My gut feeling is that we should rather load the whole index in memory (at least the set of names) beforehand, so that the actual typing does only in-memory filtering of data.

**Comment by Jezza** [comment]
Yeah, that was my idea behind:

>  [...] as we can cache it, but we have to be careful about that.

and

> We could probably also cache the json objects themselves.

>  at least the set of names

I was actually curious if we could get away with just caching the names.  
Turns out, we can.  
`git show origin/master:ti/me/time`

Which means we can simplify the query command a bit, and transfer less data.

```text
-> % git ls-tree --full-tree -rt remotes/origin/master | wc
  46088  184352 3107685
```

```text
-> % git ls-tree --name-only -rt origin/master | wc
  46088   46088  665021
```

**Comment by Jezza** [comment]
While we wait for the Cargo team to respond, I'll see if I can throw together a small prototype.

**Comment by Kobzol** [comment]
What's the current status? Do we wait for Cargo?

**Comment by Kobzol** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/6390.

**Comment by Undin** [comment]
Reopen because of https://github.com/intellij-rust/intellij-rust/issues/5908#issuecomment-744738226

**Comment by Kobzol** [comment]
This was solved by the local crate index, which is now enabled by default.
