### ISSUE TITLE
Please don't trigger Cargo.lock changes

### ISSUE THREAD

**Issue by e-oz** [intellij-rust/intellij-rust#286]
If I open Cargo.toml in IDE with Rust plugin, Cargo.lock file often getting changed after that, and I have to commit changes, because this file should not be ignored in git repo. I think plugin runs something what later brings changes to Cargo.lock - please don't do it or add some setting where it can be turned off.

**Comment by matklad** [comment]
Hm, the only two `cargo` commands which we run at the moment are `cargo metadata` and `cargo build`. Can you please run this commands manually from the command line and tell if they trigger changes in lockfile?

**Comment by matklad** [comment]
What exactly changes in the lock file? Some versions get an update, or is it some insignificant whites pace change
?

**Comment by e-oz** [comment]
I run them before each commit. `cargo build` is quite expensive command, sometime it runs 5-10 minutes, I'm not sure it's good idea to run it on each opening of Cargo.toml. And this command change at least app version in cargo.lock if it was changed in cargo.toml.

**Comment by matklad** [comment]
>I'm not sure it's good idea to run it on each opening of Cargo.toml.

We don't run `cargo build` on opening of `Cargo.toml`. `cargo build` is only executed for "make" action (Ctl+F9) and run configurations. 

We do run `cargo metadata` when you *change* `Cargo.toml` and this can trigger `Cargo.lock` update, if `cargo` finds out that `Cargo.toml` and `Cargo.lock` are inconsistent. That is, if you add a new dependency to `Cargo.toml` then it will also be added (by cargo) to the lock file. The same happens if you change `version` field.

However I think this is an expected behavior of `cargo`. It is an error to commit `Cargo.toml` with version `x` and `Cargo.lock` with version `y`. Luckily `cargo` detects such inconsistencies and fixes them automatically. 

Does this make sense?

**Comment by e-oz** [comment]
No, I'm not talking about versions of dependencies. App (module) version in
cargo.toml is not a dependency version. And I conceptually disagree with
unexpected files changes. From my point of view it looks like I just open
one file and other file getting changed - it's really annoying.
So please create some setting to disable such behavior.

**Comment by matklad** [comment]
>I just open one file

But have you changed App version in `Cargo.toml`? Then, if you at least compile your code before commit, `Cargo.lock` will be changed by `cargo` and I believe there is no option in `cargo` to disable this behavior.

What is possible is to disable auto-import on `Cargo.toml` change, which should postpone changes to `Cargo.lock` until you execute any other Cargo command. We don't have a GUI for this yet, so you  either need not to check `enable auto import` checkbox during project import, or delete `<option name="useAutoImport" value="true" />` line from `.idea/cargo.xml` file for already imported project.

**Comment by e-oz** [comment]
Sometimes app version can be changed without run of cargo build, when
changes are only in strings/sql queries. And in such cases I have to do 2
commits, 2 pushes.

Thank you for workaround.

**Comment by matklad** [comment]
I'm going to close the issue then. I'll add a GUI for controlling import options, but I can't give you an ETA: the current priority is resolve of standard library :)

**Comment by matklad** [comment]
The new Cargo settings page has `watch Cargo.toml` checkbox.
