### ISSUE TITLE
Cannot create a new project using AppCode

### ISSUE THREAD

**Issue by marcinmatczuk** [intellij-rust/intellij-rust#2866]
## Environment
* **Intellij-Rust plugin version:** 0.2.0.2105-182
* **Rust toolchain version:** 1.29.0, stable
* **IDE name and version:** AppCode 2018.2.2
* **Operating system:** macOS 10.13.6

## Problem description
It is not possible create a new project using AppCode 2018.2.2.

## Steps to reproduce
1. Launch AppCode, attempt to create new rust project using "File -> New project...".
2. Observe "Create new project" dialog.

## Expected results
1. It is possible to select rust project from "Create new project" dialog and successfully create a new project.

## Actual results
1. "Create new project" dialog has no option to create rust projects. See attached screenshot below.

<img width="368" alt="screen shot 2018-09-19 at 08 40 00" src="https://user-images.githubusercontent.com/521363/45735369-f52ce600-bbe7-11e8-9816-afd167e8912e.png">

## Additional information
AppCode is heavily based on CLion, so my assumption is that everything should be ok when creating projects. Do I miss any configuration steps for the `intellij-rust` plugin?

**Comment by Undin** [comment]
Yep, it's expected because AppCode doesn't allow to add custom project generators for plugins.
But you always can create rust project via terminal or other IntelliJ IDE (for example, IDEA or CLion) and then open it with AppCode
> AppCode is heavily based on CLion, so my assumption is that everything should be ok when creating projects.

Your assumption is incorrect. AppCode doesn't base on CLion although they have a lot of common code (but in general, all IntelliJ IDEs have a lot of common code). And even if it were true, it would not guarantee the same behavior with other plugins. In case of AppCode, it's because AppCode is only about macOS/iOS development
