### ISSUE TITLE
Automatically mark "target" directory as excluded directory. (Feature request)

### ISSUE THREAD

**Issue by crlf0710** [intellij-rust/intellij-rust#2869]
Just started using intellij-rust, works great. There's a small issue that whenever i open a new rust project, i have to manually mark the "target" directory as excluded directory. Or it will index a lot, especially when "cargo doc" generates lots of files. So i wonder if this process can be automatic, or after a user prompt to do.

By the way, there's the issue in CLion (somewhere in Youtrack of Jetbrains, i'm not sure) that the "Mark directory as" submenu won't occur unless there's a `CMakeLists.txt` file added to project and loaded by CLion. I'm not sure if there is something that should be done by the Rust plugin? Or is it purely a bug of CLion itself.

**Comment by Undin** [comment]
@crlf0710 
We've just implemented better detection of project structure including target folder so the fix will be available in the next release. Or you can try it tomorrow with nightly build (see [instruction](https://intellij-rust.github.io/install) how install it)

> By the way, there's the issue in CLion (somewhere in Youtrack of Jetbrains, i'm not sure) that the "Mark directory as" submenu won't occur unless there's a CMakeLists.txt file added to project and loaded by CLion. I'm not sure if there is something that should be done by the Rust plugin? Or is it purely a bug of CLion itself.

Looks like that it should be fixed in CLion because `Mark` action is unavailable for other project types too

**Comment by crlf0710** [comment]
That's wonderful, thanks! I'll wait for the next release, since it's not urgent.
