### ISSUE TITLE
Generate an intellij module instead of project

### ISSUE THREAD

**Issue by mfarrugi** [intellij-rust/intellij-rust#295]
Currently you cannot import a rust project as a module within an existing project. 

In order to create a project with multiple modules, I had to first import a rust project and then create an additional module for java/python/scala etc. It appears that rust needs to remain as the top level project/module.

When the rust module is not the top-level, cargo run configurations end up trying to use the JDK instead of the correct cargo executable (despite project sdk = rust).

**Comment by matklad** [comment]
Ok, turns out that configuration UI was missing. 

Now it should be possible to `import module` from the project structure menu (`Ctrl+Alt+Shift+S`). But you'll need to specify Rust SDK for the module manually after the import. 

![module](https://cloud.githubusercontent.com/assets/1711539/13904491/866c7eb4-eeb3-11e5-8c2f-29cf36c9319b.png)

This is a bit stupid, I want to fix this soon. 

I hope this solves your immediate issue, thanks for the report!
