### ISSUE TITLE
Cargo home is stable, but must be nightly (multirust)

### ISSUE THREAD

**Issue by KalitaAlexey** [intellij-rust/intellij-rust#300]
I have multirust. My multirust default is **nightly**. When I import project it shows cargo home is **stable**.
Issue in `intellij-rust/src/main/kotlin/org/rust/cargo/project/RustSdkType.kt`
```
listOf("stable", "beta", "nightly").forEach {
    val multiSub = File(root, it)
    if (multiSub.exists()) {
        return multiSub.absolutePath
    }
}
```
It chooses first existing directory.
multirust has `show-default`. It must be used.

**Comment by matklad** [comment]
Yes, you are right, a `default` toolchain is a better default then a `stable`. But please note that this is simply a suggestion, and its fine to point IDEAs SDK to another location.

**Comment by KalitaAlexey** [comment]
@matklad I understand this, but it may be done easily and users will not be required to specify it youself.

**Comment by matklad** [comment]
Yes, I'll fix this if I have some spare time before `rustup` arrives :)

**Comment by netvl** [comment]
Note that this prevents some test from completing. In the current stable version `cargo` does not have `metadata` command, but some tests uses this approach to detect the Rust toolchain and naturally fail. Although I think this error may become obsolete with the next Rust release.

**Comment by netvl** [comment]
Note that since rustup reuses .multirust directory and apparently has changed the convention for naming toolchains from `stable`/`beta`/`nightly` to `stable-<target triple>`, so this naive algorithm for deducing the appropriate toolchain breaks.

I guess I'll tackle this problem after I'm finished with the add derive intention, if you don't mind :)

**Comment by matklad** [comment]
@netvl actually I want to do a bit of architecture-level refactoring in the whole `cargo` area, so it is not the right time to work on this :)

The refactoring is needed because the whole `ExternalSystem` and `SDK` thing is not available in other IDEs (i.e. CLion).

**Comment by matklad** [comment]
Turns out that using a particular toolchain from `~/.multirust/toolchains` is just wrong, because `cargo` will just use wrong compiler/CARGO_HOME. Instead we should call wrapper script and control the version of toolchain via an environmental variable. The details are here: https://github.com/intellij-rust/intellij-rust/issues/308
