### ISSUE TITLE
recommendation: bounty system

### ISSUE THREAD

**Issue by zeroexcuses** [intellij-rust/intellij-rust#3057]
==== Here is the situation:

  1. I like Rust.
  2. I know some Kotlin, but find the IntelliJ OpenAPI vast and overwhelming.
  3. There are quite a few features I would be happy to pay $10-$50 each to have implemented to added to IntelliJ/Rust.

==== Proposed Solution

  We setup a bounty system.

  1. End users (like myself) write Request-For-Feature specs (detailed description of what new feature would do).

  2. Devs (people who have made more than X commits to IntelliJ-Rust-Plugin) can place bids of the form "Sure, for $Y, I'll rearrange my schedule and implement feature FooBar"

  3. End users contribute (kick starter style) towards the bounty for FooBar.

  4. When $Y is reached, Dev implements feature, releases it, and gets paid.

The reason I think something like this might work is that the Rust-IntelliJ-Plugin devs, having already contributed commits, are far far far more reliable than the avg kickstarter.

This has a few other side benefits:

  * It's nice to recompensate the Devs for their time.
  * It allows end users to "throw money at features" that would drastically increase their daily productivity.

**Comment by zeroexcuses** [comment]
Append: This was added here at the suggestion of https://users.rust-lang.org/t/which-rust-ide-offers-most-internal-reprogrammability/22349/6

**Comment by vlad20012** [comment]
Hello!
As a one of 4 JetBrains employees who work on IntelliJ-Rust, I'd say that such approach is not suitable for us, because JB already pay for our work :) Also, I don't know anything similar in the OSS world. You might as well suggest "bounty system" to rust-lang etc :)

The good news is that it is enough to file a feature-requesting issue to this tracker and chances are that sooner or later it will be implemented. You can also "throw :+1: likes at features" :)
