### ISSUE TITLE
Issue with type inference with `specs` crate

### ISSUE THREAD

**Issue by akxcv** [intellij-rust/intellij-rust#3155]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2112-182
* **Rust toolchain version:** 1.31.0
* **IDE name and version:** Intellij IDEA Community 2018.2.6
* **Operating system:** macOS 10.14.2

## Problem description

Not sure what actually isn't working, but when using `specs` crate, autocompletion and type inference do not work when dealing with resources:

``` rust
impl<'a> System<'a> for SysA {
    type SystemData = (WriteStorage<'a, Pos>, ReadStorage<'a, Vel>);

    // Here, Idea fails to resolve types for `pos` and `vel`, as well as the `join` function.
    fn run(&mut self, (mut pos, vel): Self::SystemData) {
        for (pos, vel) in (&mut pos, &vel).join() {
            pos.0 += vel.0;
        }
    }
}
```

Unfortunately, I haven't been able to narrow down the issue so far.

## Steps to reproduce

Open [specs crate sources](https://github.com/slide-rs/specs), and go to `examples/basic.rs:29`. Look for the issues described above.

**Comment by rafaelGuerreiro** [comment]
I am also having this issue and it's worse because it won't autocomplete anything after that join method. Even when disabling it with `//noinspection RsUnresolvedReference`.

My environment:
**Intellij-Rust plugin version**: 0.2.101.2129-191
**Rust toolchain version**: 1.36.0
**IDE name and version**: Intellij IDEA 2019.1.3 (Ultimate edition)
**Operating system**: macOS 10.14.5

**Comment by vlad20012** [comment]
If you run into the same issue, consider enabling the new macro expansion engine as described in https://github.com/intellij-rust/intellij-rust/issues/3628
