### ISSUE TITLE
Intention: contract imports, expand imports

### ISSUE THREAD

**Issue by mrhota** [intellij-rust/intellij-rust#316]
I want to contract this:

```
use libc::c_char;
use libc:c_int;
use libc::LC_ALL;
```

into this:

```
use libc::{c_char, c_int, LC_ALL};
```

Likewise, expand this:

```
use libc::{c_char, c_int, LC_ALL, setlocale, localeconv};
```

into this (if user highlighted the last two items when intention was invoked):

```
use libc::{c_char, c_int, LC_ALL};
use libc::{setlocale, localeconv};
```

or this (if the prior example is too difficult):

```
use libc::c_char;
use libc::c_int;
use libc::LC_ALL;
use libc::setlocale;
use libc::localeconv;
```

Contracting imports should be straightforward: if user has selected (with text highlighting) several imports that _can_ be contracted into one line, do it. If the user selected only the first two lines from the first example, only those two items would be contracted into the compound `use` statement:

Expanding imports would work similarly: if user has selected (with text highlighting) more than one item in a compound `use` statement, the selected items will be factored out into their own compound `use` statement. If user has selected nothing or everything inside the curly braces, all items will get their own lines as `use` statements, as in the last example above.

**Comment by mrhota** [comment]
Maybe the simple cases should be handled here (ignore highlighting: contract everything, expand everything), and we can make the intention more advanced later.

**Comment by matklad** [comment]
Hm, I am not sure about this one. I think the action that we really need here is "optimize imports". And I think this is [in scope](https://github.com/rust-lang-nursery/rustfmt/blob/da65090050aeffdb42ae73ad9eb9192b9ffd5400/src/imports.rs#L21) of `rustfmt`.'

The actions proposed here seem a bit too niche for me. I always have exactly one use declaration for each prefix. That is, I don't need to contract

```
use libc::c_char;
use libc:c_int;
use libc::LC_ALL;
```

Because I would never write `use libc::some` twice. 

Likewise, rather then expanding 

```
use libc::{c_char, c_int, LC_ALL, setlocale, localeconv};
```

I would format it to 

```
use libc::{c_char, c_int, LC_ALL, 
           setlocale, localeconv};
```


Why do you `use` from the same path twice?

**Comment by mrhota** [comment]
> Why do you use from the same path twice?

For organizing in a different way. Say, one line for types. One line for functions. /shrug/

No big deal. Thanks for taking a look. :smiley:

**Comment by matklad** [comment]
Ok, I'm gonna close this: there's no obvious way of formatting imports, and if we provide an intention for every possibility, that would be a whole lot of intentions. One day this will be handled by optimize imports entirely :)
