### ISSUE TITLE
` await!(async { /* ... */ }); ` situation didn't get covered

### ISSUE THREAD

**Issue by imkow** [intellij-rust/intellij-rust#3179]
nightly didn't cover  ` await!(async { /* ... */ }); ` situation.

**Comment by imkow** [comment]
it still prompt "`async` is reserved keyword in Edition 2018" error at ` await!(async { /* ... */ }); `

**Comment by vlad20012** [comment]
Hmm, looks like the fix is still not in the nightly, bit it's a part of today's release
![image](https://user-images.githubusercontent.com/3221931/50440218-3a0e9a00-0906-11e9-970a-dd86490a46e7.png)

(release is made manually from the master branch, but nightly is time-based auto build, so release can rarely be more actual then nightly)
