### ISSUE TITLE
When will intellij idea support rust debugger ?

### ISSUE THREAD

**Issue by 99yun** [intellij-rust/intellij-rust#3453]
When will intellij idea support rust debugger ?

Or never ? !

**Comment by amakeev** [comment]
There is no plan to support Rust debugging in IntelliJ IDEA Community; Though, eventually the debugging support might come to IntelliJ IDEA Ultimate  (no ETA on that).

Currently, CLion provides the most complete Rust support, including debugging; we also plan to add features such as Rust profiling support to CLion in future.

**Comment by Allenyn** [comment]
Actually, what I just want to know, is whether will debugging support come to IntelliJ IDEA Ultimate ? 

I am done, some one can close it now.

**Comment by Undin** [comment]
Update:
There is a plan to integrate with [Native Debug](https://plugins.jetbrains.com/plugin/12775-native-debugging-support/) plugin to support Rust debugging in IntelliJ Ultimate

**Comment by Undin** [comment]
What we need to do:
* [ ] use [nativeDebug](https://plugins.jetbrains.com/plugin/12775-native-debugging-support) plugin as a dependency of `debugger` module instead of CLion
* [ ] provide a way to download LLDB with the correspnding UI
* [ ] implement `LLDBDriverConfiguration` for non-CLion environment
