### ISSUE TITLE
Any file named body.rs does not highlight

### ISSUE THREAD

**Issue by hntd187** [intellij-rust/intellij-rust#3471]
## Environment

* **Intellij-Rust plugin version:** v0.2.92.2116-183
* **Rust toolchain version:** Stable 1.33
* **IDE name and version:** 
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

## Problem description

Whenever i have a file named `body.rs` it neither highlights or is detected by the IDE at all. If I open the file it seems intellij thinks that it is an Android Render Script file.

## Steps to reproduce
I consistently get this issue with projects like hyper or tower-grpc which have files named `body.rs`

![image](https://user-images.githubusercontent.com/6778339/53698970-47864b80-3db1-11e9-9d74-bebeab6eb32e.png)

**Comment by Undin** [comment]
> If I open the file it seems intellij thinks that it is an Android Render Script file

Looks like it's not true because android render script files have another icon
Now it looks like IDE considers that `body.rs` is just plain text file (or another file type with the same icon)
Try to check it here: `Preferences | Editor | File Types` and just type `body.rs`. It should navigate you to rule that IDE uses to determine file type in this case
![image](https://user-images.githubusercontent.com/2539310/53722789-59cabd00-3e77-11e9-84e2-dad1cfd97c58.png)

**Comment by hntd187** [comment]
Yup, you're right, I have no idea how this got there, but thanks. I thought I was going nuts.
