### ISSUE TITLE
Hovering over variable in debugger never shows its value

### ISSUE THREAD

**Issue by svenschmidt75** [intellij-rust/intellij-rust#3504]
CLion 2018.3.4, plugin v0.2.93.2117-183

**Comment by svenschmidt75** [comment]
Ubuntu 18.04

**Comment by ortem** [comment]
Thanks for reporting! It really doesn't work and I'll try to support this feature. For now, you can enable `Preferences > Build, execution, deployment > Debugger > Data Views -> show value tooltip on code selection` to see evaluated values of selected expressions (but you have to double-click on the variable instead of hovering).
