### ISSUE TITLE
Debugging support for non CLion JB IDEs

### ISSUE THREAD

**Issue by unitto1** [intellij-rust/intellij-rust#3547]
Hey! I have a short question.

Does any other IDE from JB except for CLion can support a debugging? At least theoretically.
Especially Golang =) I'ts will be cool to use 2 IDEs instead of 3 in development (my main lang is Python, so PyCharm is the first).

P.S. tnx for your work and have a nice day!

**Comment by Undin** [comment]
@unitto1 Hi!
Currently, we are going to support rust debugging in AppCode because it's already have almost all code for debugger. But there are some unsolved technical issues related to gdb support 
Also, debugger probably can be supported in Ultimate IDEA but we can't provide any estimation when it will be implemented (see [this](https://github.com/intellij-rust/intellij-rust/issues/3453#issuecomment-468698734) comment for more details)
And there aren't any plans regarding to other IDEs (including Goland) at this moment

**Comment by unitto1** [comment]
@Undin =( tnx for the answer!
