### ISSUE TITLE
Add gdb pretty printer for NaiveDate

### ISSUE THREAD

**Issue by kingsimmy** [intellij-rust/intellij-rust#3639]
## Environment

* **Intellij-Rust plugin version:** v0.2.95.2120-191
* **IDE name and version:** CLion 2019.1

## Description
Currently the debugger display for a Chrono NaiveDate shows only the integer field 'ymdf' on the struct.
Would it be possible to add to prettyPrinters/rust_types.py so that NaiveDate could be detected and rendered more nicely?

![image](https://user-images.githubusercontent.com/10784779/55475229-3bd5b100-560b-11e9-903e-65a30ced69b9.png)

![image](https://user-images.githubusercontent.com/10784779/55475247-4c862700-560b-11e9-97be-413f304f79ce.png)

The following Python code could be used to create a better display when debugging:
````python
import datetime


def render_date(ymdf):
    year = ymdf >> 13
    day_of_year = (ymdf & 8191) >> 4
    date = datetime.date(year -1, 12, 31) + datetime.timedelta(days=day_of_year)
    return '{:%Y-%m-%d}'.format(date)
````
@ortem is this feasible?

**Comment by ortem** [comment]
Hi @kingsimmy!

It's possible to add such pretty-printer, but we don't want to support pretty-printing of types from crates so far because pretty-printers have to use the internal structure of types (e.g. private fields) which can change anytime. I don't think `NaiveDate` internal structure can changes often, but for now we decided to focus only on the Rust standard library. If you know the types from the stdlib without pretty-printing support, please inform me and I'll try to support it.

The best way to improve custom types debugging is expression evaluation support, but for now it's impossible to evaluate Rust expressions due to major problems in rustc's debuginfo (e.g. the lack of DWARF for traits) and gdb/lldb itself.

However, you can customize our pretty-printers and add your own printers. On Linux, they are located on `~/.CLion2019.1/config/plugins/intellij-rust/prettyPrinters`. All you have to do is to add the regexp for `NaiveDate` to `rust_types.py`, add the provider to `gdb_providers.py`, and enable it in `gdb_lookup.py`. The provider can be like this:
```Python
class NaiveDateProvider:
    def __init__(self, valobj):
        self.valobj = valobj
        ymdf = valobj["ymdf"]
        self.year = ymdf >> 13
        self.day_of_year = (ymdf & 8191) >> 4
        self.date = datetime.date(year -1, 12, 31) + datetime.timedelta(days=day_of_year)
        
    def to_string(self):
        return '{:%Y-%m-%d}'.format(date)

    @staticmethod
    def display_hint():
        return "string"
```

Note that these files can be rewritten on every IJ Rust plugin update. We will try to find a more convenient way to use custom pretty-printers in the future.

**Comment by kingsimmy** [comment]
Thank you @ortem. The explanation was useful. I have been able to edit `rust_types.py`, `gdb_providers.py` & `gdb_lookup.py` in C:\Users\\%USERNAME%\\.CLion2019.1\config\plugins\intellij-rust\prettyPrinters\ and now I get a nice display for NaiveDate in the CLion debugger.
