### ISSUE TITLE
Unresolved Reference when referenced Type is not declared in mod.rs

### ISSUE THREAD

**Issue by WolfieWerewolf** [intellij-rust/intellij-rust#3737]
Hello please excuse me if this is a duplicate; I searched but didn't find anything that was specific to my observation.

## Environment
- Intellij-Rust plugin version: 0.2.96.SNAPSHOT-191 -> 0.2.96.212.191
- Rust toolchain version: rustc 1.35.0-nightly (70f130954 2019-04-16)
- IDE name and version: IntelliJ Community 2019.1
- Operating System: Linux Mint 18

## Problem description &  Steps to reproduce
Given a very simple test case with the following directory structure:
![image](https://user-images.githubusercontent.com/10762757/56457395-a64b5880-6350-11e9-9bfa-1d89ce21b8fc.png)

when referencing Vec2f from Vec3f, if Vec2f is not declared in mod.rs Vec2f is not highlighted as 
an unresolved reference... like this:
mod.rs
```javascript
//pub mod vec2f;
pub mod vec3f;
```
![image](https://user-images.githubusercontent.com/10762757/56457508-2cb46a00-6352-11e9-8401-4a32d9c38dcd.png)

whereas when vec2f is added to mod.rs  
```javascript
pub mod vec2f;
pub mod vec3f;
```
![image](https://user-images.githubusercontent.com/10762757/56457487-02fb4300-6352-11e9-86ed-f4fd568427eb.png)

it is highlighted along with the re-factor action to import.
Is this the desired behaviour?  If not would it be preferable to discover the types in the same folder / package (at a minimum) and offer to add them to mod.rs and then offer the current behaviour as a second discrete action?
I have a tiny test project that I can upload to github but I am hoping my screenshots and description are clear enough.

I don't expect anyone here to fix this for me; I would be more than happy to take a crack at it myself assuming this is not the desired behaviour.  If my suggestion is preferred please comment and I will make an attempt to resolve it.

If I am completely off about how this is supposed to work I would also appreciate some direction.  I'm pretty new to rust and coming from Kotlin most recently so I am used to the way the kotlin plugin works... 

Thanks
Kind Regards
/W

**Comment by Kobzol** [comment]
From the perspective of Rust, unless there is a module, the corresponding code does not exist, so I suppose that the plugin mirrors that and only indexes the modules. However I agree that it would be really nice if it could actually offer suggestions based on source files in indexed directories.

**Comment by WolfieWerewolf** [comment]
@Kobzol  thanks for the response, like I said I would be happy to take a crack at this but wanted to get feedback first.  I'll make a minimal attempt at this and submit a PR and I'm sure the specifics will shake out through the code review process.. Thanks.

**Comment by vlad20012** [comment]
It's definitely an expected behavior.

Rust (unlike Kotlin) doesn't force strict file structure. If some .rs file is located in some directory, in general it means nothing: the file can be linked to project via `include!` macro (which we doesn't support yet), or `#[path = "path/to/the/file.rs"] mod foobar;` decl, or can be linked to another crate/s (or can be included to the same crate multiple times), etc, etc. It's more like C++ with `#include` then Java/Kotlin.

Maybe we can think of some heuristics to find files that user forget to link to the project and suggest to add them (e.g. show error in project structure toolwindow), but util `include!` macro isn't supported this can produce a lot of false-positives. And I think it's not a responsibility of auto-import to do search in dangling files. If .rs file isn't (somehow) linked to the project, it's just a text file, we shouldn't take in into account
