### ISSUE TITLE
Still in Alpha?

### ISSUE THREAD

**Issue by dnedrow** [intellij-rust/intellij-rust#3807]
Hi!

Do you (the developers of this plugin) still consider this an alpha?

What features are missing that prevents this from moving to "beta"?

**Comment by Undin** [comment]
@dnedrow Hi!
It's a quite tough question.
On the one hand, we consider that the plugin can be used for rust development generally because a lot of common features are implemented.
On the other hand, there are some unsupported things (the biggest and most important one is full macro support #3628 including #1908) that is rather important either user side because in some cases you don't have any intellisense features or developer side because it prevents us to implement some missing common features (like `create new function` quick fix from unresolved function call) due to possible false positive error annotations.
I think we should commit the product stage (mark it as beta or get rid of "stage" at all and just use some version as other JetBrains product do) but only after full macro support will be implemented

**Comment by dnedrow** [comment]
Cool, thanks for the response. Closing as "answered".
