### ISSUE TITLE
IntelliJ 2016.1: Cannot add Rust SDK

### ISSUE THREAD

**Issue by starstern** [intellij-rust/intellij-rust#387]
When trying to add Rust SDK in IntelliJ 2016.1, there is no such option (latest rust IDE and TOML plug-ins installed):
![untitled](https://cloud.githubusercontent.com/assets/19308382/15184619/36d8e89a-1796-11e6-9034-0dd84851fcdb.png)

**Comment by matklad** [comment]
Yep, we've got rid of the Rust SDK, because it is not available in all IntelliJ based IDE (like CLion). Instead, you need to setup rust in `Settings > Language & Frameworks > Rust` at the moment. 

Check out our new quick start guide: https://github.com/intellij-rust/intellij-rust/blob/master/doc/QuickStart.md :)
