### ISSUE TITLE
Highlight more redundant parenthesis 

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#395]
Follow up of https://github.com/intellij-rust/intellij-rust/pull/393

Highlight redundant parenthesis in `while (true)`, `match (1)`, `return (1)`.

I am not sure about the proper error level here. If `rustc` itself reports a warning then we probably should use `warning` instead of `weak warning`.

**Comment by Furyhunter** [comment]
I am of the opinion that annotations like these should be weak warnings simply because fixing them does not change the semantic meaning of the program. Regular warning annotations have a different highlight that are conventionally used for issues that have possibly unintended meaning, such that changing them causes the program's meaning to change (to a more specific form). Stuff like untyped generics in Java would be a regular warning, whereas unnecessary parens are a weak warning.
