### ISSUE TITLE
Inference lost on openssl since upgrading to 0.2.100.2128-191

### ISSUE THREAD

**Issue by bgrieder** [intellij-rust/intellij-rust#4074]
CLion 2019.1.4
Rust Plugin 0.2.100.2128-191
Rust 1.35.0
openssl 0.10.23

Syntax highlighting and inference lost on crate openssl since upgrading from 0.2.99

![image](https://user-images.githubusercontent.com/797684/60383510-086fba80-9a72-11e9-9c45-275b32b9db20.png)

I already tried to invalidate the caches and to "Refresh the cargo project"

**Comment by bgrieder** [comment]
This seems to actually be unrelated to the plugin version but to the fact that upgrading turned macro expansion back to the "default engine" which does not parse the openssl crate correctly/at all.

Turning back the "experimental engine" with the new version works as expected.
I guess this is still a bug on the default engine.

**Comment by Undin** [comment]
What exactly doesn't work?
Name resolution and type inference starting with `subject_name()` method call?
If yes then it's expected because:
* `subject_name` is method of `X509Ref` 
* `Defer` trait impl from `X509` to `X509Ref` is generated by macro
* Default macro expansion engine doesn't work with `impl` block generated by macro (see #2458)

Just for this, we implemented a new macro expansion engine (experimental at this moment) which allows name resolution and type inference take into account such `impl` blocks

**Comment by Undin** [comment]
@bgrieder Why did you switch back to default macro expansion engine? Do you have any issue related to the new one?
At this moment we're collecting feedback about new macro expansion engine to polish it and make it default so don't hesitate to share feedback - it will help us a lot

**Comment by bgrieder** [comment]
@Undin Hello,
Yes your are right, it is starting with the `subject_name()` method so this is likely a duplicate of #2458 

I did not intend to switch back to the default engine, I think the switch occurred when I upgraded the plugin.
No complain so far with the new macros expansion engine. Good job 👍
