### ISSUE TITLE
Find Usages of ::new slow

### ISSUE THREAD

**Issue by dvtomas** [intellij-rust/intellij-rust#4222]
I have about a hundred constructors of various structs named `new` (`Foo::new`) in my medium sized project (about 50 000 lines split into 10 crates in a workspace). When I hit Alt-F7 to find usages of some of those`new`, it often takes half a minute to perform the search on my Core i5, turning this very fundamental action into something almost unusable. Less common names resolve much faster.

**Comment by vlad20012** [comment]
Yes, it's known issue. Seems like `new` name is so widespread in the Rust ecosystem that our algorithms stop working =D
I think we should make a search by struct/enum name in the case of associated items, but now this approach will work worse because of re-exports that we don't take into account during the search.

Also, we significantly improved the performance recently, it should also affect find usages. Will be in the next release (1 week ETA)
