### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by stiv-yakovenko** [intellij-rust/intellij-rust#434]
HI!

Here is what I do:

<img width="236" alt="2016-06-01 11 32 57" src="https://cloud.githubusercontent.com/assets/4163254/15699245/5faf6a70-27ed-11e6-9da9-2a55b2b4ae3e.png">

the only rust plugin i see in IDEA is the following:

<img width="513" alt="2016-06-01 11 37 19" src="https://cloud.githubusercontent.com/assets/4163254/15699235/5611c83c-27ed-11e6-93f5-0c2313c99b84.png">

please explain me what am I doing wrong, or add some hints to the tutorial. 
Thanx in advance!

**Comment by matklad** [comment]
What version of IntelliJ IDEA are you using? You need at least 15.0.4 (but if you use 15.0.4 you'd better upgrade to 15.0.6 at least).

**Comment by stiv-yakovenko** [comment]
Yes, it was wrong version of IDEA. Why don't you add this info to install tutorial?

**Comment by matklad** [comment]
>Why don't you add this info to install tutorial?

A good question! I am uneasy about specifying the exact requirements because I have not checked the plugin with all IDEs (I use IDEA myself, and sometimes test the plugin under CLion). But it deferentially is better to have mostly correct info than no info at all. Fixed in https://github.com/intellij-rust/intellij-rust/commit/9a09e668711d0d0675251967c6c83abfce454610.

Thanks for bringing this up!
