### ISSUE TITLE
Disable the default `--all` flag when building.

### ISSUE THREAD

**Issue by photex** [intellij-rust/intellij-rust#4386]
## Environment

* **0.2.105.2133-192**
* **1.37.0**
* **CLion 2019.2.1**
* **Windows 10**

## Problem description

Building always uses the `--all` flag even when I've unchecked the option in the Cargo settings.

## Steps to reproduce

I have a very large cargo workspace. Some of the components are generally only able to be built in particular circumstances and environments. I use the `default-members` configuration in the workspace to exclude these.
Unfortunately, IntelliJ-rust seems to only want to run `cargo build --all`.

**Comment by photex** [comment]
![cargo-still-uses-all](https://user-images.githubusercontent.com/301903/64857514-0525ad00-d625-11e9-9ab9-b7f338476dcc.png)

I see the issue that added this option but it apparently has no effect. 
https://github.com/intellij-rust/intellij-rust/issues/2604

**Comment by mchernyavsky** [comment]
`Compile all project targets if possible` relates to `--all-targets` option, not `--all`.

With the new experimental build tool window (https://github.com/intellij-rust/intellij-rust/pull/3926), the "Build" action builds only the current selected configuration instead of all targets.
You can enable the build tool window by setting `cargo.build.tool.window.enabled` variable to `false` (see `Actions > Registry...`).

**Comment by photex** [comment]
Oof. This makes sense. I keep confusing 'targets' and 'projects'. In this case I specifically want to exclude certain projects.
