### ISSUE TITLE
toggle hints for variable, closure, iterator and obvious type hints

### ISSUE THREAD

**Issue by Rustinante** [intellij-rust/intellij-rust#4402]
Right now in the keymap there is only a "Toggle parameter name hints". Can we have this toggle also turn on/off the four hints that can be activated in the settings Editor > Inlay Hints  > Rust "Show for {variables, closures, iterators, types}"?

**Comment by Undin** [comment]
@Rustinante we can't do it because:
* it will be quite weird because `Toggle parameter name hints` should enable/disable hints for **parameters**, not for types
* `Toggle parameter name hints` is a platform action so IntelliJ Rust plugin can't/shouldn't change it. Try to create an issue in the platform [tracker](https://youtrack.jetbrains.com/issues/IDEA)
