### ISSUE TITLE
Can't find offline mode by searching in settings

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#4422]
## Environment

* **IntelliJ Rust plugin version:** 0.2.105.SNAPSHOT-192
* **Rust toolchain version:** 1.39.0-nightly (0b36e9dea 2019-09-09) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.2.1 (CL-192.6262.62)
* **Operating system:** macOS 10.14.6

## Problem description

Can't find offline mode by searching in settings for `offline`

<img width="246" alt="Screen Shot 2019-09-22 at 17 37 51" src="https://user-images.githubusercontent.com/2500320/65389509-ba600f80-dd5f-11e9-86ef-a1a47dd32aff.png">

**Comment by Undin** [comment]
@lancelote it's because you build plugin from source with default settings.
`buildSearchableOptions` gradle task (task that collects all options from plugin configuration panels) is disabled by default to speed plugin build.
You can enable it via `gradle.properties` (see `enableBuildSearchableOptions` property) or use plugin from plugin repository
