### ISSUE TITLE
Add inspection for deriving Copy and Clone

### ISSUE THREAD

**Issue by bgourlie** [intellij-rust/intellij-rust#446]
Per [Steve Klabnik](https://www.reddit.com/r/rust/comments/2xxjda/when_should_my_type_be_copy/cp4djpw), any struct that is made up entirely of `Copy`able elements should derive Copy (and possibly Clone).

It would be cool to to add an inspection that would recommend this.  It would require being able to determine if all elements of a struct implement Copy.  Does this functionality exist yet?  If not, what would need to be done?  I'm interested in contributing and think this would be a cool feature to start with.

**Comment by matklad** [comment]
Hm, I think we already have all the necessary pieces to implement this inspection, but I am afraid of false positives. 

To implement this inspection, you'll need to create a LocalInspectionTool and a [visitor]. In the visitor, you should override `visitStructItemElement` to iterate over all fields, resolve their types and check if they are `Copy` (by [querying] the attributes and special casing built-in types like primitives, tuples and arrays)

However, as I've said, this inspection may give a fair amount of false positives. I actually prefer to add `Copy` to the local type on as needed basis, because I don't know in advance what I'll need first: to use the same value in several places or to store some non-`Copy` type within it. I think the proper solution to this problem will be detecting errors due to moves from types, which can be made `Copy`, and suggesting "add #[derive(Copy)]" Quick Fix. Unfortunately at the moment we can't check if a value was moved or not. So I'll close this particular issue and will try not to forget to ping you once we have the necessary tools to solve the problem properly :)

In the mean time, there is [add derive] intention which places a `#[derive]` attribute on top of the struct. It would be cool to add a [completion contributor] which would suggest adding "derivable" traits to the derive clause (they can be just hardcoded, because they are hard coded into the compiler anyway). Then the logic about `Copy`able types may be used to give relative weight to the `Clone` and `Copy` variants (but this is super optional compared to the mere presence of completions).

[add derive]: https://github.com/intellij-rust/intellij-rust/issues/309

[visitor]: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/inspections/UnresolvedModuleDeclarationInspection.kt#L22

[querying]: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/psi/RustDocAndAttributeOwner.kt#L22

[completion contributor]: http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/completion_contributor.html?search=Comple

**Comment by bgourlie** [comment]
Thanks for the help!  I'll look into adding the completion contributor to derive intention.
