### ISSUE TITLE
When analyzing code, can we consider "#[cfg(test)]"?

### ISSUE THREAD

**Issue by msmouse** [intellij-rust/intellij-rust#4521]
## Environment

* **IntelliJ Rust plugin version:** 0.2.107.2137-192
* **Rust toolchain version:** rustc 1.39.0-beta.2 (5752b6348 2019-09-27)
* **IDE name and version:** CLion 2019.2.4
* **Operating system:** Linux

## Problem description

The project I'm working on has `#[cfg(test)]` before `mod tests` so they are not built if we are not running tests. And the IDE doesn't know about all my tests when I, for e.g., try to jump to call sites of a certain function.

## Steps to reproduce

Right click on a function used in tests and click "find usages", only those non-test callsites show up in the result.

"Refactor -> Rename" doesn't take into account tests either.

**Comment by ortem** [comment]
This problem seems to be fixed due to our initial cfg attributes support (#4488).

<img width="251" alt="Screenshot 2020-02-06 at 17 43 34" src="https://user-images.githubusercontent.com/4854600/73947245-35d5ee00-4908-11ea-9771-c7169da5e40a.png">


@msmouse Please tell us if you're still experiencing such problems with `cfg(test)`.

**Comment by msmouse** [comment]
@ortem  It does work now, thank you!
