### ISSUE TITLE
todo macro not showing up in the TODO menu.

### ISSUE THREAD

**Issue by meltinglava** [intellij-rust/intellij-rust#4609]
As the final comment period for [todo_mcaro](https://doc.rust-lang.org/std/macro.todo.html) has passed and is going to get merged soon, this would be nice to have. Probably just treat it the same way as TODO comments are treated.

**Comment by Travus** [comment]
Yeah, it would be nice to have automatic highlighting of rust native todos and to have them show up in the built-in TODO list.

**Comment by ice1000** [comment]
How about `unimplemented!()`?

**Comment by Undin** [comment]
@ice1000 it can be tricky
The main difficulty is that patterns to treat something as todo item are user defined (see `Preferences | Editor | TODO`) and application wide.
So we shouldn't add something like `\bunimplemented\b` into todo patterns by the plugin because it will affect all projects (not only Rust), e.g. increase indexing time.
Of course, we can add some code to support `unimplemented!` macro as todo item and highlight it only when user adds the corresponding pattern himself. But nobody won't do it because it requires to do something. People don't like set up anything

**Comment by ice1000** [comment]
Ok cool!
