### ISSUE TITLE
Incompatible TOML plugin version, code completion for Cargo.toml is not available.

### ISSUE THREAD

**Issue by alexbool** [intellij-rust/intellij-rust#4681]
## Environment

* **IntelliJ Rust plugin version:** 0.2.111.2797-192-nightly, TOML plugin 0.2.0.35-192
* **Rust toolchain version:** rustc 1.39.0 (4560ea788 2019-11-04)
* **IDE name and version:** IntelliJ IDEA 2019.2.4 (Community Edition)
Build #IC-192.7142.36, built on October 29, 2019
* **Operating system:** macOS 10.15 Catalina

## Problem description
When starting the IDE i get this message: "Incompatible TOML plugin version, code completion for Cargo.toml is not available."

**Comment by Undin** [comment]
It's expected after #4643
It will be automatically fixed with new Toml plugin update next week.
Or you can install its nightly version. Just add the corresponding nightly repository https://plugins.jetbrains.com/plugins/nightly/8195 as described [here](https://www.jetbrains.com/help/idea/managing-plugins.html#repos) and update Toml plugin

**Comment by alexbool** [comment]
OK, thanks!
