### ISSUE TITLE
Make build plan execution error available to user 

### ISSUE THREAD

**Issue by Exidex** [intellij-rust/intellij-rust#4699]
## Environment

* **IntelliJ Rust plugin version:** 0.2.110.2150-192
* **IDE name and version:** CLion 2019.2.3 Build #CL-192.6817.18
* **Operating system:** Manjaro

`org.rust.cargo.fetch.out.dir` experimental feature enabled

## Problem description
When plugin attempts to get build plan and gets some sort of error, the error is just logged, or, from the point of view of user, silently ignored, while some features like expanding `env!` (and subsequently `include!`) macro just don't work. I my case the error was 'Premission denied' because some random file inside target directory had root owner.

Relevant code:
https://github.com/intellij-rust/intellij-rust/blob/60bbb1179df16042bb25d198ac280feca7839cd7/src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt#L145

## Feature request
When build plan execution error happens show the error to the user in some sort of popup.

Thanks for making this plugin!

**Comment by Undin** [comment]
Thanks for the suggestion!
It's definitely reasonable!
I think we won't implement it for `build-plan` option because of https://github.com/rust-lang/cargo/issues/7614
But we are planning use output of `cargo check` command to extract info about output directory and show `Sync` tool window  like other build tools (gradle, maven, etc) already do
