### ISSUE TITLE
Rust integer primitive missing method suggestions and inference

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#4826]
## Environment

* **IntelliJ Rust plugin version:** 0.2.113.2150-193
* **Rust toolchain version:** rustc 1.39.0 (4560ea788 2019-11-04)
* **IDE name and version:** CL-193.5662.56
* **Operating system:** Mac OS X(x86_64) v10.15.2

## Problem description

In Rust, primitives such as `u16` or `u64` have byte order conversion methods such as `to_le()`, `to_be()`, or `to_be_bytes()`.

Specifically, `to_be_bytes()` takes an integer and returns a known-size byte array. A u16 returns one of length 2. However, CLion doesn't seem aware of any of those methods, and also seems unaware of the byte inference. The methods are missing from autocompletion, when using them, the type inference is missing, and when writing a bogus type annotation such as `[u8; 3]` for the byte output result (when it should be `[u8; 2]`), CLion is not complaining. All three examples are demonstrated in the attached screenshots.

Submitted to CLion bug tracker https://youtrack.jetbrains.com/issue/CPP-18659

**Comment by Undin** [comment]
@arik-so Thanks for the report!
The main cause of missing completion is that all these methods are generated by macros in stdlib.
The default macro expansion engine can't process `impl` blocks generated by macros.
Try to enable an experimental macro expansion engine. It should fix name resolution/completion issues. See #3628 for more details.

About type inference of return value of `to_be_bytes`. Even with experimental macro expansion engine, the plugin fails to infer size of returning array because stdlib uses `mem::size_of` to get type size in compile time. At this moment, the plugin can't evaluate such expressions. But it's separate problem not related to the first one. I've created a new issue for this problem - #4831
