### ISSUE TITLE
 IntelliJ Editor mangles location of braces when using rust 

### ISSUE THREAD

**Issue by grimreaper** [intellij-rust/intellij-rust#5008]
What steps will reproduce the issue?
1. Open any rust file
2. type 
```rust
pub fn foo() {
}
```
3. press Enter

What is the expected result?
The braces are on the same line they started as 

What happens instead?
You get 
```rust
    pub fn foo() {}
```

and I can't find any setting that changes this behavior

IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.5616.10, built on February 18, 2020
IntelliJ IDEA EAP User
Expiration date: March 19, 2020
Runtime version: 11.0.6+8-b722.15 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 8
Registry: vcs.log.keep.up.to.date=false, analyze.exceptions.on.the.fly=true, debugger.valueTooltipAutoShowOnSelection=true, ide.tooltip.initialDelay=485, vcs.log.recent.commits.count=10, git.update.incoming.info.time=200000
Non-Bundled Plugins: String Manipulation, CheckStyle-IDEA, Lombook Plugin, YourKit Java Profiler 2019.1-b114 Integration, com.github.oowekyala.javacc, ru.artyushov, Pythonid, org.jetbrains.plugins.ruby, org.toml.lang, org.rust.lang, org.intellij.scala

Possibly related to #4576

**Comment by Undin** [comment]
@grimreaper I can't reproduce it
Could you provide more details about what are you doing?
I may suppose only two similar things:
- you invoke reformat action somehow
- `Rust rustfmt on save` option from `Preferences | Languages & Frameworks | Rust | Rustfmt` is enabled and you invoke `Save` action manually or via focus change

**Comment by grimreaper** [comment]
Gif of repro. The keys being pressed in order are `fnf<backspace> foo{<enter>}`
![intellij-rust-intellij-rust-issue-5008-repo-1 mov](https://user-images.githubusercontent.com/433817/75614946-e43a1100-5b0b-11ea-84ee-454268d08df9.gif)


<img width="589" alt="image" src="https://user-images.githubusercontent.com/433817/75614953-ffa51c00-5b0b-11ea-8b6b-1e56a13bdd16.png">

<img width="245" alt="image" src="https://user-images.githubusercontent.com/433817/75614956-092e8400-5b0c-11ea-9295-3309e8f33600.png">

<img width="621" alt="image" src="https://user-images.githubusercontent.com/433817/75614962-13e91900-5b0c-11ea-9952-0298624cba11.png">

**Comment by Undin** [comment]
Oh, thanks for the gif, it helps a lot! I've reproduced this behavior.
An interesting fact that it's not a bug (al least in usual meaning) but it's indeed rather unexpected.

It's because of combination of three options (all of them are located in `Preferences | Editor | General | Smart Keys`): 
* disabled `Insert paired brackets`
* disabled `Enter | Insert pair '}'`
* enabled `Reformat block on typing '}'`

Usually, all of them are enabled and you don't need to insert `}` manually and you don't trigger block reformating. But in your case, you type `}` manually that triggers code reformat (as I supposed) that collapse empty function body to `{}`.
I'd recommend enabling at least of `Insert paired brackets` and `Enter | Insert pair '}'` options because they are quite useful. Or just turn off `Reformat block on typing '}'` option.

**Comment by grimreaper** [comment]
Ah,

That all makes sense. I heavily dislike the editor adding additional characters so I disable almost all "pair" elements. I think I'll have to turn off `Reformat block on typing '}'` and likely enable reformat-on-save. We'll see which setup annoys me less. :/
