### ISSUE TITLE
Why intellij-rust need external linter to find code errors

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#5043]
## Environment

* **IntelliJ Rust plugin version:** 0.2.118.3005-193-nightly
* **Rust toolchain version:** rustc 1.43.0-nightly (4ad624882 2020-03-03)
* **IDE name and version:** clion 2019.3.4
* **Operating system:** Arch Linux

## Problem description
If not enable external linter, intellij-rust will miss a lot of code errors, it report everything fine but when `cargo build` will report some code errors

## Steps to reproduce

like #4260, without external linter, intellij-rust won't display those errors. 

I notify Goland, Idea don't need any external linter to find code errors, does intellij-rust will detect all code erros in the future? Because external linter spend a loooooooooot of time to check codes.

**Comment by Undin** [comment]
@Sherlock-Holo since the plugin doesn't use the compiler to analyze code (in fact, we cannot do it because of different architecture), we have to implement all error detection ourselves. It's a lot of work. Also, some parts of plugin analysis may produce false-positive errors in some cases (for example, if code contains an invocation of procedural macro, we can't handle it right now). So some error checks are not implemented yet because we didn't have time for it. Other checks cannot be safely implemented/enabled by default without false-positive annotations. For example, `Unresolved reference` inspection can report all unresolved references for paths and method calls right now (see `Ignore unresolved references without quick fix` option for `Preferences | Editor | Inspections | Rust | Unresolved reference` inspection) but it doesn't do it by default because may produce a lot of false-positive errors.

Currently, the main reasons of wrong analysis are macros (see #3628), incomplete support of `cfg` attributes (see #1191) and imperfect type inference in complex cases.
External linter is a temporary solution to bring compiler error detection to a user until we implement own checks

**Comment by Sherlock-Holo** [comment]
thanks for jour jobs writing this plugin, it helps me a lot when I learn rust. I will keep using the nightly plugin to help you improve this plugin.
