### ISSUE TITLE
"Generator Constructor" doesn't use type alias

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#5044]
## Environment

* **IntelliJ Rust plugin version:** 0.2.118.SNAPSHOT-201-dev
* **Rust toolchain version:** 1.41.0 (5e1a79984 2020-01-27) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1 EAP (CL-201.5616.31)
* **Operating system:** macOS 10.15.3

## Problem description

"Generator Constructor" action always uses original type instead of the alias. I guess it is #4944 regression.

## Steps to reproduce

```rust
type Coordinates = (u32, u32);

struct System {
    point: Coordinates,
}
```

call "Generator Constructor" on `System`

```rust
impl System {
    pub fn new(point: (u32, u32)) -> Self {
        System { point }
    }
}
```

expected

```rust
impl System {
    pub fn new(point: Coordinates) -> Self {
        System { point }
    }
}
```

**Comment by Kobzol** [comment]
You're right, this is indeed a regression caused by #4944. It is caused by using `substAndGetText` on the type reference instead of just taking its raw `text`. This is needed to substitute bound type parameters on an existing impl block.

There is a problem though, after the substitution we can no longer access the `typeReference` text. And since aliases only work on `TyAdt` so far, it will not work for tuples and other types :-(
With `TyAdt` it should work:

```rust
struct S;
type Coordinates = S;

struct /*caret*/System {
    point: Coordinates,
}
// generates
impl System {
    pub fn new(point: Coordinates) -> Self {
        System { point }
    }
}
```
@Undin what do you think?

**Comment by Undin** [comment]
@Kobzol I think we need to extend current API with aliases from `TyAdt` to `Ty` (or at least for something less specific). And use this API to make proper fix
