### ISSUE TITLE
macro expansion: Unresolved reference: `read_exact`

### ISSUE THREAD

**Issue by Ryan-Git** [intellij-rust/intellij-rust#5055]
## Environment

* **IntelliJ Rust plugin version**: 0.2.117.2170-193
* **Rust toolchain version**: 1.41.0
* **IDE name and version**: CLion 2019.3
* **Operating system**: MacOS

## Problem Description
The experimental macro expand works perfectly with my little async-std project. But after I adds tokio(depending on both async-std and tokio), it gives the error `Unresolved reference: read_exact` on existing working code and suggests to import `tokio::io::AsyncReadExt`, which actually has already been imported with `async_std::io::ReadExt`.

Some separating/name-spacing might be needed for this? There are quite a few similar functions within futures, async-std and tokio.

## Steps to reproduce

https://github.com/Ryan-Git/sagittarius

**Comment by Undin** [comment]
> The experimental macro expand works perfectly with my little async-std project. But after I adds tokio(depending on both async-std and tokio), it gives the error Unresolved reference:

Really, it's not true. The plugin fails to make correct name resolution for `read_exact` method even without additional dependencies. But it just doesn't report it to you.

The plugin has `Unresolved reference` inspection to highlight such things. But for now, it highlights unresolved references only when there are suitable things to import to avoid a lot of false-positive annotations (such behavior can be configured by `Ignore unresolved references without quick fix` option in `Preferences | Editor | Inspections | Rust | Unresolved reference`).

So without additional dependencies, the plugin just doesn't show this unresolved `read_exact` method. But when you add `tokio` dependency, it brings `read_exact` method with `AsyncReadExt` trait that's why the plugin starts to highlight it

**Comment by Ryan-Git** [comment]
I tried again and ur right. Is there any plan to fix this?

**Comment by Undin** [comment]
@Ryan-Git I don't think we need any special "plan" to fix it. It requires some investigation where type inference engine fails and make the corresponding fix

**Comment by dima74** [comment]
@Ryan-Git could you please check if issue still persists. I can't reproduce it now:

![image](https://user-images.githubusercontent.com/6505554/103350384-dd27ba80-4ab0-11eb-9ba8-668589d3e1e5.png)

* **IntelliJ Rust plugin version:** 0.3.139.3575-203-nightly
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3 (CL-203.5981.166)
* **Operating system:** Linux 5.9.14-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** old

**Comment by Ryan-Git** [comment]
Let me upgrade CLion first...

**Comment by dima74** [comment]
Please feel free to reopen if you still experience the problem
