### ISSUE TITLE
Support Rust extended (opt-in) syntax

### ISSUE THREAD

**Issue by Apanatshka** [intellij-rust/intellij-rust#510]
Some opt-in [features](https://doc.rust-lang.org/reference.html#compiler-features) of Rust have syntax related to it. A simple one that I'm using is `inclusive_range_syntax`, which allows `a...b` syntax. It's a little annoying to have that marked red in the IDE. Conditionally supporting the syntax is probably more complicated, but as a start, can you support the extended syntax?

I think these are features that come with syntax:

- [ ] `advanced_slice_patterns`
- [ ] `slice_patterns`
- [ ] `box_patterns`
- [ ] `box_syntax`
- [ ] `inclusive_range_syntax`
- [ ] `log_syntax` (low-priority, likely to be removed)
- [ ] `non_ascii_idents` (unstable, maybe already supported?)
- [ ] `type_ascription` (maybe already supported?)

**Comment by Furyhunter** [comment]
The grammar should include these and inspections should produce errors if they are used without the appropriate feature meta item, just as the compiler currently does.

**Comment by Apanatshka** [comment]
@Furyhunter Eventually, yes. But I'd settle for just having them included in the grammar for now.

**Comment by matklad** [comment]
Thanks for the report!

We indeed intend to support nightly syntax. It's interesting that we actually have to do this, because standard library itself uses nightly features. Looks like inclusive ranges are the only omission at the moment. 

About warning when using nightly features on stable, we definitely should implement it some day, but it is of low priority now. There is no issue for this, but it is ok: the feature is obvious.

**Comment by alexeykudinkin** [comment]
@matklad it's still better not to keep it in mind, but keep it on record: let's create a separate issue for that.

**Comment by matklad** [comment]
@alexeykudinkin done: https://github.com/intellij-rust/intellij-rust/issues/511
