### ISSUE TITLE
"Add _ pattern" context action does not append comma to last line

### ISSUE THREAD

**Issue by jammehcow** [intellij-rust/intellij-rust#5113]
## Environment

* **IntelliJ Rust plugin version: 0.2.118.2171-193**
* **Rust toolchain version: 1.40.0**
* **IDE name and version: CLion 2019.3.4**
* **Operating system: Windows 10 Enterprise (10.0.18362)**

## Problem description

When using "Add _ pattern" or "Add remaining patterns" context actions on a `match` statement commas aren't appended to the last line, causing a syntax error.

## Steps to reproduce

 1. Create a `match` statement with no `_` pattern
 2. Execute either "Add _ pattern" or "Add remaining patterns" context actions on the `match` statement

## Example

![jetbrains_rust_plugin_exhaustive](https://user-images.githubusercontent.com/4962764/77045916-0069f900-69ba-11ea-9c86-0b4f337eaa6e.gif)

**Comment by Stzx** [comment]
I want to know @Undin Do you think a comma should be added for this case?

```rust
fn main() {
    let a = true;
    match a {
        true =>
    }
}
```

**Comment by Undin** [comment]
@Stzx I don't have strong opinion about it. It seems that the addition of comma is slightly better because allows parser to recover from code without expression but with comma, i.e.

| with comma | without comma |
| - | - |
| ![image](https://user-images.githubusercontent.com/2539310/78133769-bc4e0e00-7427-11ea-8d60-f645db0c1a69.png) | ![image](https://user-images.githubusercontent.com/2539310/78134702-39c64e00-7429-11ea-93c9-5555c729cb59.png) |


I think we should take it into account in #5143 as well

**Comment by Stzx** [comment]
> I think we should take it into account in #5143 as well

OK, I will exclude only block expressions.
