### ISSUE TITLE
Project creates not a "correct" rust project

### ISSUE THREAD

**Issue by schmitch** [intellij-rust/intellij-rust#525]
I actually supposed that the Create Rust project would've created a Cargo project however the project it created only contained a *.iml file and it wasn't even possible to create directories in it. And the Rust stdlib wasn't even asked.

**Comment by matklad** [comment]
Yes, this is a know issue: https://github.com/intellij-rust/intellij-rust/issues/401

**Comment by schmitch** [comment]
Oh sorry I searched for "create" but somehow I must've set a filter wrong -.-

**Comment by matklad** [comment]
No worries, I guess we just need to implement this, it's a frequently requested functionality :) 

I am a bit hesitant about this, because wrapping `cli` tools in the GUI is difficult (GUIs in general are difficult) and for me it does not provide much benefit, because I use command line a lot anyway. But yes, being able to do this from withing IDE would be nice!

**Comment by schmitch** [comment]
Actually I use the CLI a lot, too. Mostly on Scala, but unfortunatly project creation isn't "as easily" when using a GUI. You would need to switch to a console.
When inside the project inside IntelliJ, you could just open the Terminal and do all the things. ;)
