### ISSUE TITLE
How to build the plugin for CLion?

### ISSUE THREAD

**Issue by flaghacker** [intellij-rust/intellij-rust#5253]
I'm trying to build the plugin as a distribution to install from disk into CLion, so as described in [`CONTRIBUTING.md`](https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md) I ran the command `./gradlew :plugin:buildPlugin` which indeed results in a zip file in `plugin/build/distributions`. I'm able to install this plugin from disk into IntelliJ, but CLion gives the following error message:

![image](https://user-images.githubusercontent.com/7887115/79620239-9014db80-810f-11ea-9de5-f4f04282f742.png)

I tried to set `baseIDE=clion` in `gradle.properties` but that has the same result, the distribution is installable into IntelliJ but not CLion.

Could the build instructions be clarified on how to build for CLion?

**Comment by Undin** [comment]
What version of CLion do you use?
By default, `./gradlew :plugin:buildPlugin` builds plugin compatible only with 2020.1 IDEs. If you try to install this plugin to CLion 2019.3, the installation will fail.
If you want to build plugin compatible with 2019.3, you need to change `platformVersion` property from 201 to 193 in `gradle.properties`.
Note, `IntelliJ Rust` plugin has a mandatory dependency on `Toml` plugin, so you still need to install it to your IDE as well.
But usually, you don't need to build plugin and install in from disk manually. If you want to run plugin with your changes just to check them, launch `Run` or `RunCLion` run configuration - it launches `IDEA` or `CLion` with built plugin right from plugin project.
![image](https://user-images.githubusercontent.com/2539310/79632459-fb8a9780-8167-11ea-8b6c-b2e229576eaf.png)
Anyway, all this explanation should be in our documentation. Thanks!

**Comment by flaghacker** [comment]
Thanks for the response!

My bad, I was indeed still running the old CLion version. I though I had updated all of my IDEs to 2020.1 with toolbox at once, looks like I missed CLion.

My use case is that I want to test changes to the plugin in my proper setup with other plugins, my settings and my exiting project list. Is there something better I can do than manually installing the plugin from disk every time?

**Comment by Undin** [comment]
> My use case is that I want to test changes to the plugin in my proper setup with other plugins, my settings and my exiting project list. Is there something better I can do than manually installing the plugin from disk every time?

It's a rather specific scenario. May I interest why do you need all these settings while plugin development?

Meanwhile, you can do it. 
All your desired IDE settings are stored into 3 directories: [config](https://www.jetbrains.com/help/idea/2020.1/tuning-the-ide.html#config-directory), [system](https://www.jetbrains.com/help/idea/2020.1/tuning-the-ide.html#system-directory) and [plugins](https://www.jetbrains.com/help/idea/2020.1/tuning-the-ide.html#plugins-directory).

You may copy existing settings in sandbox directory manually. By default, [`gradle-intellij-plugin`](https://github.com/JetBrains/gradle-intellij-plugin) (that we use to build our plugins) creates sandbox directory where all settings and plugins are stored while development. In our project we use two different sandbox directories not to mix IDEA and CLion settings. They are `plugin/build/idea-sandbox` and `plugin/build/clion-sandbox` respectively. According to [this](https://github.com/JetBrains/gradle-intellij-plugin#running-dsl) documentation, `gradle-intellij-plugin` creates config, system and plugins directories in `${sandboxDirectory}/config`, `${sandboxDirectory}/system` and `${sandboxDirectory}/plugins`. You can copy your current CLion settings directories into these ones to create a similar environment. 

Unfortunately, plugin directory will be cleaned each time when you run IDE via `Run` or `RunCLion` run configuration, i.e. copying of plugin directory is useless. Instead of it, you may specify all required plugins in build script. You can find necessary documentation [here](https://github.com/JetBrains/gradle-intellij-plugin#intellij-platform-properties). In our project, we do it [here](https://github.com/intellij-rust/intellij-rust/blob/master/build.gradle.kts#L184-L195).

Note, by default, sandbox directory is located in `build` dir and if you run `gradle clean`, sandbox directory will be removed. Of course, you can specify specific sandbox directory location (see [this section](https://github.com/JetBrains/gradle-intellij-plugin#rundebug-ide-properties))

Not sure that it's the simplest way to do it but I hope it will help you

**Comment by flaghacker** [comment]
I don't need the my exact settings etc, but it'd be convenient to test whether I actually fixed something in my proper projects and in my real environment I think.

Thanks for the explanation, I'll give it a shot!
