### ISSUE TITLE
'Surround selection on typing quote or brace' smart key not working for curly bracket at the end of a rust use statement

### ISSUE THREAD

**Issue by FelixBrakel** [intellij-rust/intellij-rust#5256]
## Environment

* IntelliJ Rust plugin version: 0.2.120.2202-201
* Rust toolchain version: 1.42.0
* IDE name and version: CLion 2020.1
* Operating system: Arch Linux

## Problem description
When selecting the last part of a rust use statement and typing '{' the caret just jumps one position forwards or stays at the end of the current selection depending on its starting position instead of placing curly brackets around the selection.

## Steps to reproduce
Consider the following example:
```rust
use std::mem

fn main() {
    println!("Hello World!")
}

```

1. Select the `mem` part of the `use std::mem` on line 1.
2. Press '{'

Square brackets, parenthesis, single and double quotes all work. The only one that is broken is the curly bracket, which is a bit sad since it is the one you would most often use in `use` statements.

**Comment by Undin** [comment]
Hm, it's interesting
It seems since 2020.1 IDE makes automatic reformat when you try to surround selected text with `{}`. At the same time, the plugin has a feature to remove unnecessary `{}` in `use` items (it was introduced in #1369) while reformating. As a result, IDE inserts paired `}` and then deletes it while reformatting. From user side, it looks that nothing changes.
I think we need to move this processing to `Optimize Imports` action to avoid such behavior.
Right now you can disable it via enabling `Wrapping and Braces | Keep when formatting | Punctuation` option in `Preferences | Editor | Code Style | Rust` settings.
