### ISSUE TITLE
Auto completion not working for external crate.

### ISSUE THREAD

**Issue by Beiri22** [intellij-rust/intellij-rust#5278]
## Environment

* **IntelliJ Rust plugin version:** 0.2.120.2202-201
* **Rust toolchain version:** nightly-x86_64-unknown-linux-gnu, but same issue with stable
* **IDE name and version:** CLion 2020.1
* **Operating system:** Manjaro Linux, testing branch

## Problem description
I try to use some structs of the crate mathru. There is no problem compiling and using them, but the code completion does not work. Example for reproduction:
```rust
extern crate mathru;

use mathru::statistics::distrib::{Distribution, Normal};

fn main() {
    let n: Normal<f64> = Normal::new(10.0, 1.0);

    let mut buckets = [0; 20];
    for _ in 0..1000
    {
        let num = n.random().round() as i64;
        if num >= 0 && num < 20
        {
            buckets[num as usize] += 1;
        }
    }

    println!("{:?}", buckets);
}
```

## Steps to reproduce
When calling the function `let num = n.random()` the code completion does not show the function random() of trait Distribution. As far as I understand, it should be shown in code completion since struct normal and trait Distribution are imported. The code compiles.

**Comment by Undin** [comment]
Thanks for the report!
`random` method is available only for `Normal<T> where T: Real` and `where T: Real` is the cause of the problem here. As you can see [here](https://gitlab.com/matthiaseiholzer/mathru/-/blob/master/src/algebra/abstr/real.rs#L34), the corresponding `impl` for `f64` generated by macro call. Unfortunately, the default macro expansion engine can't handle `impl` blocks generated by macros because of some technical reasons. As a result, the plugin doesn't know that `f64` implements `Real` and doesn't provide the corresponding completion.
Try to enable new macro expansion engine (see #3628 for details). It should help

**Comment by Beiri22** [comment]
Thank you very much. It works now.

**Comment by singggum3b** [comment]
Hi , im having same issue even when turned on experimental macro expansion.
The code below can't suggest trait method `run` of `warp::Server` returned from `warp::serve(promote)`
```
use serde::{Deserialize, Serialize};
use std::convert::Infallible;
use std::net::SocketAddr;
use warp::Filter;

#[derive(Deserialize, Serialize)]
struct Employee {
    name: String,
    rate: u32,
}

#[tokio::main]
async fn main() {
    // POST /employees/:rate  {"name":"Sean","rate":2}
    let promote = warp::get()
        .map(|| { "" });
    warp::serve(promote)
        .run(([127, 0, 0, 1], 3030))
        .await;
}
```
