### ISSUE TITLE
Intellij rust plugin does not give give hint to create a function 

### ISSUE THREAD

**Issue by Haider8** [intellij-rust/intellij-rust#5301]
## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-201-stable
* **Rust toolchain version:** rustc 1.43.0 (4fb7144ed 2020-04-20)
* **IDE name and version:**  CLion-2020.1
* **Operating system:** Linux (16.04.1-Ubuntu)

## Problem description
On some other Intellij IDEs when you call a function that doesn't exist already it gives you a hint to create that function either by pressing `alt+enter` or the yellow bulb appears with the suggestion to create that function. But this is not happening in CLion along with rust plugin.

## Steps to reproduce
Call a function that doesn't exist and then hit `alt+enter`. Nothing will happen, no hint will appear.

**Comment by Kobzol** [comment]
There are already several similar existing issues: https://github.com/intellij-rust/intellij-rust/issues/3581 https://github.com/intellij-rust/intellij-rust/issues/3904. This intention was intentionally not implemented yet because it would present a lot of false positives, at least until the new macro expansion engine is enabled by default (https://github.com/intellij-rust/intellij-rust/issues/3628), as explained here: https://github.com/intellij-rust/intellij-rust/issues/3807#issuecomment-493417580.

@Undin is this still valid, i.e. does this intention wait for the new macro expansion engine? Maybe we can only enable the intention if the new macro expansion engine is active?

**Comment by Undin** [comment]
@Kobzol I think we can implement it as quick fix for unresolved reference inspection even currently.
But right now unresolved inspection is disabled by default for paths that cannot be imported via `Auto import` quick fix to avoid false-positive errors.
So if you want, you can try to implement it (and it would be very cool!). But most of the users won't be able to use it right now.

> Maybe we can only enable the intention if the new macro expansion engine is active?

I think it's more about enabling unresolved reference inspection in the corresponding cases. It requires investigation: how many false-positive errors we get even with new macro expansion engine? Probably, still a lot because of procedural macros but we can take it into account as well.
Anyway, this task doesn't depend on the desired quick fix and can be solved separately

**Comment by Kobzol** [comment]
Okay, then I suggest that we add a new quick fix to unresolved paths that look like a function call. We can also add support for method calls, but for these I think that we would need an option in the plugin settings to turn it off, because I expect that method calls will have more false positives than free-standing functions (because of procedural macros and `derive`s on structs and enums).

For start, I would only use the quick fix for function calls without a nested path, i.e. `a::b::nonexistent(...)` would not get the quick fix. Otherwise we would need to create the `a` and `b` modules if they do not exist, which could get ugly (create a new file or create them as a local `mod`?). I'll try to send a PR with a prototype.

**Comment by Undin** [comment]
> For start, I would only use the quick fix for function calls without a nested path, i.e. a::b::nonexistent(...) would not get the quick fix. Otherwise we would need to create the a and b modules if they do not exist, which could get ugly (create a new file or create them as a local mod?). I'll try to send a PR with a prototype.

Note, if in `a::b::nonexistent(...)` `a` or `b` doesn't exists, `nonexistent` are not highlighted by unresolved reference inspection. So you shouldn't support such cases. But eventually, it would be great to support case, when only `nonexistent` doesn't exist while `a` and `b` modules are already in the project
