### ISSUE TITLE
How to invoke file-wide intentions?

### ISSUE THREAD

**Issue by kryptan** [intellij-rust/intellij-rust#531]
Website mentions that it is possible to automatically expand and contract modules but doesn't say how to do it. For other three intentions light bulb appears or you can press Alt+Enter but for these two there is no light bulb and Alt+Enter doesn't show anything.

**Comment by matklad** [comment]
Hi! We are in the process of refactoring our docs, the current proposal is [here], you may find it useful. 

Expand module currently only available as a quick fix for unresolved module. That is, if you type `mod quux;` in `foo.rs`, a red squiggly and light bulb will appear.

Contract module should be available via light bulb or find action, but only if `mod.rs` is the only file in the directory. 


Expand module used to be available as a light bulb everywhere in file, but I've changed it because it really got in the way: you seldom want to change module structure, so you don't want this intention to be always available and to hide more context specific ones. 

Though I think that "expand module" should always be available via find action. Will look into this. 

[here]: https://github.com/intellij-rust/intellij-rust.github.io/pull/6/files#diff-cac79fcf0c44be7a3718e6fb6257fb5fR70

**Comment by kryptan** [comment]
Thanks for clarifications. Contract module does indeed work.

> Expand module currently only available as a quick fix for unresolved module. That is, if you type mod quux; in foo.rs, a red squiggly and light bulb will appear.

Website and new docs that you linked mention two actions: "Expand module" and "Create module file". What you describe here sounds like "Create module file" while functionality of "Expand module" doesn't seem to be available. Is this correct?

**Comment by matklad** [comment]
There are two actions, "expand module" and "create module file", which are available as a quick fix for unresolved modlule

```
// directory structure
/src/foo.rs

// foo.rs
mod bar;
```

One <kbd>Alt+Enter</kbd>:

```
// directory structure
/src/foo/mod.rs

// foo/mod.rs
mod bar;
```

Second <kbd>Alt+Enter</kbd>

```
// directory structure
/src/foo/mod.rs
/src/foo/bar.rs

// foo/mod.rs
mod bar;

// foo/bar.rs is empty
```


Hm, now that I think of it, it seems pretty stupid to have to <kbd>Alt+Enter</kbd> twice... The correct UI would be:

* contract module is an intention with the light bulb, available only for module without children.
* expand module is an action without light bulb, available for any file except crate roots and mod.rs.
* quick fix for mod decl should simultaneously expand and create a file.

**Comment by kryptan** [comment]
Thanks again, now I finally got it.

**Comment by jajakobyly** [comment]
TIL: `<kbd>` works on GitHub

**Comment by matklad** [comment]
>TIL: <kbd> works on GitHub

The same here <kbd>:grinning:</kbd>

**Comment by jajakobyly** [comment]
<kbd><kbd><kbd><kbd>:smile:</kbd></kbd></kbd></kbd>
