### ISSUE TITLE
CLion doesn't recognize types (generated at build-time)

### ISSUE THREAD

**Issue by Ygg01** [intellij-rust/intellij-rust#5389]
## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-201-stable
* **Rust toolchain version:** 1.43.1 (8d69840ab 2020-05-04) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.1.1 (CL-201.7223.86)
* **Operating system:** Windows 10 10.0

## Problem description
Rust plugin doesn't correctly deal with types generated at build times.  In this case
For example in [html5ever/markup5ever/interface/mod.rs#17](https://github.com/servo/html5ever/blob/3e9fe2258fc6638902378375283a357514001327/markup5ever/interface/mod.rs#L168), CLion keeps offering to import `std::path::Prefix` even though Prefix is already added as `super::Prefix`. In Visual Code where Rust Analysis is used, there is no error and no solution is needed.

##  Steps to reproduce

1. Import html5ever project.
2. Build html5ever project using `cargo build --all`
3. Go to html5ever/markup5ever/interface/mod.rs#line17
4. Notice error

Expected result - no error.

**Comment by Undin** [comment]
> Rust plugin doesn't correctly deal with types generated at build times. 

By default, the plugin doesn't know location of `OUT_DIR` env variable value. It leads to unknown name for name resolution mechanism.
Try to enable `org.rust.cargo.evaluate.build.scripts` experimental feature (`Help | Find Action` and type `Experimental Features`). After that, each import of project data from Cargo (aka Cargo refresh) will launch `cargo check` to extract `OUT_DIR` for each crate. See #4734 for more details
Note:
- it may significantly increase time of Cargo refresh operation
- there is #5016 that leads to error during Cargo refresh if you have compilation error. It's already fixed in nightly and will be landed with stable release next week

**Comment by Ygg01** [comment]
Thanks, enabling these features and a IDE restart solved the issue.
