### ISSUE TITLE
Think about macro call matching

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#545]
Macro expansion consists of two steps:
- first we need to **match** macro arguments against a set of templates.
- then we need to **expand** the matched template. 

Template arguments specify the type of syntatic element that can be matched:

```
* ident: an identifier. Examples: x; foo.
* path: a qualified name. Example: T::SpecialA.
* expr: an expression. Examples: 2 + 2; if true { 1 } else { 2 }; f(42).
* ty: a type. Examples: i32; Vec<(char, String)>; &T.
* pat: a pattern. Examples: Some(t); (17, 'a'); _.
* stmt: a single statement. Example: let x = 3.
* block: a brace-delimited sequence of statements and optionally an expression. Example: { log(error, "hi"); return 12; }.
* item: an item. Examples: fn foo() { }; struct Bar;.
* meta: a "meta item", as found in attributes. Example: cfg(target_os = "windows").
* tt: a single token tree.
```

https://doc.rust-lang.org/book/macros.html#syntactic-requirements

Would be nice to implement **match** step, because we will be able to do proper highlighting then, eg

``` Rust
macro_rules! id {
    ( $e:expr ) => { $e }
}

fn foo() {}

fn main() {
    id!( foo() ); // <- need to highlight and resolve this call
}

```

**Comment by jajakobyly** [comment]
If I recall correctly, scala plugin had some kind of support of macros [link](https://blog.jetbrains.com/scala/2015/10/14/intellij-api-to-build-scala-macros-support/), though what this link shows is not what we need especially.

I think some kind of parser hacks (similar technique to infamous lexer hacks in C++ compilers, but applied on different layer) is needed, but there is one big problem here: the order in which files are parsed is non-deterministic.

On the other hand, it should be pretty fun & probably relatively easy to dynamically build custom parsers - `PsiBuilder` consumers. I could happily take on this :smile: 

So my idea for solution for this problem is:

 - Store collection of known macros globally per cargo project
 - During parsing of file:
    - When we meet macro definition, build it's invocations parser and store it in our collection
    - When we meet macro invocation:
        - If the macro is already present in the store, run stored parser
        - Otherwise, we need to leave a mark, that current file will have to be reparsed after indexing is finished
 - After indexing, rerun it for marked files

Problems:
 - How to handle marking of files and forcing reindexing if such files?
 - What about external macros? I don't know how rust stores them.

**Comment by matklad** [comment]
Another approach would be to leverage language injection infrastructure. That is, you don't replace token trees with actual parse trees, but use a different layer for them.

**Comment by farodin91** [comment]
I like to start working on better parsing macros.

**Comment by farodin91** [comment]
I had the idea to use `libmacro` to expand the macros. This approach would also support new macro by example and proc macros.

**Comment by farodin91** [comment]
@matklad What do you think from my approach?
