### ISSUE TITLE
#-prefixed lines are not shown in example doc section on tooltip 

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#5631]
On this code https://github.com/dtolnay/anyhow/blob/master/src/lib.rs#L381-L430 the tooltip is as following:

![image](https://user-images.githubusercontent.com/873919/85303210-e22d0100-b4b2-11ea-8030-57248017964b.png)

0.2.125.3175-202-nightly

CLion 2020.2 EAP
Build #CL-202.5792.50, built on June 19, 2020
CLion EAP User
Expiration date: July 19, 2020
Runtime version: 11.0.7+10-b944.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=580
Non-Bundled Plugins: org.jetbrains.plugins.rest, org.toml.lang, org.rust.lang, com.intellij.clion-swift

**Comment by Undin** [comment]
It's definitely a bug but expected behavior is not to show all code after `#` in quick documentation because it's a special notation in rustdocs to skip code while rendering
For example, see the corresponding [rendered documentation](https://docs.rs/anyhow/1.0.31/anyhow/type.Result.html#example) on docs.rs
