### ISSUE TITLE
`extern` exports of std suggested before std

### ISSUE THREAD

**Issue by DomWilliams0** [intellij-rust/intellij-rust#5654]
Often when implementing a std trait like `Display`, the import suggestions will include other crates that reexport std/core, and then automatically use them instead of the original `std`.

For example, `bumpalo::core_alloc::fmt::Formatter` and `smallvec::alloc::fmt::Formatter` are suggested above `std::fmt::Formatter` (alphabetical ordering I suppose?)

A solution I suggest would be "demoting" suggestions from `pub extern crate ...` reexports, either suggesting them at the end of the list or not at all unless specified in an option.

Another solution could be to allow the blacklisting of import suggestions from specified module prefixes, [like how IntelliJ does for Java imports](https://blog.jetbrains.com/idea/2009/03/excluding-classes-from-auto-import/). e.g. blacklist `smallvec::alloc::*`.

Cheers!

**Comment by tjg1** [comment]
This is really annoying when using the [tracing](https://crates.io/crates/tracing) crate, which re-exports all of the parts of `std` it uses. 

Auto-expansion will always prefer `tracing::stdlib` over `std`, which is actually a private module. 

This makes it seem more like a bug to me.

**Comment by Dessix** [comment]
This is partially equivalent to #5997 and #6399 in that a re-export is picked ahead of the original, but disparate in that those two issues include the specific nuance of the referenced module being inaccessible due to being `private` or `pub(crate)`.

I suspect we have two steps to solve these:
- For reexports, check that the original path is available and not a child of the parent module before assigning precedence (rules need work), which will be sufficient to fix this issue
- Do not walk inaccessible crates; Simply hiding them wastes an opportunity for a performance gain of not indexing them at all, since many reexports are very large (e.g. "all of `std`")
