### ISSUE TITLE
Make list of project templates extendable

### ISSUE THREAD

**Issue by nexoscp** [intellij-rust/intellij-rust#5916]
The list of project templates is hard coded and no way provided to extend by another plugin:

https://github.com/intellij-rust/intellij-rust/blob/d5bc6f95722410580bd730ab81fd65bfd9ec3602/src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt#L46

IntelliJ plugin.xml provides a way to register project templates: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000500010-Including-ProjectTemplate-in-a-plugin

Not sure how to build the ui from this.

THX

**Comment by Undin** [comment]
@nexoscp Thanks for your suggestion!
What template do you want to provide via another plugin?
In general, it's possible but I'm not sure that it's a good idea because in this case, we will have to keep backward compatibility for this extension that can be complicated sometimes (and it's quite hard to verify). Additionally, we try to publish new stable plugin builds each 2 weeks. In combination with the [impossibility] (https://youtrack.jetbrains.com/issue/IDEABKL-7906) to specify plugin dependency version, it may lead to a lot of `NoSuchMethodErrors`
Note, we've just merged https://github.com/intellij-rust/intellij-rust/pull/5845 to allow a user to add custom project template via UI

**Comment by nexoscp** [comment]
My use case is to make rust embedded development really easy: dependent on the microcontroller board plugged in, generate a proper project. Maybe some blinking lights or so. Setting up all cargo plugins. Wire the debugger. Having a structured view of logs from the board. ...
Indeed not easy, that's way i opened this issue instead of an pr.
 #5845 is nice, but not enough to support my use case.
THX

**Comment by Undin** [comment]
@nexoscp You can create and register your own project generator to provide a similar settings panel for new project creation.
See [RsDirectoryProjectGenerator](https://github.com/intellij-rust/intellij-rust/blob/d8b18f7b954a449b3006fa38badf235fbb231bec/src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt#L25) and related code as example
Note, it will work only in minor IDEs (all JetBrains IDEs except IntelliJ IDEA)

**Comment by Undin** [comment]
I think it can be closed
