### ISSUE TITLE
`i32` doesn't implement `Display` (required by {})

### ISSUE THREAD

**Issue by MichalMichalak** [intellij-rust/intellij-rust#5948]
## Environment

* **IntelliJ Rust plugin version:** 0.3.128.3278-202
* **Rust toolchain version:** stable-x86_64-apple-darwin (default) / rustc 1.45.2 (d3fb005a3 2020-07-31)
* **IDE name and version:** IntelliJ IDEA 2020.2 (Community Edition) / Build #IC-202.6397.94, built on July 27, 2020
* **Operating system:** MacOS 10.15.6

## Problem description
Example compiles and runs fine but IDE shows error:

    `i32` doesn't implement `Display` (required by {})

## Steps to reproduce
```rust
fn show_one() {
    let i: i32 = 1;
    println!("{}", i);
}
```
In line 3, `i` is underlined with red marker and above mentioned message appears on mouse hover.

**Comment by rschristian** [comment]
Just ran across this error myself, can reproduce.

**Comment by MaximeCouasnon** [comment]
I had this strange bug too, now it seems to have disappeared since I installed rust nightly.

I ran `rustup toolchain install nightly-x86_64-unknown-linux-gnu`
Then when I restarted PhpStorm: the bug disappeared.

I don't know...

**Comment by MichalMichalak** [comment]
Not an issue anymore.

**Comment by U007D** [comment]
I'm getting it today (with `u32`).
```
CLion 2022.1
Build #CL-221.5080.224, built on April 13, 2022
Runtime version: 11.0.14.1+1-b2043.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 12
Registry:
    run.processes.with.pty=TRUE

Non-Bundled Plugins:
    org.rust.lang (0.4.169.4584-221)
```
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
``
![Screen Shot 2022-04-26 at 6 25 48 AM](https://user-images.githubusercontent.com/2874989/165310921-c965daeb-ea66-4c90-8a02-8230579f72c1.png)
`

**Comment by afetisov** [comment]
I did some troubleshooting, and it seems like the bug happens only when two conditions are true:

1. The "Settings > Languages & Frameworks > Rust > Expand macros > Use new engine" option is enabled.
2. The "Experimental features > org.rust.macros.new.engine" option is disabled.

Using the old macro expansion, or enabling both the feature and the new macro expansion seem to remove the error (though I don't know whether that is because the Display impl is found correctly, or just because the error is silenced; I believe the old macro expansion hardcodes many impls for stdlib types).

@Undin Is there a reason the org.rust.macros.new.engine is still present? I thought it should have been removed when the new expansion engine was stabilised. I also wonder whether all other features are necessary, they seem to exist for ages and don't cause any apparent problems, but the absence of things like build script evaluation may very well do.

**Comment by vlad20012** [comment]
I removed the experimental feature in #8795. 
(but to be honest I have no idea how that feature could affect anything; it only specifies the settings default)

**Comment by afetisov** [comment]
Honestly, no idea. The impl Display for {integer} are defined within a cfg-gated macro:

```rust
#[cfg(any(target_pointer_width = "64", target_arch = "wasm32"))]
mod imp {
    use super::*;
    impl_Display!(
        i8, u8, i16, u16, i32, u32, i64, u64, usize, isize
            as u64 via to_u64 named fmt_u64
    );
    impl_Exp!(
        i8, u8, i16, u16, i32, u32, i64, u64, usize, isize
            as u64 via to_u64 named exp_u64
    );
}

#[cfg(not(any(target_pointer_width = "64", target_arch = "wasm32")))]
mod imp {
    use super::*;
    impl_Display!(i8, u8, i16, u16, i32, u32, isize, usize as u32 via to_u32 named fmt_u32);
    impl_Display!(i64, u64 as u64 via to_u64 named fmt_u64);
    impl_Exp!(i8, u8, i16, u16, i32, u32, isize, usize as u32 via to_u32 named exp_u32);
    impl_Exp!(i64, u64 as u64 via to_u64 named exp_u64);
}
```

I would expect the fail to be related either to a failure in macro expansion, or to a failure in cfg condition evaluation (so that neither or both impls are present at the same time). This would mean that the failure should be related either to "evaluate build scripts" or "fetch actual stdlib metadata" features. But in my mucking around it was linked to the "new engine". Maybe I had some cache issue?

**Comment by vlad20012** [comment]
> Maybe I had some cache issue?

Well, yes, I think it's the the most likely reason, but I have no idea how we come to this. 

Btw the macro expansion was rewritten almost entirely in #8647 (released in 0.4.168 plugin), so the current issue may be of a different nature than the old issues like this.

**Comment by vlad20012** [comment]
@U007D Could you please press `Cmd + Shift + A`, then type "Invalidate Caches ...", then check "Clear file system cache and Local History" and press "Invalidate and Restart" button. 

If the error still persists, could you please attach your IDE logs? You can do it by `Help` | `Collect Logs and Diagnostic Data`

**Comment by sagacity** [comment]
FYI, this happened to me today when upgrading from the previous to the current version (0.4.176.4815-222). Using the "Clear file system cache..." option solved it.
