### ISSUE TITLE
false "argument never used" in some format strings generated by macros

### ISSUE THREAD

**Issue by notviri** [intellij-rust/intellij-rust#5994]
## Environment

* **IntelliJ Rust plugin version:** The latest one! I updated 5 minutes ago.
* **Rust toolchain version:** 1.45.2 stable
* **IDE name and version:** CLion 2020.2

## Problem Description
I often break up big format strings with `concat!` over multiple lines, unfortunately, the plugin does not seem to be able to recognize the arguments that are not in the first string passed to the macro which it at least correctly picks up. Similarly, it also can't tell when there's too many arguments if they aren't in the first input.

## Steps To Reproduce
The problem is observable in a simple use case:

![image](https://user-images.githubusercontent.com/30309547/91152010-a44b8500-e67b-11ea-94b6-c78478613c75.png)
![image](https://user-images.githubusercontent.com/30309547/91152286-04dac200-e67c-11ea-89a7-d35d1d567e13.png)

## Additional Info
This check doesn't seem to happen if I write my own (useless) wrapper for `concat!` even if the macro inputs are identical so perhaps this is a special case? Doesn't seem to work as intended, though.

![image](https://user-images.githubusercontent.com/30309547/91154786-2a1cff80-e67f-11ea-919d-ffe52ce75690.png)

**Comment by Kobzol** [comment]
The `concat!` macro is one of a few special macros that are not opaque to the plugin, therefore we understand its first argument and incorrectly consider it to be the format string.

I started implementing support for the concat macro (basically treat all of its concatenated arguments as the format string), which would work for marking erroneous format arguments. But then I realized that it will not work with highlighting, as the current code does not support multiple string literals and it's probably not worth it to add this quite large complexity because of the `concat!` macro. Therefore I will probably just disable the inspection if the first argument is not a simple string literal. @Undin do you agree?

**Comment by Undin** [comment]
> Therefore I will probably just disable the inspection if the first argument is not a simple string literal.

@Kobzol yep, I think it's good and simplest solution atm. In future, we can try to expand any expr macro (including `concat` one) to string literal and provide the same error handling as for simple string literals.

**Comment by Kobzol** [comment]
Error handling would be relatively simple to add even now, the problem is with highlighting, when you have something like this:
`println!(concat("{}", "{}", "{}"), 1, 2, 3);` the highlight would have to span 3 different literals. It could be done, but I'm not sure if it wouldn't be confusing for the user. Maybe we can add it later.
