### ISSUE TITLE
"Run rustfmt on Save" only works with ctrl-s

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#6021]
Now `Run rustfmt on Save` only works with ctrl-s.
However, since most the time files in JetBrain IDEs are auto-saved, formatting on ctrl-s is neither elegant nor convenient with that.

Here's a work around, but it's what `Run rustfmt on Save` should have done.
https://stackoverflow.com/questions/59512214/execute-rustfmt-on-file-save-in-intellij-or-clion

**Comment by vlad20012** [comment]
Do you also use `Run external linter on the fly`, right?

**Comment by qiujiangkun** [comment]
> Do you also use `Run external linter on the fly`, right?

No. But whether yes or no, it behaves the same. Does it have something to do this this issue?

**Comment by vlad20012** [comment]
Well, I don't understand the issue... 
I just checked: `rustfmt` is launched on every file save, not only ctrl+s. For example, window unfocusing also triggers the save. Maybe the problem is that IDEA usually just don't save anything? So... please, describe what exactly you expect from the feature and what goes wrong from your PoV.

(it can work a bit differently (in a bad way) with `Run external linter on the fly`, but it's not your case)

**Comment by qiujiangkun** [comment]
Tab unfocusing does not trigger rustfmt. Isn't it time to save in IDEA? I'm mistaken here

**Comment by Undin** [comment]
No. You should unfocus IDE window to trigger implicit save
