### ISSUE TITLE
"Substitute associated type" intention works for regular type aliases

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#6030]
## Environment

* **IntelliJ Rust plugin version:** 0.3.130.3315-202-nightly
* **Rust toolchain version:** 1.46.0 (04488afe3 2020-08-24) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2020.2.1 Ultimate Edition (IU-202.6948.69)
* **Operating system:** Linux 5.4.0-42-generic

## Steps to reproduce
```rust
type T = i32;

fn main() {
    let a: T = 1;
}
```

![image](https://user-images.githubusercontent.com/3221931/91660007-0ffa7b80-eadc-11ea-87ed-e85bb627347e.png)

Possible fixes:
1. Restrict it to associated types only
2. Rename it to something like `Substitute type alias` because the intention is also good in this.

Found the bug during @Kobzol's [blog post](https://kobzol.github.io/rust/intellij/2020/08/25/contributing-2-subst-assoc-type-int.html) reading.

**Comment by Kobzol** [comment]
After I finished writing the post, I realized this and also that the intention is pretty broken for type aliases :D I tried to fix it, but it would require support of aliases for non-adt types to work properly. So for now I'll just disable it for type aliases.

**Comment by Kobzol** [comment]
@vlad20012 btw, how difficult would it be to support type aliases properly also for non-ADT types? Could I try to with some mentoring or is too complex?

**Comment by vlad20012** [comment]
Well, it would be complex only for numeric types (i.e. `type T = i32;`), but only because of our singleton-based design of numeric types. For other types it looks simple: `TyAdt.withAlias` and `TyAdt.aliasedBy` should just be propagated to the base `Ty` class (with default implementations returning `null` and `self` respectively) and then some boilerplate code should be added each `Ty*` class (`override val aliasedBy` and `withAlias` returning `copy(aliasedBy = aliasedBy)`). Sounds relatively simple... if we ignore numeric types 😅

**Comment by Kobzol** [comment]
@vlad20012 The problem with type singletons could be solved by inverting the API:
```rust
type Alias = u32;
```
(`u32.aliasedBy: Alias` would change to `Alias.aliases: u32`). But I suppose that would require manual check of the `aliases` property in pretty much all places that use types?

**Comment by vlad20012** [comment]
I think I don't understand your proposal... Could you please explain in more detail?

(note that current users of `aliasedBy` know nothing about possible aliases, it's e.g. type hint providers that just know `Ty` and want to render it)

**Comment by Kobzol** [comment]
First I'll try to describe what problems I had when trying to implement the "Inline type aliases" extension of the intention, so that I don't forget it, and maybe you can spot something that I was doing wrong.
If I have something like this:
```rust
struct S<X>(X);
type T1<X> = S<X>;
type T2<X> = T1<X>;
fn foo(x: T2<u32>) {}
```
`x: T2` has a `RsTypeReference`, let's say that I want to inline the type alias `x: T2`. Here are some problems that I found:
1) The `type` (`inferTypeReferenceType()`) of the `RsTypeReference` infers and goes through type aliases eagerly, so it returns me `S`. I can't parametrize the `type` inference property, so it doesn't allow me to (for example) stop at the first type alias, if I didn't want the inlining to be recursive. And if I'm not mistaken, `T1<u32>` cannot be represented as a proper `Ty` at this moment.
I could probably walk back from `S`, but I didn't find an easy way to go from `T1` to `T2`, I would have to manually check at which type alias to stop and this currently only works for ADTs anyway. Of course there are other ways of getting the aliased type other than using type inference, I could just resolve `T2` to the type alias and replace it with `T1` as text, but then generic substitutions will not work. If we didn't want an option to disable "recursive" inlining, I think that the actual infrastructure is OK for inlining type aliases in type context.
2) If I'm in an expression context (`Alias::<u32>::method()`), the situation is worse. There's no type reference, so I have to manually build the correct type from the corresponding path and match its type arguments with the type parameters of the target type (unless I miss some easy way to do this?). Also sometimes the type cannot be substituted directly (for example `(u32, u32)` cannot be part of a path, so it needs to become a type qual `<(u32, u32)>`), thus replacing the path is tricky. I didn't finish this intention change because I didn't know how to properly support aliases in expression context.

So actually the current type alias support should be more or less enough for this intention to work on regular type aliases, the question about adding more support for type aliases was orthogonal to this issue.

Regarding the proposal: I suppose that the problem with singleton types is that they do not have multiple instances, therefore you cannot have one `u32` that is `aliasedBy` Alias1 and another `u32` that is `aliasedBy` Alias2. You could instead get a special `Ty` for type aliases which would have an `aliasesTo` property, which would allow you to have aliases to primitive types. It would also be useful for "non-recursive" inlining. But I suppose that "stopping" at type aliases and not going through them implicitly e.g. in type inference would require users to manually check whether a type is an alias or not pretty much all over the plugin.

**Comment by vlad20012** [comment]
About "Inline type aliases", I think there is an approach that should work. In this example
```rust
struct S<X>(X);
type T1<X> = S<X>;
type T2<X> = T1<X>;
fn foo(x: T2<u32>) {}
```

we can look at `T2<u32>` as a path (not as a type). Then, resolve it using `reference.advancedResolve()` and find `type T2<X> = T1<X>;` and also a substitution `X => i32`. Then we can look at `type T2<X> = T1<X>`, take its typeReference (`T1<X>`) and use `RsTypeReference.getStubOnlyText()` utility on it, passing the substitution `X => i32` as an argument. We'll get string " T1<i32>". It looks like 1-level inlining.

> You could instead get a special Ty for type aliases

Am I understand right that you propose to create a new `TyAlias` that wraps any other type? Hmm, this could work. But it scares me that we will need to unwrap these types all the time we need a real type. Sounds bug-prone. But, well, we already have a similar concept - `RsParenType`, we unwrap it all the time, and it works. So, maybe it's not a big issue. But to be honest, ridding of singleton-based numerics is not a big issue too. We should just... get rid of it =D. Sounds not too complex.

**Comment by Kobzol** [comment]
`TyAlias` is exactly what I meant, but it would need changes all over the plugin probably, as its not very transparent, we would need to think about it everytime when working with types. It could improve handling of aliases, as they would need to be taken into account, but I'm not sure if it's worth it.
