### ISSUE TITLE
"Debug toolchain is not configured" when debugging in CLion

### ISSUE THREAD

**Issue by AndreKR** [intellij-rust/intellij-rust#6070]
## Environment

* **IntelliJ Rust plugin version:** 0.3.131.3329-202-nightly
* **Rust toolchain version:** nightly-x86_64-pc-windows-gnu unchanged - rustc 1.45.0-nightly (f8d394e51 2020-05-05)
* **IDE name and version:** CLion 2020.2.1
* **Operating system:** Windows 7

## Problem description

Previously I could simply debug my application by setting a breakpoint and clicking the "bug" button. Since some update this doesn't seem to work anymore. When I now click the bug button I get an error message "Debug toolchain is not configured". Then it takes me to the settings dialog where I can choose between adding a MinGW, Cygwin, Visual Studio or Remote Host toolchain. No idea what to choose (MinGW I guess?) and what to put in "Environment", which seems to be a required setting.

**Comment by ortem** [comment]
@AndreKR Since you're using `x86_64-pc-windows-gnu` [Rust toolchain](https://rust-lang.github.io/rustup/concepts/toolchains.html), you should install and configure 64-bit MinGW or Cygwin [CLion environment](https://www.jetbrains.com/help/clion/toolchains.html#1a906f) to debug your code. There is a [tutorial](https://www.jetbrains.com/help/clion/quick-tutorial-on-configuring-clion-on-windows.html) that might help you. Please feel free to ask any further questions here.

**Comment by AndreKR** [comment]
I'm confused. Didn't rustup install that for me? I don't remember installing MinGW and Rust works just fine, as it should. I also have MSYS2 on my machine, maybe it's stealing something from there?

I tried putting the parent of the `bin` folder that rustup installed as "Environment", but that gives me an error message:

![image](https://user-images.githubusercontent.com/1188538/92384979-56ba2800-f111-11ea-86b9-70a48163e97a.png)

**Comment by ortem** [comment]
@AndreKR CLion uses GDB from MinGW/Cygwin to debug 64-bit code, and that's why we recommend installing one of them. AFAIK `rustup` doesn't install debuggers (but installs linker). CLion's bundled GDB [is currently](https://youtrack.jetbrains.com/issue/CPP-16363) only for 32-bit code, so it will not work in your case. If installing MinGW/Cygwin is undesirable, you can try using bundled LLDB with an unconfigured MinGW environment (like on your screenshot).

**Comment by AndreKR** [comment]
>  If installing MinGW/Cygwin is undesirable

It's fine, just unexpected that I need to install a *second* MinGW environment in an arbitrary folder, just to get the debugger. Without you telling me clearly I need to do that I would have assumed I'm doing something wrong.

One thing I don't understand yet. I'm 100% sure that half a year ago I was using exactly the same `nightly-x86_64-pc-windows-gnu` Rust toolchain just with an older CLion and an older IntelliJ Rust plugin and I was able to debug just fine, why/how was that?

**Comment by AndreKR** [comment]
Ok, and the next problem: The link "MinGW-W64" from the tutorial leads to a website and it's unclear what to download.

**Comment by ortem** [comment]
> I was able to debug just fine, why/how was that?

I don't know, probably you used an unconfigured MinGW environment with bundled LLDB

> But when I start debugging I get [GDBCommandException]

Looks like you've selected the wrong `i686` architecture during installation. Try to reinstall MinGW. It should looks like this:
<img width="527" alt="Screenshot 2020-09-08 at 13 06 12" src="https://user-images.githubusercontent.com/4854600/92463364-6189c100-f1d4-11ea-8765-965d8d5ac533.png">
<img width="594" alt="Screenshot 2020-09-08 at 13 06 59" src="https://user-images.githubusercontent.com/4854600/92463369-63538480-f1d4-11ea-9823-adfdd0daca9d.png">

**Comment by AndreKR** [comment]
> I don't know, probably you used an unconfigured MinGW environment with bundled LLDB

It's actually possible that I had an old MinGW environment configured in CLion. Since only gdb.exe is needed and it needs no connection with my Rust environment, that seems like a distinct possibility.

> Looks like you've selected the wrong i686 architecture during installation. Try to reinstall MinGW.

I actually saw that and wondered "what a weird architecture" but I assumed it's a sane default. I was installing MinGW-w**64** after all.

Reinstalled MinGW with the correct architecture and it works now. :partying_face:
