### ISSUE TITLE
Highlight code fences in doc comments

### ISSUE THREAD

**Issue by mkaput** [intellij-rust/intellij-rust#618]
Highlight code fences with Rust source code in doc comments (lexer highlighting is enough), like @wilfred does in Emacs ([tweet](https://twitter.com/_wilfredh/status/767457636820234240)):

![cqaoeblw8ai8rj0 png large](https://cloud.githubusercontent.com/assets/3450050/17884482/d58e50fa-6918-11e6-9e3e-18075a814811.png)

I'm not 100% sure, but separating token types for code fence contents ~~and then layering Rust highlighting lexer over them should do~~. Remember that code fences can have language specifier.

The other solution could be to use language injection (@matklad's idea) - actually might be better.

Related source files:
- Documentation comments [lexer](https://github.com/intellij-rust/intellij-rust/tree/master/src/main/kotlin/org/rust/lang/doc/lexer), [token types](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/java/org/rust/lang/doc/psi/RustDocElementTypes.java)
- [Highlighter](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/highlight/RustHighlighter.kt)

**Comment by matklad** [comment]
I think this can be done via language injection

**Comment by zjhmale** [comment]
vote for language injection

**Comment by zjhmale** [comment]
@matklad @mkaput i think the best way is to follow `PyDocstringLanguageInjector`?

[Injector](https://github.com/JetBrains/intellij-community/blob/master/python/src/com/jetbrains/python/documentation/doctest/PyDocstringLanguageInjector.java), [FileType](https://github.com/JetBrains/intellij-community/blob/master/python/src/com/jetbrains/python/documentation/doctest/PyDocstringFileType.java), [DocstringDialect](https://github.com/JetBrains/intellij-community/blob/master/python/src/com/jetbrains/python/documentation/doctest/PyDocstringLanguageDialect.java)
 
there is a problem that since [RustLanguage](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/RustLanguage.kt) is an object so it is not inheritable.

and it is also confusing that there is no `PsiLanguageInjectionHost` implementation in current Rust PsiElements like [Go](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/grammars/go.bnf#L305) and [Erlang](https://github.com/ignatov/intellij-erlang/blob/master/grammars/erlang.bnf#L581), but we can still inject Rust code in doc comments although it will produce syntax error currently.

![2016-08-23 8 21 40](https://cloud.githubusercontent.com/assets/6234553/17891571/512b8506-696f-11e6-82e7-1b3905e83c57.png)

![image](https://cloud.githubusercontent.com/assets/6234553/17891638/bb0d27ae-696f-11e6-9206-7e3edf78b817.png)

**Comment by mkaput** [comment]
`PsiLanguageInjectionHost` has to be implemented anyway to support injecting in string literals from what I know

**Comment by zjhmale** [comment]
@mkaput yeah, the statement is [here](https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/psi/PsiLanguageInjectionHost.java#L36), but here is PsiComment so it is still confusing 😂 

![psicomment](https://cloud.githubusercontent.com/assets/6234553/17894413/d820da64-697b-11e6-89ee-b36e6c25a3b2.png)

**Comment by johnthagen** [comment]
It would be great if it not only highlighted it, but also linted it like normal code as well.

Many times these fenced code blocks are used as doc tests, so having these feature would improve writing doc tests **immensely** in IntelliJ. I believe language injection (recommended above) would allow this as I've seen other IntelliJ based products provide this can of injected linting before.
