### ISSUE TITLE
Getter for `String` should return `&String` and not `&str`

### ISSUE THREAD

**Issue by chinedufn** [intellij-rust/intellij-rust#6237]
Right now when generating a getter for a `String` field the signature is `fn my_field (&self) -> &str`.

It would be better (more use cases for the returned value) to do `fn my_field (&self) -> &String` since `&String` can deref to `&str`.

**Comment by Kobzol** [comment]
Hmm, to be honest, I'm not sure if I ever saw `&String` used as a return value "in the wild". Using `&str` provides a more future-proof API and mainly in my experience it is the more common option.

Do you have some use case where you need `&String`? I can't think of any use for that, as you said, `&String` can deref to `&str`, but what additional benefits do you gets from returning `&String`?

**Comment by chinedufn** [comment]
Hey!

I would question whether `&str` is the more common option for returning a reference to a `String`.

If this is indeed true, that would mean that it is common for code to intentionally force unnecessary allocations (if you really ned an `&String` you now need to allocate), which is wasteful.

Maybe you are thinking of function arguments? i.e. `fn foo (arg: &str)` is better because anything that derefs to `&str` can be used. So it would be more flexible to use `&str` as an argument.

Where as using `-> &str` as a return value is less flexible.

I'm not too sure about what you mean by more future proof?

---

Sure, here's one example of where losing the `&String` would hurt.

```rust
#[derive(Default())]
struct Neighbors {
  neighbor_1: String,
  neighbor_2: String
}

fn neighbor_ages () -> HashMap<String, u32> { unimplemented!() }

impl Neighbors {
  fn neighbor_1 (&self) -> &str {
    &self.neighbor_1
  }
}

fn main () {
  let all_neighbors = neighbor_ages();
  
  let n = Neighbors::default();

  // Unnecessary allocation forced by the unnecessary `&str` return
  all_neighbors.get(&n.neighbor_1().to_string());
}
```

In the above example we are trying to use our `String` as a key into a HashMap that has `String` keys.

We can't, though, since we only have an `&str`.

So we are forced to allocate.

---

This is just one example - but my general thinking is that there are zero tangible benefits to returning a less flexible type both here and in general.

---

Thank you for your help!! Please let me know if I am missing something!

Your thoughts?

**Comment by Kobzol** [comment]
`&str` can be used to index a `HashMap<String, ...>`, because `String` implements `Borrow<&str>`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=86163d8c764087d569f023cd3f00a4ce.

I don't see any benefits in terms of allocation for `&String`. You cannot mutate `&String` and because function parameters almost always expect `&str` (or a generic type expects `Borrow<&str>`, as is the case with `HashMap`), having `&str` is enough. And if you need to copy the string, having `&String` will not help with anything.

By future-proofing I meant that if you change the representation of the string from `String` to something else that can also give out references to `&str` (like `Cow<str>`), you will not have to change the users of the method if it uses `&str` instead of `&String`.

**Comment by chinedufn** [comment]
Ah I did not know that `K: Borrow<Q>` for the std HashMap.

I'm all good then, thanks!
