### ISSUE TITLE
Code analysis never finishes on some projects (because of cross-compiling?

### ISSUE THREAD

**Issue by wolverian** [intellij-rust/intellij-rust#6240]
## Environment

* **IntelliJ Rust plugin version:** 0.3.132.3395-203
* **Rust toolchain version:** rustc 1.49.0-nightly (b1af43bc6 2020-10-10) cargo 1.48.0-nightly (9d1a4863a 2020-10-05)
* **IDE name and version:** IntelliJ IDEA 2020.3 EAP (Ultimate Edition) Build #IU-203.4449.2, built on October 6, 2020
* **Operating system:** macOS Catalina (10.15.7)

## Problem description

On some projects, in particular https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials, code analysis never finishes and the IDE doesn't give any, well, IDE functionality.

## Steps to reproduce

1. Clone https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials
2. Open the subdirectory `01_wait_forever` in IDEA.
3. Open `src/main.rs`
4. Wait for code analysis to complete (it never does)

There are no errors in the event log.

**Comment by Undin** [comment]
@wolverian I suppose it's a duplicate of #6225
You can check your log (`Help | Show log in Finder` action may help) if it contains `java.lang.NoSuchMethodError: 'void com.intellij.util.containers.ConcurrentWeakKeySoftValueHashMap.<init>(int, float, int, gnu.trove.TObjectHashingStrategy)'`.
#6225 is already fixed. The fix is already in nightly builds (see [instruction](https://intellij-rust.github.io/install#nightly-builds) how to install it) and will be landed with stable build next week

**Comment by wolverian** [comment]
Yep, that looks to be it, thank you. I'll close this issue.
