### ISSUE TITLE
Unrecognized functions from packed_simd_2

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#6302]
## Environment

* **IntelliJ Rust plugin version:** 0.3.133.3426-202
* **Rust toolchain version:** 1.49
* **IDE name and version:** CLion 2020.2
* **Operating system:** Windows 10

## Problem description

Functions from the packed_simd_2 crate are marked as red, despite being imported.

## Steps to reproduce

```rust
use packed_simd_2::*;

let ones: f32x8 = [1f32; 8].into();
let twos: f32x8 = [2f32; 8].into();

// min is marked red
let result = ones.min(twos);
```

**Comment by Undin** [comment]
As I can see, `f32x8` is just a type alias to `Simd` type.
And `min` method is defined using `f32x8` type. Currently, the plugin has restricted support for `impl` blocks for type aliases. More precisely, the plugin doesn't process impls if there are more than `threshold` number of type aliases for a particular base type because of performance reasons. By default, `threshold` is 10. You can change it via `org.rust.lang.type.alias.threshold` key in `Registry` to, for example, `85` to make this case work.
Note, it may significantly affect the performance of type inference.
The restriction will be eliminated with [name resolution 2.0](https://github.com/intellij-rust/intellij-rust/issues/6217)
