### ISSUE TITLE
Can't find Rust language SDK

### ISSUE THREAD

**Issue by fungos** [intellij-rust/intellij-rust#633]
Hi,

I've saw others similar and solved issues about this, but none of the solutions worked here. This seems to be another factor causing the same problem again.

My fresh install can't find the Rust SDK even if the UI shows everything correctly set.
In File > Settings > Language & Frameworks > Rust I have:

![2016-08-26 15_53_02-settings](https://cloud.githubusercontent.com/assets/151544/18018514/73bfcd10-6ba5-11e6-9f3e-e22cc9c443a9.png)

The project is like this:

![2016-08-26 15_53_02-settings](https://cloud.githubusercontent.com/assets/151544/18018570/a7571548-6ba5-11e6-928d-2a6ec9071ea9.png)

But when I try to build it asks for a SDK:

![2016-08-26 15_53_02-settings](https://cloud.githubusercontent.com/assets/151544/18018693/45950f30-6ba6-11e6-93b4-a65be8926e45.png)

then:

![2016-08-26 15_53_02-settings](https://cloud.githubusercontent.com/assets/151544/18018717/7403e4fe-6ba6-11e6-86f1-89a0d62ee192.png)

Note also that I'm using Rustup and everything is accessible from PATH (rustup, cargo, rustc).

Any ideas?
Thanks

**Comment by matklad** [comment]
Hi! We don't use SDK interface at all in IntelliJ Rust, because it exists only in IDEA and is missing in, eg., CLion. 

To build the project you need to create a run configuration for `cargo build` command. Does this help?

**Comment by fungos** [comment]
Sure, I will try, thanks!

Now my 2cc: That is misleading on the IDEA side of intellij-rust. Maybe that should require some love as it is a roadblock in user adoption.
I really understand it, but from an adoption point of view (IDE and even for Rust as-is) it is not interesting. Some users will pay in usability because of another IDE. That said, if this worked out of box it would be really a incredible selling point of Rust (on tooling side) as for now, from the little I experimented with it, it seems the best integration I've used.

**Comment by matklad** [comment]
Yeah, we totally can have different implementations of SDK for IDEA and for other IDEs, and I think that we eventually will do just that, because it provides the best user experience, just as you say. 

We don't do it right now for two reasons: 

* there are a number of higher priority issues at the moment (we are pushing underling code analysis infrastructure and are a bit light on the UI work).

* rustup is not stable yet, but it should become the main interface for the rust toolchains. So it makes sense to wait for it to become stable before really nailing down the IDE side of things.
