### ISSUE TITLE
No colors from rustc/cargo

### ISSUE THREAD

**Issue by Streetwalrus** [intellij-rust/intellij-rust#646]
The run window doesn't show colored compiler output, even with `--color always`.

![](https://sr.ht/xNEw.png)

I've changed the stderr color, tried disabling it as well.
I'm running 0.0.1.955 in PyCharm Community 2016.2.2, rustc 1.11.0 and cargo 0.12.0.

My program is outputting colored text to stdout which works fine, if I output to stderr, it doesn't though.

**Comment by matklad** [comment]
Note to self:

On linux, add `.withRedirectErrorStream(true)` to `CargoRunState` and set `TERM=linux`. Not sure what should be done for windows though.

**Comment by alygin** [comment]
On Windows, `rustc` uses the Win console API to produce color output. The only exception is the msys terminal for which it emits ANSI escape codes, but unfortunately, it does it incorrectly.

**Comment by alygin** [comment]
Works fine on mac with the following settings in the `Cargo` class:

    .withEnvironment("TERM", "linux")
    .withEnvironment("RUSTFLAGS", "--color=always")
    .withRedirectErrorStream(true)

![image](https://cloud.githubusercontent.com/assets/2101250/19198379/8dc52c58-8cc7-11e6-9324-32821a149ea2.png)

On Windows, it should be `.withEnvironment("TERM", "msys")`, but it was broken [last time I tried to use it](https://github.com/AtomBuild/atom-build-cargo/issues/56).

**Comment by alygin** [comment]
@matklad, what do you think, should we use the colorful output only on linux and mac? Are there other platform-dependent features in the plugin?

**Comment by matklad** [comment]
Yep, I guess it is fine to set `TERM` on linux and to add `--color always` to the Cargo flags on linux. It'd be great to figure out how to do this on windows as well. 

However, we really should not use `RUSTFLAGS`, because they go into Cargo's fingerprints, and you might get some spurious recompilation. I remember an issue that Cargo should pass `--color` through to the compiler (Ah, I fixed it actually: https://github.com/rust-lang/cargo/pull/2779 :) )

The issues about windows: https://github.com/rust-lang/cargo/issues/3077, https://github.com/Stebalien/term/issues/58.

**Comment by sanmai-NL** [comment]
@matklad: `0.1.0.1259-nightly` now fails on my IntelliJ Run command since it appends `--color always` to the complete command line instead of to the `cargo` command parameters.

**Comment by alygin** [comment]
@sanmai-NL, please, have a look at a [possible workaround](https://github.com/intellij-rust/intellij-rust/issues/829#issuecomment-266302942).
