### ISSUE TITLE
In some debugging situations, it always stops before'macro_rules' instead of my breakpoint

### ISSUE THREAD

**Issue by tuanzijiang** [intellij-rust/intellij-rust#6477]
## Environment

* **IntelliJ Rust plugin version:** 0.3.136.3514-202
* **Rust toolchain version:**  1.45.0-nightly
* **IDE name and version:**  CLion 2020.2.5 Build #CL-202.8194.17, built on November 26, 2020
* **Operating system:** Windows10

## Problem description

In some debugging situations, it always stops before "macro_rules". It will not jump directly to my breakpoint. As follows:
![image](https://user-images.githubusercontent.com/26037690/101030247-3b49a680-35b4-11eb-86af-c014fc7c4a5c.png)

However, when I clear the line4~6 in test\mod.rs. It works fine. It jump to my breakpoint. As follows:
![image](https://user-images.githubusercontent.com/26037690/101031024-72b85300-35b4-11eb-9c4f-fdc91a428b21.png)

This is the code:
[test13.zip](https://github.com/intellij-rust/intellij-rust/files/5636621/test13.zip)

**Comment by jwiesler** [comment]
I thought so at first too, but the problem is a lot bigger. The debugger breaks at *every* file with the same name.
If i put a breakpoint in src/some_module/mod.rs, it breaks in *every* crate's mod.rs in the same line. If you open "View breakpoints", you can see that the IDE does not distinguish them at all and just adds a breakpoint for "mod.rs:line".

This is a big problem with env_logger, making it almost impossible to debug code in a mod.rs file of an application containing log statements.

**Comment by jwiesler** [comment]
This is actually the same problem as the 4 months old #6161.

**Comment by ortem** [comment]
Fixed since 2021.2, based on https://github.com/intellij-rust/intellij-rust/issues/6161#issuecomment-895794766
