### ISSUE TITLE
plugin not compatible with IntelliJ IDEA 2016.3 EAP

### ISSUE THREAD

**Issue by yanns** [intellij-rust/intellij-rust#648]
First thanks for this plugin!

With IntelliJ IDEA 2016.3 EAP, the plugin is not activated anymore.
I guess it is not compatible with that version.

**Comment by matklad** [comment]
Thanks for the report! Fixed in master, you can try this [this build](https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_Idea16_TestsRust_2/857877:id/intellij-rust-0.0.1.971.zip?guest=true) until the next nightly arrives. 

Keep in mind that it's only lightly tested though, unfortunately CI does not work with the CI at the moment :(
