### ISSUE TITLE
Incorrect detection of use of moved value

### ISSUE THREAD

**Issue by PizzaCrust** [intellij-rust/intellij-rust#6551]
## Environment

* **IntelliJ Rust plugin version:** 0.3.137.3543-203
* **Rust toolchain version:** 1.50.0-nightly (1c389ffef 2020-11-24) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2020.3 Community Edition (IC-203.5981.155)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
![image](https://user-images.githubusercontent.com/15954148/103035548-23a18480-459a-11eb-9bba-62a2d068ac5f.png)
The IDE says `Use of moved value` even though it compiles.

## Steps to reproduce
Place the aforementioned code in the editor

**Comment by MightyPork** [comment]
Possibly another case of the same bug:

![Screenshot_20210210_153127](https://user-images.githubusercontent.com/2041118/107523648-407b3100-6bb5-11eb-9a8a-846f2d58d1e2.png)

sample code (simplified)

```rust
use serde_json::Value;
use std::convert::TryFrom;
use std::borrow::Cow;
use serde::{Serialize,Deserialize};

#[derive(Debug,Clone,Serialize,Deserialize,Eq,PartialEq)]
struct OcppCall {
    message_id: String,
    action: String,
    payload: Value,
}

impl TryFrom<Value> for OcppCall {
    type Error = ();

    fn try_from(value: Value) -> Result<Self, ()> {
        let mut items : [Value; 4] = serde_json::from_value(value.clone()).unwrap();

        if let [
            Value::Number(n),
            Value::String(message_id), // warning
            Value::String(action), // warning
            payload @ Value::Object(_)
        ] = items {
            Ok(Self {
                message_id,
                action,
                payload
            })
        } else {
            Err(())
        }
    }
}
```

**Comment by ortem** [comment]
Thank you for reporting!

@PizzaCrust Please try executing `Re-Expand All Rust Macros` action, and then `Invalidate Caches` action if the first one doesn't help. Both actions can be invoked via `Ctrl+Shift+A` menu. Please feel free to ask any further questions and inform us if this approach works or not!

@MightyPork Your case is different from the original since it is steadily reproducible and probably caused by incorrect processing of slice patterns in IJ Rust code analysis. Please open a new issue using `Create New Issue` action (can be invoked via `Ctrl+Shift+A` menu as well).

**Comment by Undin** [comment]
I've created #6826

**Comment by ortem** [comment]
@Undin Thanks! In fact, I asked for opening a new issue only to know the exact IJ Rust version since I haven't managed to reproduce the bug on my environment. Now I know the environment so I'll investigate the problem in more details 👌

**Comment by PizzaCrust** [comment]
It seems to be fixed for me, thanks!
