### ISSUE TITLE
Move refactor should create file if it doesn't exist

### ISSUE THREAD

**Issue by sirgl** [intellij-rust/intellij-rust#6584]
Now if you try to move to non-existent file refactoring gives an error, while it could create it for me.
I think it is pretty common use case (actually, most of the time I use it to extract parts of module to separate one).
![2020-12-29_23-32](https://user-images.githubusercontent.com/11944514/103318294-4aded280-4a2e-11eb-8e25-483d6e0aa5d4.png)

## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.50.0-nightly (fa4163942 2020-12-14) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3 (CL-203.5981.166)
* **Operating system:** Linux 5.4.0-58-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

**Comment by ortem** [comment]
I think there could be a separate action (~ "Extract Module") with a more clear UI. Since it's not obvious that a **non-existing path** may be used in the general Move Refactoring UI.

Also, currently, if I manually create an empty new file `move_to.rs` just alongside the existing file `move_from.rs` **but** forget to manually include `move_to.rs` in `move_from.rs` before moving, the Move Refactoring will think that I want to move the items outside of the current crate (technically, that's right, but I don't mean that) and produce unexpected code.
