### ISSUE TITLE
IDE becomes temporarily unresponsive after running a Tokio test

### ISSUE THREAD

**Issue by PizzaCrust** [intellij-rust/intellij-rust#6607]
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.51.0-nightly (e22670468 2020-12-30) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2020.3.1 Community Edition (IC-203.6682.168)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
```rust
#[cfg(test)]
mod test {
    #[tokio::test]
    async fn a() {
        unimplemented!()
    }
}
```
When a test is unsuccessful, the whole IDE becomes unresponsive temporarily. Additionally, the IDE can become unresponsive again temporarily if you click the test in the menu to focus on output.
Potentially relevant log:
[idea.log](https://github.com/intellij-rust/intellij-rust/files/5760890/idea.log)

## Steps to reproduce
1. Add tokio dependency
```toml
tokio = { version = "1.0.1", features = ["full"] }
```
2. Place the aforementioned code in the editor
3. Run the test

**Comment by PizzaCrust** [comment]
Also, this doesn't happen under the old name resolution engine.

**Comment by dima74** [comment]
@PizzaCrust thanks for report!

I don't think that new resolve somehow affects test execution. Probably something like this happens:
1. `tokio` dependency is added. By default, Rust plugin will process it only after `Cargo.toml` will be saved to disk
2. When we run test, IntelliJ automatically saves all files (including `Cargo.toml`) to disk. At this stage Rust plugin sees added dependency and does a lot of work - indexing, expanding macros, preparing data for new resolve

Probably lag is caused by `preparing data for new resolve`. Could you please run test multiple times and check whether lag occurs only at first run or not?

**Comment by PizzaCrust** [comment]
Yes, it happens every time the test fails (on CLion and Intellij CE). Additionally, every time I modify the Cargo.toml, I press `ctrl+s` and let it finish, before I start any work.

I don't know if this is related or not but, I tried to replicate the same thing on my machine using linux; and it didn't lag with both the old name resolution and the new name resolution.

I will upload a video shortly demonstrating the lag

**Comment by PizzaCrust** [comment]
https://drive.google.com/file/d/1RW8Sv-hDOaAmG3CyEInhSOiqTWDAEMwg/view?usp=sharing

**Comment by dima74** [comment]
@PizzaCrust could you please [install nightly build](https://www.jetbrains.com/rust/download/) and check that issue was fixed

**Comment by PizzaCrust** [comment]
Thanks! It's fixed
