### ISSUE TITLE
Get rid of usages of scheduled for removal IntelliJ API in Rust sources

### ISSUE THREAD

**Issue by chashnikov** [intellij-rust/intellij-rust#6737]
'Compatibility verification' section on [the plugin page](https://plugins.jetbrains.com/plugin/8182-rust/versions) reports that there are 30 usages of API which is scheduled for removal. Please process these usages and migrate corresponding code to modern API to avoid compatibility problems in the future. It also makes sense to look at usages of deprecated API.

**Comment by Undin** [comment]
I suppose this issue can be closed now. We fixed all usages of "scheduled for removal" API in [203 builds](https://plugins.jetbrains.com/plugin/8182-rust/versions/nightly/117467). All remaining warnings are not actually related to plugin source. They are because of a combination of `@ApiStatus.ScheduledForRemoval` annotation and kotlin interface method with default implementation without `@JvmDefault` annotation that leads to addition of deprecated API usages during compilation.

Newer "scheduled for removal" API will be fixed later when we drop support for the 203 platform.
