### ISSUE TITLE
Fails to expand declarative macro

### ISSUE THREAD

**Issue by Pzixel** [intellij-rust/intellij-rust#6753]
## Environment

CLion 2020.3.1
Build #CL-203.6682.181, built on December 30, 2020
You have a perpetual fallback license for this version.
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 16
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: org.toml.lang, com.intellij.plugin.adernov.powershell, org.rust.lang, ru.adelf.idea.dotenv
Macro expansion engine: new
Name resolution engine: new

Plugin version: 0.3.141.3634-203-nightly

## Problem description

this code should be expandable:

```rust
use utf16_lit::utf16;

const UTF88: &str = "cycle!";

fn main() {
    let _ = &utf16!(UTF88);
}
```

Actual result:

![image](https://user-images.githubusercontent.com/11201122/106198609-4dffe680-61c5-11eb-92a1-92b3bb4a061d.png)

**Comment by dima74** [comment]
If you use stable version of `utf16_lit` (1.0.1), then [`utf16` is actually a proc macro](https://github.com/Lokathor/utf16_lit/blob/v1.0.1/src/lib.rs#L37-L38), and the plugin currently doesn't support expanding procedural macros (#1786).

Also please note that `utf16_lit` [recently started to use declarative macros instead of proc macros](https://github.com/Lokathor/utf16_lit/commit/6cf082ca5504f252bf05dbd616775ef166c28e99), and with new name resolution engine the macro [can be expanded](https://user-images.githubusercontent.com/6505554/106207063-2f541c80-61d2-11eb-9edb-9728a847c873.png)

**Comment by Pzixel** [comment]
This is my cargo.toml:

```toml
[dependencies]
utf16_lit = { git = "https://github.com/Lokathor/utf16_lit", branch = "main" }
```

Which is using declarative macro expansion (you can tell it by `&utf16!()` in new version whenever procmacro one was `utf16!()`.
I know engine is not supposed to expand procedural macros
