### ISSUE TITLE
How to run bin/examples as root?

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#7048]
I'm developing something with dpdk and pnet, which require running as root. How can I run my bin/examples as root in intellij-rust, instead of manually `sudo target/examples/xxx`?

**Comment by ortem** [comment]
@qiujiangkun Running/debugging as root is not yet implemented in IntelliJ Rust.

Note, it is already implemented in CLion since CLion 2020.3 ([issue](https://youtrack.jetbrains.com/issue/CPP-7224), [documentation](https://www.jetbrains.com/help/clion/debug-as-root.html)), but does not natively support Rust for now. However, I suppose running Rust code as root in CLion can be done the following way.

### Workaround

1. Create a [Custom Build Application](https://www.jetbrains.com/help/clion/custom-build-targets.html) run configuration
2. Configure a Custom Build Target: create a new one and specify `Program` and `Arguments` fields. You can use the values from an existing Cargo run configuration, like on the screenshot
<img width="500" alt="Screenshot 2021-04-08 at 12 37 22" src="https://user-images.githubusercontent.com/4854600/114004292-2ed9a100-9867-11eb-854c-63314b154a14.png">

3. Specify an executable (`target/examples/xxx` in your case)
4. Specify a working directory. The value from an existing Cargo run configuration can be used
5. Enable `Run with root privileges` option
6. Run your configuration

Please feel free to inform us if this workaround works for you.

**Comment by qiujiangkun** [comment]
Thanks, it worked, though a bit inconvenient

**Comment by ortem** [comment]
@qiujiangkun Great! I hope we will implement running/debugging as root for Rust in the near future. For now, let's leave this issue open.
