### ISSUE TITLE
Handle `cfg(doc)` and `cfg(not(doc))` on modules

### ISSUE THREAD

**Issue by nazar-pc** [intellij-rust/intellij-rust#7136]
## Environment

* **IntelliJ Rust plugin version:** 0.3.146.3802-211-nightly
* **Rust toolchain version:** 1.53.0-nightly (07e0e2ec2 2021-03-24) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2021.1 Ultimate Edition (IU-211.6693.111)
* **Operating system:** Linux 5.11.15
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Originally reported as a comment: https://github.com/intellij-rust/intellij-rust/issues/1191#issuecomment-699544780

When following code is present, IDE is confused as to what version of the module should be used:
```rust
#[cfg(not(doc))]
pub use router::consumer;
#[cfg(doc)]
#[path = "router/consumer.rs"]
pub mod consumer;
```

I'm doing this because of https://github.com/rust-lang/rust/issues/59368.
The idea is to have nested modules with useful visibility scopes internally, but present it to the user as a flat structure.

I think if two modules like above are present, auto-imports should prefer `cfg(doc)`. It is more tricky when checking visibility rules though, in that case I think ideally IDE should check both and use the more restrictive path, but I'm not sure if it is feasible implementaion-wise.

## Steps to reproduce
See https://github.com/versatica/mediasoup/tree/v3/rust for the codebase where this is an issue (implementation, tests, examples).

**Comment by vlad20012** [comment]
@nazar-pc thanks for the report!

Do I understand correctly that autoimport prefers the full path `router::consumer` instead of just `consumer`?

I think it's not related to `cfg(doc)` at all because autoimport should just always prefer a shorter path.

But, well, when I see these `#[cfg(not(doc))]` and `#[cfg(doc)]` I suspect that you are doing things wrong. 
You could make the module `router` private and then re-export all items from another module:
```rust
mod router;
pub mod consumer {
    pub use super::router::consumer::*;
}
```
This is a well-known rust pattern, you can note it in almost all libs.
Or you could place [`#[doc(inline)]`](https://doc.rust-lang.org/rustdoc/the-doc-attribute.html#docno_inlinedocinline) attribute on `pub use router::consumer;` re-export to make it flat. But I'm not sure it works for module re-exports.

**Comment by nazar-pc** [comment]
Yes, one problem is that it imports longer path automatically, that is true.

As to the suggestion on re-export I'll take another look at it, don't remember why I didn't use it like that before, thanks!

**Comment by nazar-pc** [comment]
OK, I have refactored it and now indeed the only issue I see is that autoimport prefers the full path.
