### ISSUE TITLE
Test result hide successful result, only show failed result

### ISSUE THREAD

**Issue by davyzhu** [intellij-rust/intellij-rust#7138]
## Environment

* **IntelliJ Rust plugin version:**
03.145.3797.211
* **Rust toolchain version:**
1.51.0
* **IDE name and version:**
Pycharm 2021.1 Community
* **Operating system:**
Win 10

## Problem description
Test result hide successful result, only show failed result.
![image](https://user-images.githubusercontent.com/149704/115171973-d9b74e00-a0f6-11eb-8eed-1601ca5ecc4a.png)

![image](https://user-images.githubusercontent.com/149704/115172279-81cd1700-a0f7-11eb-8192-cef090d80c0a.png)

## Steps to reproduce
Create a simple test, configure `cargo test`, run it.
![image](https://user-images.githubusercontent.com/149704/115172161-3f0b3f00-a0f7-11eb-8fbd-3436827ae82e.png)

**Comment by Undin** [comment]
@davyzhu it's expected behavior. Successful tests are not shown by default. To see them, enable `Show Passed` option
![image](https://user-images.githubusercontent.com/2539310/115195864-f1430680-a0f7-11eb-832c-a0691029f9c2.png)
![image](https://user-images.githubusercontent.com/2539310/115195932-0324a980-a0f8-11eb-8e0e-62a0a90ac4bb.png)

**Comment by davyzhu** [comment]
> @davyzhu it's expected behavior. Successful tests are not shown by default. To see them, enable `Show Passed` option
> ![](https://user-images.githubusercontent.com/2539310/115196094-349d7500-a0f8-11eb-8423-55876791b8dc.png)
> 
> ![image](https://user-images.githubusercontent.com/2539310/115195932-0324a980-a0f8-11eb-8e0e-62a0a90ac4bb.png)

Thank you!!!

**Comment by davyzhu** [comment]
@Undin Thank you!!!
