### ISSUE TITLE
"Crate not found" after cache invalidation with local crates index enabled

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#7306]
## Environment

* **IntelliJ Rust plugin version:** 0.4.149.3901-212-nightly
* **Rust toolchain version:** 1.52.0-nightly (b3e19a221 2021-03-12) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2 EAP (CL-212.3888)
* **Operating system:** macOS 10.15.7
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

After cache invalidation, I stuck with "Crate not found" false positives in the `Cargo.toml`. 

## Steps to reproduce

1. Create a new project
2. Enable `org.rust.crates.local.index` in registry
3. Add `num = "0.4.0"` to dependencies
4. Run "File -> Invalidate Caches", select both options
5. Wait for everything to load back
6. `num` is reported as not found

<img width="667" alt="image" src="https://user-images.githubusercontent.com/2500320/120694567-0eb70e80-c4b3-11eb-9ef1-a00d1ab5df99.png">

**Comment by avrong** [comment]
Cannot reproduce on the latest nightly plugin.

Note that currently it is required to reload the IDE after enabling the experimental feature, otherwise, all the dependencies will be marked `not found` as the index is empty and will be downloaded on the next IDE startup or if the registry repo will be updated by Cargo

**Comment by lancelote** [comment]
Seem to be obsolete indeed. Sorry for the noise.
