### ISSUE TITLE
Support for clickable rust errors

### ISSUE THREAD

**Issue by lilianmoraru** [intellij-rust/intellij-rust#731]
Let's say you make a mistake and this message appears:
`error[E0308]: mismatched types`

It would be nice to be able to click in the output(or if it is not possible, than maybe present the option inside the IDE Window somewhere) on the error.
So, when clicking on "E0308", the plugin would sent the user to `https://doc.rust-lang.org/error-index.html#` + the error.
In this case it would look like this: `https://doc.rust-lang.org/error-index.html#E0308`.

Even better would be if it could take that part from the web and present it inside the IDE.

**Comment by matklad** [comment]
Ah, we kinda have this functionality already,  but it has bitrotten and no longer works with the new error format. 

Here it is: https://github.com/intellij-rust/intellij-rust/blob/aea198e1893dc73d7ecf0fafc6f8f714951681e8/src/main/kotlin/org/rust/cargo/runconfig/RustExplainFilter.kt

And I am a bit hesitant to fix it, because it will conflict with next/previous error shortcuts (see #611). As far as I know, it is impossible to make a link clickable with mouse, but exclude it from shortcuts. However, we can add a right click dropdown which would suggest to open a link in browser. But I am afraid nobody will understand that it is possible.

**Comment by alygin** [comment]
There's obviously a demand for such a feature. Maybe we could combine the dropdown list with a error code highlight (by means of `com.intellij.execution.filters.Filter.Result.highlightAttributes`) to give the user a hint about the possibility of doing something with this error code. What do you think?

**Comment by matklad** [comment]
Fixed by #788, thanks @d9n!
