### ISSUE TITLE
Bad completion recommendation for `else` statement

### ISSUE THREAD

**Issue by MintBee** [intellij-rust/intellij-rust#7325]
## Environment

* **IntelliJ Rust plugin version:** 0.4.148.3911-211
* **Rust toolchain version:** 1.52.1 (9bc8c42bb 2021-05-09) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.1.1 (CL-211.7142.21)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

I actually have no idea about what most Rustaceans are doing when trying to use `else` keyword, but personally, I usually just type "el" and enter: let IDE complete it.

What makes me very uncomfortable is following
![image](https://user-images.githubusercontent.com/60168844/121368921-63a4ca00-c976-11eb-87c1-9631abdba558.png)

After `if` block, why in the world eprintln!() is recommended first followed by private fn and than finally and eventually else is recommended?

![image](https://user-images.githubusercontent.com/60168844/121368983-715a4f80-c976-11eb-9d7e-0ef46d4debb0.png)

If I type "els" it shows me else finally, but I've always used just "el" to type `else` and there was no problem to type `else` properly except for this case in my entire programming experience. (makes me insane!)

Can guys who work with Intellij Plugin kindly consider this when they develop it?
Imo, it doesn't make any sense in the given context.

**Comment by CAD97** [comment]
The general solution here is probably to prefer keyword suggestions when in a location said keyword is valid, and the suggestion is a "good match" (for some value of good match).

There are interesting edge cases, of course: a function in scope called `el`, if you type `ee` how much does that favor `else` as a completion over other functions, etc.

But in this _specific_ case, it's pretty clear that

- when a keyword suggestion is provided
- and the match for the suggestion is a prefix
- then the keyword suggestion should be favored
- unless there is an exact match suggestion

for the `else` case, at least.

Unfortunately, there's at least one counterexample to generalizing this to all keyword suggestions: since `match` starts a statement/expression, any prefix of it would then prefer `match`, where a local variable (or even function) could be what the user would prefer, especially if said user were a common user of postfix snippets (e.g. `.match` to create a match expression around).

So while this seems like a generalizable concept, `else` might be the only keyword worth prioritizing in this manner, given its status as a continuation keyword.

-----

In another generalization direction, I personally would expect a suggestion with a prefix match to generally always be prioritized over a fuzzy match. Perhaps the above ramble is irrelevant and that's the core mismatch instead.

**Comment by afetisov** [comment]
Looks like a non-issue to me. Typing out `else` is barely more work than `el` + completion. The basic problem is that it's unclear what rules could be used to distinguish your intention from a perfectly valid if-block followed by a statement. Considering that most Rust statements can also be used as expressions, prioritizing keywords would mean that any identifier which has a common prefix with "if", "try", "match", "async", "loop", "for", "while", "as", "break", "continue" or "return" would have problems with autocompletion.

One could make an exception for "else" in a specific case where it directly follows the closing brace }, but that would be inconsistent since whitespace never affects autocompletion in other cases, and will be incompatible with any different code style.

**Comment by ortem** [comment]
@MintBee Thank you for reporting. Now Rust keywords are collected and shown at the very beginning of the completion session so this issue is resolved. Read [the PR description](https://github.com/intellij-rust/intellij-rust/pull/7703) for more information.

@CAD97 @afetisov The problem you described is indeed important and will be hopefully solved by our new ML-based ranking model. Currently, the model is experimental and disabled by default but you can enable it in `Editor | General | Code Completion | Machine Learning-Assisted Completion` settings.

Feel free to provide any feedback on the code completion. It would really help us to improve the new ranking model.
