### ISSUE TITLE
Bind "Make project" to "cargo build" by default

### ISSUE THREAD

**Issue by target-san** [intellij-rust/intellij-rust#736]
ATM trying to perform "Make project" causes error "No SDK set up for project"
I was told in project's gitter that this action wasn't tied to cargo invocation because the latter may require additional arguments. Though, I'd suggest invoking "cargo build" when running compile/make project, because it's the action expected in most cases, especially during development
- In most cases development process happens in debug mode, which is the default
- In most cases, custom builds happen in special situations like deploy etc.

So I think it'd be a good and sensible default for most users. Ones not satisfied will be able to use "Run Configurations"

**Comment by matklad** [comment]
Yep, this is a know rough edge at the moment. The problem is that wile a single `make project` works cleanly in the Java world (because there is a whole incremental build system imlemented in the IDEA itself), it's not that obvious what it should do in Rust. Should it be a `cargo build`, or `cargo build --release`? What about feature flags? And note that the Cargo side of things is still evolving: you can't use a plain `cargo build` with a virtual manifest, for example. 

So, the current strategy is to use `Run configurations` instead, and wait until things settle down a bit :) 

This is covered in FAQ: https://intellij-rust.github.io/docs/faq.html#make

**Comment by ForsakenHarmony** [comment]
debugging would also be nice

https://github.com/RustDT/RustDT/blob/latest/documentation/Features.md#debugging-functionality

**Comment by chriskrycho** [comment]
@ForsakenHarmony also a known issue. See: https://github.com/intellij-rust/intellij-rust/issues/535

**Comment by devurandom** [comment]
This seems somewhat related to #876 and #861. A good start would already be if CLion+Rust could import existing projects (i.e. those that already have a `Cargo.toml`), instead of creating `CMakeLists.txt`.

**Comment by matklad** [comment]
Make project now executes `cargo build` or `cargo check`, depending on the project-level settings.

**Comment by Horki** [comment]
I have problem running Debug in Clion for Rust, please help
<img width="1440" alt="screen shot 2018-01-20 at 20 59 57" src="https://user-images.githubusercontent.com/1398263/35187501-04dbb936-fe25-11e7-91fa-17de871f3f51.png">

**Comment by ForsakenHarmony** [comment]
@Horki #535
