### ISSUE TITLE
"Self convention" inspection doesn't represent the actual conventions

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#7475]
## Environment

* **IntelliJ Rust plugin version:** 0.4.151.3969-211-nightly
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.1.2 (CL-211.7442.42)
* **Operating system:** Linux 5.4.0-77-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

"Self conventions" insists that methods starting with "with_" must take the receiver by value or by mutable reference. It seems that the person writing this code thought about the methods in builder patterns, which indeed follow this convention. However, this is not the actual convention in the Rust code at large. For example, collections in Rust commonly have a constructor "with_capacity" which doesn't take `self` at all, and the prefix "with_" is common for factory functions. A `&self` receiver can also be used when the type has internal mutability, or for methods which take an applied closure.

The intention also claims that methods starting with "to_" must take `&self`. This is also inconsistent with Rust practice, and with [Clippy](https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention) which is closer to the actual convention. 

Similar problem with "get_". It can take a `&mut self` when the method has the form `get_??_mut` (or a `&self` for types with internal mutability).

## Suggestion

* remove the "with_" self convention;
* make "to_" self convention consistent with Clippy: `"to_??_mut"` takes `&mut self`; `"to_??"` takes either `&self`, or `self` if `self: Copy`.
* fix the "get_" convention: a method `get_??_mut` can take `&self` or `&mut self`.

**Comment by Kobzol** [comment]
This inspection is quite opinionated nad its assumptions might be outdated, I agree. I don't like changing the heuristic arbitrarily, but I really like your idea to copy the logic from Clippy. It's well known and used in the Rust ecosystem and it therefore probably "defines" what the actual convention is.

Do you want to change the inspection so that it behaves the same as Clippy does? Maybe checking `Copy` types is not needed, otherwise it should be quite simple, we just also need to check the suffix of the method and not just the prefix. If not, I will implement it.

**Comment by afetisov** [comment]
Working like Clippy seems fine. I don't know how reasonable it is to check for `Copy` in that intention, imho that restriction can be safely dropped (most people would run Clippy anyway). I think we should still check for suffixes, it's simple enough.

Clippy doesn't have conventions for get/set methods. It is unclear to me whether Intellij's current conventions are reasonable. I can't imagine a situation where those methods taking `self` would be reasonable, but both `&self` and `&mut self` could be used (e.g. we may have a setter on a type with interior mutability). I can also imagine those methods being static, if they get/set a global variable.

Maybe `set_`-methods with a `self` argument could be used in a builder pattern?

**Comment by Kobzol** [comment]
I suspect that `set_` with `self` are probably used in some builder patterns. Your point about factory/static methods is valid, maybe we should just ignore `get`/`set` if it's not a method. `fn get()` might be okay, but `fn get(self)` is a bit suspicious.

**Comment by afetisov** [comment]
Maybe we could run some script on the Crates.io packages to check which patterns exist and which are common?

**Comment by Kobzol** [comment]
I tried GitHub search and some other online service quickly, but it didn't get me reasonable results. But yeah, it's a possibility.

> Maybe fn get(self) could be used with Copy types?

Well, I guess it could. There will always be cases where the convention is "broken", even in some of my personal Rust projects this  inspection gives me a false positive, because I don't follow the "convention". The goal is to find a sweet spot where the inspection doesn't produce a lot of false positives and at the same time it actually finds places where a reasonable convention is not followed (and that might mark a bug in the user's code).

For that reason I think that it's reasonable to implement exactly the convention that `Clippy` uses (or its subset), otherwise we could be debating these heuristics and edge cases for a long time :)

**Comment by afetisov** [comment]
Very well, Clippy it is then. I guess Clippy is _the_ place to establish Rust naming conventions.

**Comment by a1ien** [comment]
What about `set_` that take `&self` for interior mutability?

**Comment by Kobzol** [comment]
I know, these should be supported. I think that I will just remove the `get`/`set` lints altogether, there are too many false positives with them and they are not supported by `Clippy` anyway.
