### ISSUE TITLE
False-positive `Invalid version requirement` warning in Cargo.toml

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#7600]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4014-212-nightly
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.3 EAP (CL-213.1557)
* **Operating system:** macOS 11.2.3
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
`CrateVersionInvalidInspection` produces a false-positive warning on a version requirement with `-`, like `"0.4.0-2"`.

## Steps to reproduce
`Cargo.toml`
```Toml
[dependencies]
libbpf-sys = { version = "0.4.0-2" }
```
`Invalid version requirement 0.4.0-2` warning is shown, but the version requirement is actually [correct](https://crates.io/crates/libbpf-sys/versions).

**Comment by avrong** [comment]
`semver4j` treats requirements with hyphens and numbers like `0.4.0-2` range requirements meaning this will parse as `>=0.4.0 <3.0.0`.

Coupled with `^` before the version that is included by default, this creates a situation when the presence of two requirements returns `null`.

We could create a special case for such versions, but we will need to do it for each separate requirement modificator and the problem is that we can't construct `Requirement` of `semver4j` by ourselves, it is private.

Things that currently don't work properly:
- parsing versions with numbers after `-` (`1.2.3-4`)
- parsing versions with requirements (`^`, `=`, etc.) with numbers after `-` (`^1.2.3-4`)
- correctly handle version order according to [semver spec](https://docs.rs/semver/1.0.3/semver/struct.Prerelease.html#total-ordering) and [rust semver](https://docs.rs/semver/1.0.3/semver/struct.Prerelease.html#total-ordering) docs
