### ISSUE TITLE
Add "Crate Module" button to create module directory with `mod.rs`

### ISSUE THREAD

**Issue by Zymlex** [intellij-rust/intellij-rust#7636]
Add "Crate Module" button to create module with `mod.rs`:

![изображение](https://user-images.githubusercontent.com/25817412/128582571-4edaf367-0a27-4776-99d6-19c93378cc5d.png)

**Comment by vlad20012** [comment]
Currently, it works in a different order. When you type `mod foo;` in some file, the plugin shows you a suggestion to create a file with such name:

https://user-images.githubusercontent.com/3221931/128859622-31976e27-d092-472b-a789-dd4a2a087d9a.mp4

This workflow is much handier than inserting mod declaration after file creation because the IDE takes care of a location where a module should be created.

Also, Rust modules with `mod.rs` are a little bit outdated since edition 2018 where it became possible to create nested modules without `mod.rs`.

Summarizing all the above, I'd not say this feature would be useful.

Also, duplicates #5707
