### ISSUE TITLE
Create tuple struct or function generate code with wrong placeholder

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#7672]
## Environment

* **IntelliJ Rust plugin version:** 0.4.154.4041-212-nightly
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2 (CL-212.4746.93)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Creating a struct from a line with an unresolved type of parameter generates a struct with _ placeholder. 
But: _error[E0121]: the type placeholder `_` is not allowed within types on item signatures for structs_

https://user-images.githubusercontent.com/49211026/129343762-edf1cf37-ad76-4f3c-aac4-a89f4669f8eb.mov

Same situation with functions:
<img width="342" alt="изображение" src="https://user-images.githubusercontent.com/49211026/129345168-8c310e6f-8c96-443a-bff6-17ce908c2422.png">

## Steps to reproduce
```rust
// struct Baz(i32, _);

fn main() {
    Baz(566, something);
    foo(566, something)
}

// fn foo(p0: i32, p1: _) {
//     todo!()
// }
```

**Comment by Kobzol** [comment]
Good catch! Probably we should use a template to let the user fill in unknown types.

**Comment by vlad20012** [comment]
Like we did it in `Convert closure to function` intention

**Comment by Kobzol** [comment]
That intention uses `()` for unknown types instead of `_` for parameters. Maybe it would be better to also switch to `()` to make the generated core "more valid" (even though it still won't compile outright, because the types will not match).

Also for named structs, currently `RsMultipleVariableRenamer` is used instead of the template builder to rename the names of the fields. But I think that with the new API it should be relatively simple to migrate it to the template builder, so that we can use templates for both field names and their types.

**Comment by vlad20012** [comment]
> That intention uses `()` for unknown types instead of `_` for parameters

I'd say, we should choose `()` or `_` and use it in all the code generation stuff

**Comment by Kobzol** [comment]
I agree. `_` won't compile, so there's less chance that the user will miss it. `()` might in some cases compile after the code is generated, but it usually probably isn't what the user wants.
