### ISSUE TITLE
Highlight exit points of the function

### ISSUE THREAD

**Issue by aka-demik** [intellij-rust/intellij-rust#778]
It is much easier to analyze the control flow of the function, if the highlighted (background / Gutter) all exit points. `return`, `{ re_val }`, `try!`, `panic!`, `?` and so on.

A la [Navigate To Function Exits](https://www.jetbrains.com/help/resharper/2016.2/Navigation_and_Search__Navigate_from_Here__Function_Exits.html)  from ReSharper.

**Comment by alygin** [comment]
Just a note: In IDEA it's usually implemented as background highlighting of all exit points when you put the cursor to any of them:

<img width="240" alt="screen shot 2016-11-30 at 00 44 54" src="https://cloud.githubusercontent.com/assets/2101250/20730218/40d23e06-b696-11e6-9bb9-2da93e4db6f4.png">

**Comment by johnthagen** [comment]
I like the idea (no pun intended) of highlighting after you put your cursor on a return statement. When I first read this issue I thought that all returns would always be highlighted, which I would add a bit too much noise to the display.

**Comment by alygin** [comment]
Another possible implementation is to highlight exit points when the cursor is placed on the function name. IntelliJ uses this approach in other products ([ReSharper](https://www.jetbrains.com/help/resharper/10.0/Navigation_and_Search__Navigate_from_Here__Function_Exits.html), [dotPeek](https://www.jetbrains.com/help/decompiler/10.0/Navigation_and_Search__Navigate_from_Here__Function_Exits.html)). In this case you always know where to click to see them and don't have to scan the function body with your eyes looking for at least one such point.

I think this approach has some advantage here because Rust's exit points are [harder to find quickly](https://github.com/intellij-rust/intellij-rust/issues/785#issuecomment-263819800). Or these approaches can be combined.

**Comment by farodin91** [comment]
I'm on it.
