### ISSUE TITLE
Syntax coloring for ? symbol.

### ISSUE THREAD

**Issue by la10736** [intellij-rust/intellij-rust#785]
When use `?` instead of `try!()` macro there are no evidence of it in the syntax highlighting. That make very hard to identify these exit points.

If you have no time to do it please point me where I should looking for to implement it.

**Comment by matklad** [comment]
This should be handled in the annotator: https://github.com/intellij-rust/intellij-rust/blob/48d122ebde0ce7e96ee62bc34ec393fc0dc5f639/src/main/kotlin/org/rust/ide/annotator/RustHighlightingAnnotator.kt

Other relevant bits are

https://github.com/intellij-rust/intellij-rust/blob/48d122ebde0ce7e96ee62bc34ec393fc0dc5f639/src/main/kotlin/org/rust/ide/colors/RustColorSettingsPage.kt

and 

https://github.com/intellij-rust/intellij-rust/blob/48d122ebde0ce7e96ee62bc34ec393fc0dc5f639/src/main/kotlin/org/rust/ide/colors/RustColors.kt

**Comment by johnthagen** [comment]
`?` should just be colored as an operator now, right? Like `+`, etc?

https://blog.rust-lang.org/2016/11/10/Rust-1.13.html

**Comment by matklad** [comment]
I think it makes sense to add a separate color for `?`, and perhaps even make it stand out a bit by default.

**Comment by la10736** [comment]
Maybe implement #778 is the right way to handle this scenario.

**Comment by alygin** [comment]
In my opinion, these tasks are not mutual exclusive. Moreover, I think the different color is much more important in Rust than background highlighting as described in #778.

The reason is that in Java/Kotlin exit points are quite wordy (it's `return ...` or `throw ...` usually placed on a separate line) and so are relatively easy to find and put the cursor on one of them. And you always know that at least you find a `return` at the end of the function.

In Rust, we have а `?` symbol that can be hidden somewhere in the middle of a long calls chain, and the `return` word might be absent at all. In such cases, it's much harder to quickly find a `?` symbol. And even when you find one and manage to hit it with the cursor, it's still hard to find other highlightings because the dark green background for a single symbol somewhere in the middle of another long line (again, unlike in Java/Kotlin) is not so easy to notice. Different color for `?`'s would help greatly here.

Here's a real example from the Cargo source code. Just try to quickly find a place you need to click to highlight the exit points:

```rust
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        match *self.inner {
            SourceIdInner { kind: Kind::Path, ref url, .. } => {
                fmt::Display::fmt(url, f)
            }
            SourceIdInner { kind: Kind::Git(ref reference), ref url,
                            ref precise, .. } => {
                write!(f, "{}{}", url, reference.url_ref())?;

                if let Some(ref s) = *precise {
                    let len = cmp::min(s.len(), 8);
                    write!(f, "#{}", &s[..len])?;
                }
                Ok(())
            }
            SourceIdInner { kind: Kind::Registry, ref url, .. } |
            SourceIdInner { kind: Kind::LocalRegistry, ref url, .. } => {
                write!(f, "registry {}", url)
            }
            SourceIdInner { kind: Kind::Directory, ref url, .. } => {
                write!(f, "dir {}", url)
            }
        }
    }
```

And this example is relatively easy because `?`s are at the ends of lines and because Github already colorizes them. In other cases with `?`s in the middle of lines and without coloring, it will be much harder.

That's why I think the coloring of `?`s is crucial while contextual highlighting is of less importance.

**Comment by chriskrycho** [comment]
I'd also suggest *bolding* the question mark: `?` vs. **`?`**, combined with color, would help a lot. I also agree that this and #778 are not mutually exclusive (especially if #778 ends up being a configurable option); there are any number of places where #778 will show that this won't, even if it would also include all of these. Personally, I'd be inclined *not* to have #778 enabled in my own codebase, so having this coloring (and bolding?) would still be helpful.

**Comment by johnthagen** [comment]
A reminder that an example usage of `?` should also be added to [highligherDemoText.rs](https://github.com/intellij-rust/intellij-rust/blob/f2d86bdbf9b5e7fe7ab3af59812f7d4e4c1e06a9/src/main/resources/org/rust/ide/colors/highlighterDemoText.rs)

**Comment by alygin** [comment]
Since `?` controls the program execution flow, how about highlighting it as a keyword?

<img width="454" alt="screen shot 2016-12-02 at 22 24 07" src="https://cloud.githubusercontent.com/assets/2101250/20848051/8aea3528-b8e1-11e6-9ba1-5ff0d175ba7e.png">

<img width="450" alt="screen shot 2016-12-02 at 22 25 56" src="https://cloud.githubusercontent.com/assets/2101250/20848061/923db714-b8e1-11e6-82cc-e644ef69eb73.png">

For me, it doesn't look conspicuous enough in the default (white) theme, but that might be because I don't use it much.

**Comment by la10736** [comment]
Ok, I've looked at this little bit late :smile: . I sent a PR #813 for test case.
