### ISSUE TITLE
Debugger doesn't break at breakpoints in some cases (using raqote)

### ISSUE THREAD

**Issue by phisch** [intellij-rust/intellij-rust#7958]
## Environment

* **IntelliJ Rust plugin version:** 0.4.157.4174-212
* **Rust toolchain version:** rustc 1.55.0 (c8dfcfe04 2021-09-06)
* **IDE name and version:** IntelliJ IDEA 2021.2.2 (Ultimate Edition)
* **Operating system:** Arch Linux

## Problem description
When using the [raqote](https://github.com/jrmuizel/raqote) library, there are some weird cases in which the rust debugger does not break at any breakpoints anymore. I have a minimal reproducible example in the next section.

Since it is very unclear what exactly causes this issue, i have also reported it at raqote directly, my best guess would be this is some issue with the debugger itself, rather than raqote.
Here is the issue in raqotes repository: https://github.com/jrmuizel/raqote/issues/178

## Steps to reproduce
Create a rust project, and add raqote to the `Cargo.toml` dependency section:

```toml
[dependencies]
raqote = "0.8.0"
```

Add the following code to your `main.rs`:
```rs
use std::f32::consts::PI;
use raqote::*;

fn main() {
    let mut dt = DrawTarget::new(400, 400);
    let mut pb = PathBuilder::new();
    pb.move_to(200., 200.);
    pb.arc(200., 200., 200., 0., 2. * PI);
    pb.close();

    let path = pb.finish();
    let color = Source::Solid(SolidSource { r: 0x80, g: 0x20, b: 0xff, a: 0xff });

    // as soon as the line containing `dt.stroke(...` is commented out,
    // the debugger doesn't stop at breakpoints anymore

    dt.fill(&path,&color,&DrawOptions::new());
    dt.stroke(&path, &color, &StrokeStyle::default(), &DrawOptions::default());

    dt.write_png("example.png");
}
```
Setting a breakpoint anywhere works as expected, but as soon as the line containing `dt.stroke(&path, &color, &StrokeStyle::default(), &DrawOptions::default());` is commented out, breakpoints do not work in the entire file anymore.

**Comment by phisch** [comment]
Also broken on:
* **IDE name and version:** IntelliJ IDEA 2021.3 EAP (Ultimate Edition)
* **IntelliJ Rust plugin version:** 0.4.157.4174-213

**Comment by ortem** [comment]
See https://github.com/intellij-rust/intellij-rust/issues/7698#issuecomment-943407856

**Comment by ortem** [comment]
I think this issue can be finally closed now, see https://github.com/intellij-rust/intellij-rust/issues/7698#issuecomment-954822171.

@eiennohito Thank you for reporting. The problem you are facing on Windows is most likely not related to this issue since IDE uses a very different LLDB for the MSVC toolchain. It would be helpful to have more details about your particular case to investigate that problem on Windows. You could use `Help | Create New Issue` action right from your IDE to create a new issue and automatically provide us with the information about your environment. Also, it would be great if you could attach IDE logs using `Help | Show Log in Explorer` action (check the [instruction](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) for more information; keep in mind that it might contain sensitive information like local paths) and any examples to reproduce the problem.
