### ISSUE TITLE
recent updates do not properly pass %PATH% to cargo on windows10

### ISSUE THREAD

**Issue by Trolldemorted** [intellij-rust/intellij-rust#798]
After upgrading Intellij (community) to 2016.3 (and patching the rust plugin), my rust project can no longer be run from intellij:

```
C:\Users\XXXX\.cargo\bin\cargo.exe run --bin YYYYYYY
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\YYYYYYY.exe`
error: process didn't exit successfully: `target\debug\YYYYYYY.exe` (exit code: 3221225781)

Process finished with exit code -1073741515 (0xC0000135)
```

When i run the cargo command from my W10 shell, it works. When i copy the required .dlls (which are in folders that are included in my PATH) to projecthome/target/debug/, it works from intellij too.

Did you more or less recently change which environment variables are passed to cargo?

**Comment by matklad** [comment]
>Did you more or less recently change which environment variables are passed to cargo?

No, I don't believe there were related changes recently. We've switched to UTF-8 output for cargo processes recently, but this is purely UI thing. You can inspect environment variables from Rust with

```
for (key, value) in ::std::env::vars() {
    println!("{}: {}", key, value);
}
```

Does this confirms that `PATH` is indeed different between the shell and the IDE spawned Cargo?

**Comment by Trolldemorted** [comment]
yeah, the `PATH` from intellij is different. Longer, but some folders are missing.

Nevertheless, restarting IntelliJ again (i did once to install 2016.3, then again to update the rust plugin) yields now *another* different path (three time a charm, i guess), but at least that one is apparently a superset of my real windows path.

Thanks for your quick help, i am closing this as this is most likely a w10/intellij issue.

**Comment by Philipp91** [comment]
For me, this error occurs when I use rustup to switch the default toolchain from `nightly-x86_64-pc-windows-msvc` to `nightly-x86_64-pc-windows-gnu`. The command `cargo` also fails on the cmd shell and complains that zlib1.dll is missing, with the same error code `-1073741515`.

For me, that file is in `C:\Git\mingw64\bin` -- possibly because I copied it in there manually at some point. That directory is added to the PATH by MinGW shells. So I'm just putting that directory on the system's PATH for now and hope that nothing else breaks. Alternative solution would be to (download and) put that file elsewhere, like `C:\Git\bin`, which is on the system's PATH anyway.
