### ISSUE TITLE
Types aren't recognized when using Bevy queries

### ISSUE THREAD

**Issue by yopox** [intellij-rust/intellij-rust#8049]
## Environment

* **IntelliJ Rust plugin version:** 0.4.158.4203-212
* **Rust toolchain version:** rustup 1.24.3 (ce5817a94 2021-05-31)
* **IDE name and version:** CLion 212
* **Operating system:** macOS 12.0

## Problem description

It is easy to work with Bevy `Query` when it is of form `Query<T>` because the type parameter is recognized. Most of the queries are of form `Query<(T, U, …)>` and here the Rust plugin recognizes `<unknown>` types.

<img width="470" alt="Screenshot 2021-11-03 at 09 27 08" src="https://user-images.githubusercontent.com/8440079/140028776-e40d312e-ddec-4eb1-a3c7-b621f73742fd.png">

Fixing this issue would greatly improve game development using Bevy and CLion.

`cargo.toml`

```rust
[package]
name = "bug_report"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version="0.5.0", default-features=false}
```

`main.rs`

```rust
use bevy::prelude::*;

fn main() {
    App::build().run();
}

fn system1(query: Query<&Transform>) {
    for transform in query.iter() { // &Transform
        println!("position: {:?}", transform.translation);
    }
}

fn system2(query: Query<(Entity, &Transform)>) {
    for (e, transform) in query.iter() { // (<unknown>, <unknown>)
        println!("position: {:?}", transform.translation);
    }
}
```

**Comment by Arc-blroth** [comment]
Queries with tuples don't resolve by default since Bevy generates their `WorldQuery` impl with a [proc macro](https://github.com/bevyengine/bevy/blob/f907d67d7ed5cfd8b11b2ad78e9dfd6eeb913cea/crates/bevy_ecs/src/query/fetch.rs#L1499). However, enabling the experimental proc macro support #6908 (experimental features `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc`) seems to fix type resolution:

![image](https://user-images.githubusercontent.com/45273859/162125447-1614857d-f575-4194-928a-9932601b1448.png)

**Comment by Bastczuak** [comment]
@yopox here is my steps to get it working again. 

1. disable the experimental rust feature described above. 
2. Use the cache invalidation in clion, tick all boxes
3. enable the experimental feature again
4. Again use the cache invalidation
<img width="469" alt="Screen Shot 2022-07-29 at 21 15 01" src="https://user-images.githubusercontent.com/50180188/181829154-fee670d8-b536-485b-9c65-33b338c39c26.png">
