### ISSUE TITLE
Rust dependency auto select

### ISSUE THREAD

**Issue by jrpruitt** [intellij-rust/intellij-rust#8127]
## Environment
CLion 2021.2.3
Build #CL-212.5457.51, built on October 14, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.0-8-amd64
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 8
Registry: run.processes.with.pty=TRUE, cidr.max.intellisense.file.length=1500000
Non-Bundled Plugins: org.toml.lang (0.2.155.4114-212), org.rust.lang (0.4.158.4203-212)
Current Desktop: X-Cinnamon
OS: Debian 11 (bullseye)
rustc 1.48.0

## Problem description
When editing the Cargo.toml file, when you start typing a dependency name, it suggests possible matches, but it sometimes doesn't work correctly.

For instance, "tokio-tungstenite", if I type the "t", it comes up with a partial list of names that contain a "t". When I type the "o", the list goes blank. If I backspace and type the "o" again, it repopulates the list with matches of "to". That works correctly until I get to the "t" after the dash and then the list goes blank again. If I backspace to erase the "t" and then type it a second time, it will pull up the expected list.

The same issue exists in IntelliJ IDEA.

**Comment by Undin** [comment]
I suppose it should be fixed by completion based on the crate local index that will be enabled by default in the next release (v160).
But if you want to try it right now, you can enable `org.rust.crates.local.index` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features). But I'd suggest updating the plugin to the latest version before because it contains some improvements in the corresponding feature

https://user-images.githubusercontent.com/2539310/142480926-7a68497e-16a3-49cf-91f2-cd62afe7ecb6.mov

**Comment by jrpruitt** [comment]
Thank you very much.  That fixed it and is very nice how it lists all the versions.

**Comment by Undin** [comment]
Fixed in #7996
