### ISSUE TITLE
Proc macro expansion always fails on NixOS

### ISSUE THREAD

**Issue by ondt** [intellij-rust/intellij-rust#8197]
## Environment
* **IntelliJ Rust plugin version:** 0.4.161.4270-212-nightly
* **Rust toolchain version:** 1.56.1 (59eed8a2a 2021-11-01) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Linux 5.15.3-zen1 (nixos-unstable 73369f8d0864854d1acfa7f1e6217f7d6b6e3fa1)
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
So far I haven't come across a proc macro that would expand successfully. This seems to be an issue specific to NixOS. I tried it on a live Ubuntu stick and it worked as expected (the macro expansion popup showed up and code completion worked for the generated impls).

![2021-11-29T09:28:34+01:00_1305x249](https://user-images.githubusercontent.com/20520951/143874137-7f63de83-0af4-4e5d-a711-cfcfcf783195.png)

How can I help to debug this issue? Is there any log output where I can see what it was trying to do and what exactly went wrong?

## Steps to reproduce
Try expanding any proc macro on NixOS. I use rustup just for the IDE, but it does the same thing when launched from nix shell with [oxalica overlay](https://github.com/oxalica/rust-overlay).

**Comment by ondt** [comment]
Ok, so I finally took the time to look into this and found the reason why it didn't work.

## Problem
The problem is that `intellij-rust-native-helper` is shipped as a precompiled dynamically linked binary that depends on `/lib64/ld-linux-x86-64.so.2`, which is a no-go on NixOS because `/lib64/ld-linux-x86-64.so.2` simply doesn't exist on that path.

## Solution
In order for a random binary like this to work on NixOS it needs to be either:
- compiled from scratch / packaged in nixpkgs, OR
- patched with patchelf to use the correct dynamic linker from the Nix Store (see Workaround), OR
- statically linked to avoid runtime dependency on glibc or the dynamic linker, OR
- removed entirely and reimplemented in Java or Kotlin.

Compiling the native helper during plugin installation or including it in nixpkgs is a bad idea. Patching pre-compiled binary is also a bad idea, as the particular glibc that was linked can disappear without notice and is really only useful as a temporary workaround. Shipping a statically linked binary (`cargo build --target x86_64-unknown-linux-musl --release`, for example) is the best and easiest solution in my opinion.

## Workaround
A temporary workaround is to patch the `intellij-rust-native-helper` binary using patchelf.
```bash
$ nix shell nixpkgs#patchelf -c patchelf --set-interpreter $(nix eval --raw nixpkgs#glibc)/lib64/ld-linux-x86-64.so.2 ~/.local/share/JetBrains/CLion2021.3/intellij-rust/bin/linux/x86-64/intellij-rust-native-helper
```

**Comment by vlad20012** [comment]
Wow

**Comment by vlad20012** [comment]
Fun fact: rust-analyzer patches the binary at runtime:
https://github.com/rust-analyzer/rust-analyzer/blob/b65d9c3e62a55028236be84995d1ba43462f4a5c/editors/code/src/main.ts#L278-L319

**Comment by InternetUnexplorer** [comment]
I just ran into this myself :(. Patching the helper manually works temporarily, but static linking definitely seems to be the easiest/most robust solution here. It doesn't seem to increase the binary size by much:
```text
native-helper:master λ du -h target/x86_64-unknown-linux-{gnu,musl}/release/intellij-rust-native-helper
4.2M	target/x86_64-unknown-linux-gnu/release/intellij-rust-native-helper
4.4M	target/x86_64-unknown-linux-musl/release/intellij-rust-native-helper
```
It looks like the binaries are built [here](https://github.com/intellij-rust/intellij-rust/blob/master/.github/workflows/build-native-code.yml); I'm unsure about my ability to change it without breaking something (especially since I don't know how to test GitHub Actions locally), but if I'm able to figure it out I'll do my best to put together a PR.

**Comment by ortem** [comment]
@InternetUnexplorer Maybe https://github.com/Mic92/nix-ld could be a solution, instead of patching the binaries manually after every update

**Comment by InternetUnexplorer** [comment]
@ortem Thanks for the suggestion, I might try it when I get a chance, but it looks like it sets `LD_LIBRARY_PATH`, which I think will cause problems with Nix-provided Rust toolchains. Still, I don't feel confident enough to make a PR changing the way the helper is built without breaking something, so a fragile solution is better than no solution at all!

**Comment by ortem** [comment]
@InternetUnexplorer Feel free to provide your feedback about `nix-ld` here. None of the current IntelliJ Rust maintainers has experience with NixOS, so we would be glad to hear if there is a ready-to-use solution for NixOS users.

Speaking of changing how the `intellij-rust-native-helper` is built, I would say that we would consider it a last resort. Although static linking doesn't significantly increase the binary size, it could require more effort from us as the maintainers to deal with potential compatibility or safety issues in the future. Especially considering that none of us has a NixOS environment for testing purposes.

**Comment by ondt** [comment]
@ortem @InternetUnexplorer I've been using the `nix-ld` NixOS module for at least half a year and it works flawlessly. Never had to do `patchelf` since.

**Comment by InternetUnexplorer** [comment]
> I've been using the `nix-ld` NixOS module for at least half a year and it works flawlessly. Never had to do `patchelf` since.

@ortem Wait, you're right! It works (I think)! I was worried it wouldn't, because of the note about "LD_LIBRARY_PATH is inherited by child processes" in the README. I haven't tested it very thoroughly yet, so there might be issues that come up in the future, but for now it seems to work. It's not a perfect solution (there's a reason NixOS doesn't do this by default), but it's definitely really convenient.

> Speaking of changing how the `intellij-rust-native-helper` is built, I would say that we would consider it a last resort.

@ortem I was worried about that :(. It seems like a big change that could have a lot of unintended side-effects. But at least right now using `nix-ld` seems to solve this issue for me :). I guess the summary as I understand it is:

- Using `nix-ld` if is a quick and easy solution.
- Using a packaged version of the extension is a more nix-y solution, but requires more effort.
- Using `patchelf` manually is a sort of in-between option, for those who do not want to use `nix-ld` for whatever reason but also want to let IntelliJ install/update the extension.

At the moment, `nix-ld` works great for me :). If at some point all of the extensions I use make it into nixpkgs or I find an overlay somewhere and I have some spare time, I might switch to using packaged versions instead. But in the meantime everything seems to be working! Thanks everyone for your help :).

**Comment by ortem** [comment]
@ondt @InternetUnexplorer Thank you for sharing your experience! I am glad to hear that it works. I think now we can suggest `nix-ld` as a decent solution for NixOS users who experience issues with precompiled binaries that our plugin uses.
