### ISSUE TITLE
Trust Project notification is doubled for welcome plugin screen

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#8204]
## Environment

* **IntelliJ Rust plugin version:** 0.4.162.4278-213-nightly
* **Rust toolchain version:** null
* **IDE name and version:** IntelliJ IDEA 2021.3 RC Ultimate Edition (IU-213.6206), 212
* **Operating system:** macOS 11.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
Trust Project notification is doubled for welcome plugin screen

## Steps to reproduce
1. Install `Test Management` plugin
2. Open a new project without .idea => the IDE should ask whether you trust this project or not.
3.  Stay in Safe mode => Project is opened

## Expected Results:
Only one notification is shown

## Actual Results:
Notification is tripled 
<img width="744" alt="Screenshot 2021-11-30 at 13 41 47" src="https://user-images.githubusercontent.com/1213122/144049166-cb3164ba-fb74-4d8d-abe0-b043530457db.png">
[trust.txt](https://github.com/intellij-rust/intellij-rust/files/7625772/trust.txt)

**Comment by Undin** [comment]
@mili-l Looks like the bug is not related to Rust plugin because:
- the plugin shows this notification only for Rust and Cargo.toml files
- I've managed to reproduce it without Rust plugin 😄 

You can try [this](https://github.com/intellij-rust/intellij-rust/files/7648029/intellij-rust-0.4.162.SNAPSHOT-213-dev.zip) build if you don't manage to reproduce the bug without Rust plugin. I've added "(from Rust plugin)" text to the corresponding notification in this build to distinguish it from other similar notifications

![image](https://user-images.githubusercontent.com/2539310/144574102-6ae72b74-1906-4a46-b353-33d654435315.png)

**Comment by mili-l** [comment]
Cannot reproduce
