### ISSUE TITLE
Ability to supress errors in Rust

### ISSUE THREAD

**Issue by egorklepikov** [intellij-rust/intellij-rust#8407]
Hi

I am using the Rust plugin for IntelliJ IDEA. I am currently writing a procedural macro. Below you can find a very stripped down of this macro:

```rust
#[proc_macro_attribute]
pub fn my_macro(attrs: TokenStream, input: TokenStream) -> TokenStream {
    let mut item_struct = parse_macro_input!(input as ItemStruct);

    /*parse attributes, add a field to the item_struct, etc...*/

    let output = quote!(
        #item_struct
        
        impl MySuperTrait for #item_struct_name {
            /*implement methods*/
        }
    )
    Tokenstream::from(output)
}
```

The above macro implements the functions of a trait `MySuperTrait`. I also have another trait:

```rust
pub trait MyTrait: MySuperTrait {
    /*specific functions for MyTrait*/
}
```
When I now use this in practice:

```rust
#[my_macro]
struct MyStruct {}

impl MyTrait for MyStruct {
    /*implementation*/
}

```

The IDE gives an error at the line impl MyTrait for MyStruct (line 4):

```
The trait bound `MyStruct: MySyperTrait` is not satisfied [E0277] 
the trait `MySuperTrait` is not implemented for `MyStruct`
```

And it gives me the option to implement missing members of supertrait(s). However, the example above will compile and run perfectly. IntelliJ just doesn't know the MySuperTrait trait is implemented using the macro. It would be nice to have IntelliJ either be able to expand procedural macros or simply suppress this error.

**Comment by Undin** [comment]
I don't think the plugin should provide an easy way to turn off compiler errors since it usually leads to no errors at all because users forget to turn them on even if the corresponding bug is already fixed.
The reason for the current issue is that the plugin doesn't expand procedural macros by default for now. But it can do it.
Just enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` [experimental](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) features

See #6908 for more details
