### ISSUE TITLE
launch profiles unable to parse options

### ISSUE THREAD

**Issue by InfRandomness** [intellij-rust/intellij-rust#8472]
## Environment

* **IntelliJ Rust plugin version:0.4.163.4378-213**
* **Rust toolchain version:**
```
cargo 1.59.0-nightly (fcef61230 2021-12-17)

rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.59.0-nightly (91a0600a5 2021-12-18)`
```
* **IDE name and version: CLion 2021.3.2**
* **Operating system: Fedora 35**

## Problem description
rust-intellij is unable to parse launch profiles with certain options (like --profile)
![image](https://user-images.githubusercontent.com/43730933/151168004-8d8e274e-6dc1-43be-8298-34641d59c80a.png)

## Steps to reproduce
Clone https://gitlab.com/veloren/veloren (don't forget to install and initialize git lfs)
Open it in clion
Create a launch profile like this one 
![image](https://user-images.githubusercontent.com/43730933/151167849-85964a72-915d-4ff1-a751-aba8dc4069a1.png)

**Comment by nathanvoglsam** [comment]
Is there any update on this? With cargo stabilizing custom profiles this feature becomes more important. It's really useful when multiple tiers of 'debug' build are needed like with games where different levels of tradeoff between runtime performance and debuggability are needed.

The behavior of this has changed since the initial report too. `cargo build --profile <some profile>` now works correctly, but does not work with `cargo run --profile <some profile>` which triggers the same error message as in the initial report.
