### ISSUE TITLE
Not compatible with IDEA 2017.1?

### ISSUE THREAD

**Issue by ForsakenHarmony** [intellij-rust/intellij-rust#851]

**Comment by matklad** [comment]
Fixed in https://github.com/intellij-rust/intellij-rust/commit/05dd7b904891b4b952d9dd1d7c01323523009640

You can download the latest build from here: https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_CurrentIdea_TestsRust/954616:id/intellij-rust-0.1.0.1321.zip

Thanks for the report!

**Comment by ForsakenHarmony** [comment]
Same applies to the TOML plugin

**Comment by matklad** [comment]
Yep, I've forgot to publish the TOML plugin, here it is now: https://plugins.jetbrains.com/idea/plugin/8195-toml/31357-update
