### ISSUE TITLE
Failed to parse the `edition` key

### ISSUE THREAD

**Issue by panstromek** [intellij-rust/intellij-rust#8517]
## Environment

* **IntelliJ Rust plugin version:** 0.4.164.4409-213
* **Rust toolchain version:** 1.60.0-nightly (27f5d830e 2022-02-02) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.3.3 (CL-213.6777.58)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
Project sync fails with this error:

```
Execution failed (exit code 101).
C:\Windows\system32\wsl.exe --distribution ubuntu --exec /bin/sh -c "export PATH=\"/home/matyas/.cargo/bin:$PATH\" && export RUST_BACKTRACE=short && export TERM=ansi && cd /home/matyas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test && /home/matyas/.cargo/bin/cargo vendor /mnt/c/Users/panstromek/AppData/Local/JetBrains/CLion2021.3/intellij-rust/stdlib/1.60.0-nightly-da0947d6a3255f7cde017d47d074aabb849e246a/vendor"
stdout : error: failed to parse manifest at `/home/matyas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.

stderr : 
```
This project runs in WSL

## Steps to reproduce

I am not sure how, but could it be that the directory override is not used by the sync command? My stable version is 1.49, but the project uses 1.60 nightly via directory override.

**Comment by Undin** [comment]
Thanks for the report!
It's an interesting case that wasn't taken into account previously.
The reason is quite simple - the plugin invokes `cargo metadata` not only for project crates but also for stdlib crates. And currently, we don't pass proper toolchain if you use `rustup override`. In most cases, it doesn't matter, but it looks like since 1.60 stdlib uses 2021 edition and 1.48 doesn't know about the new edition version. As a result, `failed to parse the `edition` key` error
