### ISSUE TITLE
"no field named  xxx" when evaluate expressions

### ISSUE THREAD

**Issue by doki23** [intellij-rust/intellij-rust#8672]
## Environment

* **IntelliJ Rust plugin version: 0.4.166.4486-213**
* **Rust toolchain version: 1.24.3**
* **IDE name and version: Intellij idea 2021.3.2**
* **Operating system: macos**

## Problem description
let me define some variables to describe the problem:
an arc trait object: obj, with type Arc\<dyn my_trait\>
function of my_trait: func(&self) -> xxx
evaluated expression when debugging:  obj.func()
The error "no field named  func" occured.

## Steps to reproduce
as mentioned above

**Comment by ortem** [comment]
Expression evaluation in the debuggers does not support method calls so far. Unfortunately, this cannot be implemented until rustc emits enough debug information about traits: https://github.com/rust-lang/rust/issues/33014. Thus, the issue has to be fixed on the compiler side before implementing this functionality in debuggers and IDE.

**Comment by benze** [comment]
Sorry to resurrect an old bug, but I'm running into the same difficulties.
Any suggestions how one can work around this limitation in the meantime to debug code?
What does everyone else do?

**Comment by bioinfornatics** [comment]
Indeed this feature would help a lot

**Comment by zinking** [comment]
how does people work around this when debugging rust stuff? by not using `dyn`?

**Comment by Grunthos** [comment]
@artemmukhin The rust bug that you quote from GitHub is for making trait details available to gdb and has been given a low priority in rust as a result.

However the problem with RustRover is not limited to traits (I think!). Examining `some_var.is_some()` on any optional results in `no field named is_some`.

**Comment by artemmukhin** [comment]
@Grunthos Yes, you're absolutely right. The root problem lies in the interoperability of Rust compiler code generation and debuggers (GDB, LLDB) at a deep level. From what I've seen, sometimes the Rust compiler does not use proper LLVM internals to generate specific information; often GDB or LLDB cannot leverage the information properly – generally, they treat Rust as C/C++ with some slight adjustments, because, as far as I know, nobody has fully implemented Rust's syntax, type system, and runtime support for them.

Speaking of your example, as far as I know the situation, supporting some simple function calls is doable at the GDB/LLDB level, but it might be challenging and not worthwhile without a matching effort from the compiler side.
