### ISSUE TITLE
Can't use smart keys

### ISSUE THREAD

**Issue by asaning** [intellij-rust/intellij-rust#8948]
## Environment

* **IntelliJ Rust plugin version: *0.4.172.4687-221*
* **Rust toolchain version: **
* **IDE name and version: *Clion Build #CL-221.5787.29, built on June 1, 2022*
* **Operating system:*macos*

## Problem description

i can't use tab to skip ) when i invoke function

## Steps to reproduce
![image](https://user-images.githubusercontent.com/99789353/174195020-21b62de9-0892-4e9f-9c03-85f5321fd64b.png)
when i print the ``` println!("")``` i can use tab to skip ", but when i want to use tab skip ) it doesn't work.

**Comment by Talented-6** [comment]
Yeah, I have met the same bug too. It's quite disgusting to meet such a bug.😂

**Comment by Talented-6** [comment]
I can add a few clues to find where the bug is.
**When I type the '(' mannually instead of input the 'println' and press button `TAB` to let it complete the brackets automatically, the smart keys work normally.**
So before the bug was repaired, I suggest mannually input the function and left bracket.
