### ISSUE TITLE
Feature request: Allow excluding type/function suggestions

### ISSUE THREAD

**Issue by TobiasDeBruijn** [intellij-rust/intellij-rust#8971]
## Environment

* **IntelliJ Rust plugin version:** 0.4.172.4687-221
* **IDE name and version:** CLion 2022.1.3
* **Operating system:** Ubuntu 22.04 LTS

## Problem description
When writing code, a case that I often run into is `format`. 99% of the time I want the `format!` macro, but quite often I end up importing the `format` function (both from `std`). This feature request aims to solve that, by allowing the user to configure 'import exclusions'.

This could be a simple dialog where the user can enter the fully qualified path to the type/function/whatever to exclude. The import suggestions should then no longer mention that exclusion.

In IntelliJ for Java something similar is present at `Settings | Editor | General | Auto Import | Java | exclude from auto-import and completion`. CLion doesn't have such a dialog for C/C++. For Rust a similar dialog could be presented to the user for Rust exclusions.

I'm unsure if this feature is doable with just the intellij-rust plugin, or if it requires support at the IDE level (in e.g. CLion). I spoke to @ozkriff in the Rust Programming Language discord about this [here](https://discord.com/channels/273534239310479360/335502067432947748/990297907301335100)

Thanks in advance!

**Comment by vlad20012** [comment]
I think that really there is a bug, and I suppose that fixing that bug makes will make the feature request a bit irrelevant for you.

In JetBrains IDEs usually there is a "stats"-based completion ranking. That meant that if you use "format!" macro more often than `format()` function, the macro completion variant should be sorted upper in the completion list.

The bug is that we're disprefering macros in the completion variant list regardless of "stats", so you see `format()` function before `format!` macro anyway

**Comment by TobiasDeBruijn** [comment]
That makes sense too. Want me to open a bug report for that?

**Comment by vlad20012** [comment]
> That makes sense too. Want me to open a bug report for that?

I think yes. I've been wanting to fix this for a long time, but we don't have issues about it, so this had a bit low priority 😅

**Comment by TobiasDeBruijn** [comment]
Makes sense! I'll open an issue refering this one once I'm home.

I do think we should keep this one open as well, as some probably will find it useful.
