### ISSUE TITLE
Suggestion: doctest should have the test gutter icons

### ISSUE THREAD

**Issue by jendrikw** [intellij-rust/intellij-rust#9098]
## Environment

* **IntelliJ Rust plugin version:** 0.4.174.4743-221
* **Rust toolchain version:** 1.62.0 (a8314ef7d 2022-06-27)
* **IDE name and version:** Clion 2022.1.3
* **Operating system:** Arch Linux 5.17.8

## Problem description
I would be nice to have the [test gutter icons](https://www.jetbrains.com/help/idea/performing-tests.html) on doctest, to get an overview of what tests failed and to quickly rerun a single test.

## Steps to reproduce

```
/// Example module
/// ```
/// assert_eq!(1, 2);
/// ```
mod example {}
```

**Comment by Kobzol** [comment]
I tried to look into this, but so far I haven't found a way to execute a specific doctest. I asked about this on the [forum](https://users.rust-lang.org/t/how-to-run-a-specific-doctest/78715), if there will be a way to do this, I'll try to implement it.

**Comment by jendrikw** [comment]
It'd be ok for me if it run all test on a method. That is doable with `cargo test --docs module::Type::method`.

**Comment by Kobzol** [comment]
This is not enough, because if there was a method called `module::Type::method2`, the mentioned command would also executed that one (since `module::Type::method` is part of the second method's name). However, I found a way to execute a specific doctest, so this problem has been hopefully resolved. I'll try to send a PR soon if I can get it to work :)

**Comment by jendrikw** [comment]
Great, thanks for looking into this!

**Comment by jendrikw** [comment]
Great, thanks for looking into this!
