### ISSUE TITLE
Crate version autocompletion: suggest the last stable version by default, not {}, "", or alphas

### ISSUE THREAD

**Issue by Riateche** [intellij-rust/intellij-rust#9116]
## Environment

* **IntelliJ Rust plugin version:** 0.4.176.4773-221-nightly
* **Rust toolchain version:** 1.62.0 (a8314ef7d 2022-06-27) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.1.2 (CL-221.5787.29)
* **Operating system:** Linux 5.10.0-16-amd64
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.emulate.terminal

## Problem description
I was adding dependencies to Cargo.toml in this way:
- Type the beginning of crate name, e.g. `future` and press Ctrl+Space
- Select the correct crate, e.g. `futures` and press Enter. IDE inserts `futures = "[cursor]"` and opens version list.
- Press Enter again to select the first suggestion, which was usually the last stable release.

Unfortunately, this no longer works because `{}` is now the default suggestion. Choosing this suggestion generates `futures = "{[cursor]}"`, which doesn't make sense. The usefullness of `{}` in the list is questionable, as it's pretty easy to type by hand.

If I invoke autocomplete on `futures = [cursor]`, it also suggests `""` as the second best option, which is pretty useless and also gets in the way of selecting a version.

I would love to see my workflow (double press Enter to select the latest version) to work again.

Another issue is that new alpha releases appear at the top of the version list, and selecting the last stable release requires skipping the alphas. For example, For an example, for `heron` crate, he plugin currently suggests `4.0.0-alpha.2` and `4.0.0-alpha.1` first, and stable `3.1.0` is the third option. I'd argue that adding a stable version is far more common and should be prioritized in auto completion.

**Comment by afetisov** [comment]
The weird thing is that the tests for TOML dependency completions (CargoTomlDependencyCompletionTest and LocalCargoTomlDependencyVersionCompletionTest) ostensibly test that the exact specified scenario works. Are the test written incorrectly, so that some other completion provider isn't firing?

**Comment by Undin** [comment]
We found the reason of additional items in the completion list - support for json schemes in TOML files by TOML plugin.
And previously, the corresponding integration didn't affect us because there wasn't the corresponding json scheme for Cargo.toml. But now, there is https://json.schemastore.org/cargo.json and common json scheme in IDE integration uses schemes from https://json.schemastore.org by default. As a result, TOML plugin started to take it into account and provide additional items

At this moment, I don't know what's exactly wrong - scheme itself or some code in TOML plugin. But as workaround, you can disable `org.toml.json.scheme` registry option (`Help | Find Action` and type registry) for now

**Comment by avrong** [comment]
@Undin I'm almost sure that this all is caused by [this line in intellij.toml.json.xml](https://github.com/JetBrains/intellij-community/blob/fa8cca6230854d58e7a5e77aea5829fd8ecf378c/plugins/toml/json/src/main/resources/intellij.toml.json.xml#L7). I guess I wasn't thinking of these two completion providers overlapping and assumed that JSON schema should be the one prioritised for completion. So removing `order="first"` from there should eventually fix this, if not, we can specify `order="first"` to the version completion in `intellij-rust` as this one should be prioritised in cargo manifest.
