### ISSUE TITLE
intellij-rust parse thiserror::Error has problem

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#9133]
## Environment

* **IntelliJ Rust plugin version:** 0.4.176.4779-222-nightly
* **Rust toolchain version:** rustc 1.64.0-nightly (3924dac7b 2022-07-29)
* **IDE name and version:** CLion 2022.2
* **Operating system:** Archlinux

## Problem description

when an enum Error derived by `thiserror::Error`, it implements the `Display` but intellij-rust doesn't think so

## Steps to reproduce

```rust
#[derive(thiserror::Error, Debug)]
enum Error {
    #[error("{0}")]
    Io(String),
}

fn main() {
    let err = Error::Io("123".to_string());

    println!("{}", err);
}
```

intellij-rust will say 
![image](https://user-images.githubusercontent.com/10096425/181908445-12f3d0ff-cf1c-419d-8900-5b97532beae0.png)

**Comment by aldanor** [comment]
Same with `derive_more`:

![image](https://user-images.githubusercontent.com/2418513/182262009-e541695c-5325-4a4b-9f93-86e3917f1cd3.png)

**Comment by Undin** [comment]
@Sherlock-Holo @aldanor I suppose experimental procedural macro expansion is not enabled in your cases. To turn it on, you need to enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` [experimental](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) features.

See #6908 for more details

**Comment by aldanor** [comment]
@Undin indeed, it looks like in my case the build scripts were turned off.

(not sure if related issue or not, but since last release code analysis has become acting weird, not always re-running on save and sometimes refusing to re-analyze the code for very long periods of time; so I often have to invalidate caches and restart in order for it to start acting normal again... never seen this happening before)

**Comment by Kubuxu** [comment]
I have the same issue, both options are enabled but it still doesn't work.
