### ISSUE TITLE
Plugin doesn't automatically refresh after editing Cargo.toml

### ISSUE THREAD

**Issue by AndWass** [intellij-rust/intellij-rust#9148]
## Environment

* **IntelliJ Rust plugin version:** 0.4.175.4772-222
* **Rust toolchain version:** 1.62.0
* **IDE name and version:** CLion 2022.2
* **Operating system:** OpenSuse Tumbleweed

## Problem description

For some reason the plugin has stopped automatically refreshing the cargo project after editing and saving `Cargo.toml`. I must now manually press a button to perform a refresh.

## Steps to reproduce

Add a dependency to your project in `Cargo.toml`.

Try to use the dependency, CLion won't find anything relating to it, autocomplete won't work.

Push button to refresh the project.

Auto complete now works as expected.

**Comment by Undin** [comment]
It's expected because the plugin migrated to new internal framework to detect project model changes (i.e. changes in `Cargo.toml` files) used in most other build systems since 2022.2 IDEs. And new default behavior is to refresh the project model only on external changes (i.e. changes made by version control) because it allows you to control when project model update is performed not to break your workflow.
If you prefer the previous behavior, just switch to `Any changes` option in `Preferences | Build, Execution, Deployment | Build Tools` settings
<img width="1094" alt="Screenshot 2022-08-02 at 13 23 05" src="https://user-images.githubusercontent.com/2539310/182363158-48f93faf-e65c-4c08-8d28-d81a9de72fae.png">

**Comment by AndWass** [comment]
Thanks for the explanation!

Would it be possible to have the notification be more visible. For instance CMake prompts in a much more visual way with a banner at the top of the CMakeLists file
![image](https://user-images.githubusercontent.com/1329621/182365832-faedbd9c-6132-456a-a8c3-dd97aacd8918.png)

compared to the cargo notification which is just a tiny little floating box
![image](https://user-images.githubusercontent.com/1329621/182365961-6bfe5241-fdb4-45a4-852f-18e4fbe6e591.png)

**Comment by Undin** [comment]
We didn't plan to do it to be consistent with other build tools like Gradle. At least, at this moment.
From my point of view, CMake solution is too cluttered and floating button works well

**Comment by AndWass** [comment]
Not saying it needs to be consistent but at least for me, the auto reload just suddenly stopped working and it took me a fair amount of time before I found the reload button because it was so small (and no text telling me what is happening). From my perspective the current solution was confusing until I filed this bug report (a couple of days).

Now when I do know about it I can probably live with it though.

**Comment by Undin** [comment]
> the current solution was confusing until I filed this bug report 

The previous solution was more confusing (at least from my point of view) because it depended on save events which happen in some unpredictable time from user point of view and to control it, you have to save all files manually (and it's weird in IntelliJ ecosystem) or invoke Cargo refresh manually (it's the same as current default behaviour but now you have a UI element indicates about it)

> Now when I do know about it I can probably live with it though.

Or, you can enable project model reloading on each change. In any case, don't hesitate to share your experience
