### ISSUE TITLE
Formatter should indent wrapped imports to same alignment as previous line

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#937]
```rust
use piston_window::{Button, clear, Context, Event, Input, Key, PistonWindow, text, types,
    Transformed};
```

Should be formatted to

```rust
use piston_window::{Button, clear, Context, Event, Input, Key, PistonWindow, text, types,
                    Transformed};
```

According to `rustfmt` 0.6.3:

```rust
 use piston_window::{Button, clear, Context, Event, Input, Key, PistonWindow, text, types,⏎
-    Transformed};⏎
+                    Transformed};⏎
```

@matklad Is the goal of the intellij-rust formatter is to default to what `rustfmt` does? Just want to make sure I'm not reporting issues that aren't actually in scope for where intellij-rust wants to go (but I assume this would be a positive).

**Comment by matklad** [comment]
>Is the goal of the intellij-rust formatter is to default to what rustfmt does?

Yes!

**Comment by matklad** [comment]
By the way, you can run `rustfmt` directly from the IDE: <kbd>Ctrl+Shift+A</kbd> **Reformat file with rustfmt**.

**Comment by johnthagen** [comment]
Thanks! Exactly what I was looking for. I was playing around with [external tools](https://www.jetbrains.com/help/idea/2016.3/external-tools.html), but this is much nicer. One to run `clippy` would be cool too.

**Comment by matklad** [comment]
https://github.com/intellij-rust/intellij-rust/issues/938

**Comment by matklad** [comment]
>Thanks! Exactly what I was looking for. I was playing around with external tools, but this is much nicer. One to run clippy would be cool too.

I think you can use run configuration for clippy at the moment? Specify `clippy` as cargo command, and add `RUSTUP_TOOLCHAIN=nightly` to the environmental variables of the run config.

**Comment by johnthagen** [comment]
>I think you can use run configuration for clippy at the moment? Specify clippy as cargo command, and add RUSTUP_TOOLCHAIN=nightly to the environmental variables of the run config.

@matklad Thanks, that works pretty well. Only downside to a run configuration is that IntelliJ seems to like to color stderr in red, so you lose the colored output from clippy as compared to a normal run from the Terminal. You know of an easy way to deal with that?

**Comment by alygin** [comment]
@johnthagen, unfortunately `cargo` doesn't pass the `--color` option to `clippy`, so adding `--color=always` has no effect on this command. A (bit ugly) workaround would be to call `rustc` instead of `clippy` and pass the color option directly to it:

```
rustc -- -L [path_to_clippy_lib_dir] -Z extra-plugins=clippy --color=always
```

This command works and even respects `--color=always`, but for the reason I'm not aware of, one of two things happens: either `cargo` emits incorrect ANSI symbols or the IntelliJ displays them incorrectly:

<img width="506" alt="screen shot 2017-01-16 at 21 00 21" src="https://cloud.githubusercontent.com/assets/2101250/21994061/dfa0184c-dc2e-11e6-8ce4-468fe82928fb.png">

I don't know how to fix this corrupted output. But maybe someone has any ideas on this?

**Comment by johnthagen** [comment]
@alygin Even passing `-- --color=always` to `clippy` in a run configuration seems to strip out the colors (I think IntelliJ is doing something in the background related to coloring stderr red). Check out:

![clippy-color](https://cloud.githubusercontent.com/assets/10340167/22000750/fc06b5f6-dc0e-11e6-9b58-0972263d82ad.png)

**Comment by johnthagen** [comment]
@alygin I looks like `Editor > Colors & Fonts > Console Colors > Console > Error Output` could be the culprit. @matklad any ideas?

**Comment by alygin** [comment]
> I think IntelliJ is doing something in the background related to coloring stderr red

You're right, I completely forgot about that. We only use `withRedirectErrorStream()` (which allows to colorise the output) when the executed cargo command is one of the predefined (one of those that support the `--color` option propagation).

We could use the stderr redirection every time there's the `--color` option is specified (either implicitly by the plugin or explicitly by the user), not only for the predefined list of commands. But there're two problems here:

- It won't help with the `clippy` command because `cargo` doesn't pass it to pluggable commands [on purpose](https://github.com/rust-lang/cargo/issues/3474). Though, it'll let you use the `rustc` command I described above, it will produce colored output.
- Theoretically, some other pluggable commands can have the `--color` option with absolutely different meaning, which might introduce a problem (we'll switch colors on when the user doesn't expect it).

Or we could also add a separate checkbox "Colored output" to run configurations. But it should only present on Linux and Mac, which is not good.

Actually, I see no perfect solutions here. @matklad, what do you think?

**Comment by johnthagen** [comment]
> It won't help with the clippy command because cargo doesn't pass it to pluggable commands on purpose. 

I guess I don't understand this. When I run `cargo +nightly clippy` in the IntelliJ Terminal, or just in a terminal outside of IntelliJ, the colors just work. What exactly isn't propagated?

Also, I clippy currently has a bug on Windows (https://github.com/Manishearth/rust-clippy/issues/1422) so I can't run it on a Windows machine, but `rustfmt` colorizes everything nicely in the IntelliJ terminal, so it seems like it could work?

**Comment by alygin** [comment]
`rustc` (and I think `cargo` as well) [uses some checks](https://github.com/rust-lang/rust/blob/7f2d2afa9196ba6314a29e58d5324dbd9923c75e/src/libterm/terminfo/mod.rs#L83) to find out if it's running in an environment that supports colors. If not, the colored output is suppressed. But you can force it by passing the `--color=always` option to the command (or explicitly suppress it by passing `--color=never`).

Cargo also supports the `--color` option, but it relies on other programs. For instance, `cargo build` executes `rustc` and passes some of its own options to the compiler, including `--color` (if it has been specified explicitly). But when you execute `cargo clippy`, the `--color` option is not passed to `rustc` (which is the actual clippy's engine) because cargo treats `clippy` as a pluggable command and makes no assumptions on what options it supports.

So, `cargo build --color=always` forces colored output in the underlying `rustc` command, while `cargo clippy --color=always` does not.

The IntelliJ command output window handles output in a special way (for instance, it paints all the stderr output red), so we have to reconfigure it a bit and add the `--color=always` option every time we run a command that we know supports colored output.

The IntelliJ terminal (and the outside one) works another way and is treated by `rustc` (as well as by `cargo`) as color-friendly. So, no additional actions needed to force colors.

I don't know, what exactly is the difference in implementation of these two windows. Maybe Alexey can answer this. But the fact is that when you execute `cargo clippy --color=always`, the underlying `rustc` command remains unaware of this `--color` option, so it fully relies on its checks (mentioned above) that fail to recognise the IntelliJ command output window as suitable for colored output. And here we are, with the red stderr text.
