### ISSUE TITLE
No autocompletion of stdlib items in detached files

### ISSUE THREAD

**Issue by KaimingWan** [intellij-rust/intellij-rust#9422]
## Environment

IntelliJ Rust plugin version: 0.4.179.4903-222
Rust toolchain version: rustup 1.25.1 (bb60b1e89 2022-07-12)
IDE name and version: Clion 2022.2
Operating system: MacOS 12.6

## Problem description
- String:: not give auto completion

<img width="677" alt="image" src="https://user-images.githubusercontent.com/4374015/192778968-3a40ce0c-71f2-4891-9acd-6da4af9e192b.png">

- Not support std module auto import
<img width="806" alt="image" src="https://user-images.githubusercontent.com/4374015/192779142-201e9013-bad0-4936-878d-9f0bed890989.png">

## Steps to reproduce

The code is easy to find. They are exercises in project rustlings, file string1.rs and module3.rs . Click [string1.rs](https://github.com/rust-lang/rustlings/blob/main/exercises/strings/strings1.rs) and [module3.rs](https://github.com/rust-lang/rustlings/blob/main/exercises/modules/modules3.rs) to check

**Comment by Undin** [comment]
It's expected because all exercises in rustlings just a separate rust files not connected to any cargo project.
As a result, the plugin doesn't know about project model here including info about stdlib that leads to absence of some completion suggestions

BTW the plugin even tells you that something is wrong here

<img width="770" alt="Screenshot 2022-09-28 at 14 41 53" src="https://user-images.githubusercontent.com/2539310/192781245-2b43a062-93a8-413d-b216-aa12a962e069.png">

**Comment by Undin** [comment]
Currently, the only "solution" I see is to somehow attach such files to cargo project (probably, via [workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html))

But it seems the plugin can consider such files as virtual crate roots, adds known stdlib as a dependency and some analysis and completion from stdlib will work. We already [discussed](https://github.com/intellij-rust/intellij-rust/issues/8853#issuecomment-1132613105) this approach in context of scratch files

**Comment by KaimingWan** [comment]
@Undin Thanks. I am looking forward to see the feature that support virtual crate roots. BTW, the first auto complete not work is still a problem, am I right ?

**Comment by Undin** [comment]
@KaimingWan no, `String::new` is a function from stdlib => completion doesn't work because of the same reason

You can check it in any file which belongs to a cargo project, for example, in `src/main.rs`. Completion of items from stdlib will work

Unfortunately, `rustlings` are designed in a non IDE-friendly way. As a result, students get proper support neither in IntelliJ ecosystem nor in VSCode + rust-analyzer.
But there is IDE-friendly adaptation of [rustlings](https://plugins.jetbrains.com/plugin/10081-edutools/docs/learner-start-guide.html?section=Rustlings) for IntelliJ available via [EduTools](https://plugins.jetbrains.com/plugin/10081-edutools) plugin

**Comment by KaimingWan** [comment]
@Undin Thanks for your response. I will try EduTools and keep an eye on [intellij-rust](https://github.com/intellij-rust/intellij-rust)
Public
