### ISSUE TITLE
Complete `static` as known lifetime name

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#9435]
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4890-222-nightly
* **Rust toolchain version:** 1.66.0-nightly (9c56d9d6f 2022-09-29) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.2 Ultimate Edition (IU-222.3345.118)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
If I want to use `'static` lifetime for a field, the plugin doesn't help me to write `static` although it's a special name and the plugin can always suggest it

## Steps to reproduce
```rust
struct FeatureDef {
    name: &'sta/*caret*/
}

```

**Comment by Kobzol** [comment]
I looked at this, and tried to create a `ScopeEntry` for `'static`. But for that I need some (target) `RsElement`, otherwise the completion code does not work (there are a lot of places where it expects the element otherwise it "panics"). Is there some better way to complete things that don't have any element? Should I create a fake element or complete this somewhere else than in `RsCommonCompletionProvider` via some special completion provider?

**Comment by Undin** [comment]
I don't think that using `ScopeEntry` is the best approach since it's a part of name resolution in the first place. But `'static` doesn't have a definition, so nothing needs to be resolved

I'd personally just implement a simple completion provider
