### ISSUE TITLE
broken code navigation (minimal example included) IDEA Ultimate

### ISSUE THREAD

**Issue by panov-andy** [intellij-rust/intellij-rust#9534]
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4932-222
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2022.2.3 Ultimate Edition (IU-222.4345.14)
* **Operating system:** Linux 5.15.0-48-generic
* **Macro expansion:** enabled

## Problem description
Navigation to code declaration doesn't work (Ctrl+B) and it does work for the same code in Fleet.

## Steps to reproduce
 - Clone & open project https://github.com/panov-andy/kubeapi-prometheus
 - find line [let ipv4_packet = Ipv4Packet::new(ethernet.payload()).unwrap();](https://github.com/panov-andy/kubeapi-prometheus/blob/5f7835031b8d06c2167975481e8f8e5591cef6d4/src/main.rs#L32)
 - try goto declaration on `::new` <- expected to work (and it's working in Fleet)

**Comment by Undin** [comment]
@panov-andy thanks for the report!

It is expected behavior since `Ipv4Packet::new` is generated by [procedural macro](https://docs.rs/pnet_packet/0.31.0/src/pnet_packet/ipv4.rs.html#138) but procedural macro expansion is not enabled by default yet.

To make it work, you can enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` [experimental](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) features and [reload](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-cargo-tool-window.html#manual-reloading) project model. See #6908 for more details

**Comment by panov-andy** [comment]
These experimental features enabled work for me. Thank you.

**Comment by Undin** [comment]
Let's keep it open since proc macro expansion is not enabled by default yet
