### ISSUE TITLE
Debugging gives error - "The code execution cannot proceed because ..." (`cargo:rustc-link-search`)

### ISSUE THREAD

**Issue by ralfbiedert** [intellij-rust/intellij-rust#9701]
## Environment

* **IntelliJ Rust plugin version:** 0.4.182.4996-222
* **Rust toolchain version:** 1.67.0-nightly (85f4f41de 2022-11-08) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.2.4 (CL-222.4345.21)
* **Operating system:** Windows 11 10.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.cargo.features.settings.gutter, org.rust.macros.proc.derive, org.rust.cargo.emulate.terminal, org.rust.macros.proc.function-like, org.rust.macros.proc

## Problem description

This issue both happens in my own app, and when trying to debug [tch](https://github.com/LaurentMazare/tch-rs) directly:

While running any app depending on tch works fine, when trying to **debug** one I get a flurry of errors like the one below, basically saying:

> System Error - The code execution cannot proceed because torch_cuda_cu.dll was not found. Reinstalling the program may fix this problem.

![image](https://user-images.githubusercontent.com/301288/200775598-0c212a3b-7302-4bb6-95e6-ad3173a7e0de.png)

This error is repeated for each missing DLL:

- torch_cuda_cu.dll
- torch_cpu.dll
- torch_cuda_cpp.dll
- c10.dll

I suspect this happens because the debugger for some reason does not honor `cargo:rustc-link-search=native={}` emitted by `build.rs`. Even when debugging that variable is set ...

```
  --- stdout
  cargo:rerun-if-env-changed=TORCH_CUDA_VERSION
  cargo:rerun-if-env-changed=LIBTORCH
  cargo:rustc-link-search=native=C:\Users\rb\Development\Source\_thirdparty\tch-rs\target\debug\build\torch-sys-28a1400f35c20e0f\out\libtorch\libtorch\lib
...
```
... and the folder it points to contains the relevant DLLs:

![image](https://user-images.githubusercontent.com/301288/200776740-69cb13d4-3322-4db5-9e9b-5d4d462f9934.png)

Again, just "Running" the examples works fine.

## Steps to reproduce

1. Clone https://github.com/LaurentMazare/tch-rs
2. Open the project in CLion
3. Under `Build, Execution, Deployment -> Toolchains` select `Visual Studio`
4. Open any of the examples, like  `example/cifar/main.rs` 
5. Try to debug it

You might also have to set your environment variable `TORCH_CUDA_VERSION` to `cu117` but this is probably unnecessary.

**Comment by ortem** [comment]
@ralfbiedert Thank you for the detailed report.

I think normal running works fine because the dynamic library path is set [by Cargo](https://doc.rust-lang.org/cargo/reference/environment-variables.html#dynamic-library-paths) when running a binary using `cargo run` (which is called by IDE when you press `Run`). However, when you press `Debug`, the debugger launches a binary without using Cargo, so the dynamic library path is just not set. To take it into account, try to add the corresponding path to `PATH` environment variable in the [Cargo run configuration settings](https://plugins.jetbrains.com/plugin/8182-rust/docs/cargo-command-configuration.html).

This should resolve the "The code execution cannot proceed" system error. But just in case, if the breakpoints will not work properly, try adding `settings set target.exec-search-paths /path/to/directory/with/unstripped/library` to the [lldbinit](https://www.jetbrains.com/help/clion/configuring-debugger-options.html#gdbinit-lldbinit) file.

**Comment by ralfbiedert** [comment]
Thanks! Yes, I can confirm setting `PATH` to that folder will make it debug. 

It would still be nice if the Rust plugin would process the `cargo:rustc-link-search=native={}` build output and do that for me.

**Comment by ortem** [comment]
Duplicate of #6814.
