### ISSUE TITLE
Parser does not support struct literal shorthand syntax (RFC 1682)

### ISSUE THREAD

**Issue by himikof** [intellij-rust/intellij-rust#986]
This was recently implemented and seems to be on the road to stabilization. Defined by rust-lang/rfcs#1682.

**Comment by bgourlie** [comment]
It should be noted that this will break rename refactoring. Consider the following scenarios:

```rust
struct SomeStruct {
    foo: u8,
    bar: u8
}

fn new_struct() -> SomeStruct {
    let foo = 1;
    let bar = 2;

    SomeStruct {
        foo, 
        bar
    }
}
```

- What happens if we rename the struct field? Does it rename bindings used in short-hand?
- What happens when we rename the binding? Does it rename the struct field? Does it convert the struct to long-form?

**Comment by matklad** [comment]
Good catch @bgourlie! This is partially fixed in https://github.com/intellij-rust/intellij-rust/commit/46fda4101abba0a912692be9a4e8e8d3fec3145b. Renaming the struct field should work fine. 

Renaming the let binding would not work as expected at the moment.
