### ISSUE TITLE
"Unsupport" `abi_efiapi` feature

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#9993]
## Environment

* **IntelliJ Rust plugin version:** 0.4.187.5141-223-nightly
* **Rust toolchain version:** 1.68.0-nightly (4781233a7 2023-01-16) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.3.1 Ultimate Edition (IU-223.8214.52)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal

## Problem description
The feature will be stabilized from the 1.68 rust version,  see https://github.com/rust-lang/rust/issues/65815
The code is correct. 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/49211026/212887424-0ee5648a-36ac-4cf1-9ecd-31063a781c99.png">

## Steps to reproduce
```rust
// #![feature(abi_efiapi)]

extern "efiapi" { fn f1(); }

extern "efiapi" fn f2() { todo!() }

```

**Comment by Undin** [comment]
@neonaot you need just to merge #9984 to fix it

**Comment by neonaot** [comment]
wow, I thought that you need to remove it from some source code too, like in https://github.com/intellij-rust/intellij-rust/pull/9930/files

**Comment by Undin** [comment]
No
#9930 was made because some features were **removed** and we had some special support (except highlighting syntax as experimental) for them. In this case, the plugin just annotates some syntax as experimental where it relies on feature state in the corresponding list. And this check handles if a feature became stable but without #9984 it just doesn't know about it
